[BE] Teamplace 참가 여부를 확인하는 TeamPlaceInterceptor 구현
woowacourse-teams/2023-team-by-team pull request #130
Opened 2023-07-20 02:29 UTC by SproutMJ

## 이슈번호
#30

## PR 내용
Teamplace 참가 여부를 확인하는 TeamPlaceInterceptor 구현

## 참고자료

## 의논할 거리

2023-07-20 05:26 UTC, pilyang requested changes
Request Change (개행) 하나 있습니다!!

다른 하나 좀 긴 커멘트 있는데 해당 부분은 다른 백엔드 팀원들과 다같이 이야기 해보는 시간 가져요..!!

2023-07-20 05:26 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/teamplace/configuration/TeamPlaceInterceptor.java
> +        }
해당 부분에 대해서는 다같이 이야기 해보는게 좋을 것 같아요. (@SproutMJ @sh111-coder @the9kim )

지금의 코드에서는 `MemberTeamPlaceRepository`에서 가져온 `MemberTeamPlace`객체를 로직을 구현하는데 사용하고 있는데, 해당 객체는 맵핑을 위한 객체여서, 이보다는 `Member`나  `TeamPlace` 객체를 이용하고, `MemberTeamPlace`클래스는 해당 Member나 TeamPlace객체의 내부에서만 사용하는것이 좋지 않을까 합니다.

추가로 주요 로직들을 도메인으로 이동시킬 수 있을 것 같습니다.

아래 제가 생각한 예시 코드도 첨부합니다..!! 해당 내용들은 다같이 모여서 한번 정리할 필요가 있어보입니다!!

```java
        final TeamPlace teamPlace = teamPlaceRepository.findById(teamPlaceId)
                .orElseThrow(() -> new TeamPlaceException.NotFoundException("ID에 해당하는 팀 플레이스를 찾을 수 없습니다."));
        final Member member = memberRepository.findByEmail(email)
                .orElseThrow(() -> new TeamPlaceException.TeamPlaceAccessForbidden("접근할 수 없는 팀플레이스입니다."));

        // 해당 도메인이 팀플레이스 도메인이라서 팀플레이슬라는 주체에게 멤버를 건내주며 물어보는 식으로 일단 짜기는 함...
        // 이부분은 일단은 우리가 양방향 참조를 하고있어서 이리 했는데, 나중에 teamplace  에서의 양방향 참조를 끊는다면 아래 주석처리한것과 같은 방식이 더 효율적이고 안전하다고 생각함
        if (teamPlace.hasMember(member)) {
            throw new TeamPlaceException.TeamPlaceAccessForbidden("접근할 수 없는 팀플레이스입니다.");
        }
        // 양방향 참조를 안한다고 생각을 한다면..!! (TeamPlace에서는 Member 도메인에 대해서 모르는 경우..!!)
        // 물론 이경우도 다시 생각해보면 현 TeamPlace 패키지에서 Member를 가지고 있으니까 완벽하게 참조를 끊은것은 아님.. 양방향 안한다면 참조 끊는법은 더 고민..!
//        if (member.isMembeerOf(teamPlace)) {
//            throw new TeamPlaceException.TeamPlaceAccessForbidden("접근할 수 없는 팀플레이스입니다.");
//        }

```


논의하고싶은 내용 요약

1. 맵핑테이블을 도메인으로서 사용을 할 것인가 (중요)

2. 양방향 참조를 끊는다면 어떠한 구조를 만들 수 있을 것인가 (중요하지만 덜중요 아직은)

2023-07-20 05:56 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/teamplace/configuration/TeamPlaceInterceptor.java
> +        }
처음에는 필립처럼 hasXXX 메서드를 만들어서 하려고 했는데 데베를 한번만 조회하고 싶어서 맵필 테이블을 통해 조회하려고 한거긴 합니다. 근데 위 코드처럼 변경하는거 찬성합니다.

2023-07-20 23:35 UTC, sh111-coder requested changes
몇 부분 수정 요청드린 부분 있어서
반영 부탁드립니다! 😎

2023-07-20 23:35 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
> +            final Long wrongScheduleId = 7L;
7L로 하면 데이터가 추가됐을 때 테스트가 깨질 수도 있을 것 같아서
아예 있을 수 없는 -1L 같은 값을 넣는게 좋을 것 같습니다!

2023-07-21 08:39 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
>      public ResponseEntity<String> handleCustomForbiddenException(final RuntimeException exception) {
했습니다.

2023-07-21 08:44 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
> +    List<MemberTeamPlace> findMemberTeamPlacesByMemberEmail(@Param("email") Email email);
했습니다.

2023-07-21 08:48 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
> +            final Long wrongScheduleId = 7L;
변수이름으로 인해 오해를 드린 것 같습니다.
죄송합니다. 사실 스케줄을 변인 통제를 위해 있는 편이 나을 것 같아서 참가하지 않은 팀플레이스에 대한 테스트만 진행하고 싶었거든요
변수 이름 변경하겠습니다.
감사합니다.

2023-07-22 13:58 UTC, pilyang approved these changes
TeamPlace에 멤버 확인 역할 위임한부분이랑 다른 부분들 확인 완료했습니다!!!

2023-07-22 16:59 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/teamplace/configuration/TeamPlaceInterceptor.java
> +                .noneMatch(memberTeamPlace -> memberTeamPlace
member.hasXXX로 변경했습니다.

2023-07-22 16:59 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/teamplace/configuration/TeamPlaceInterceptor.java
> +        }
변경했습니다.

2023-07-22 23:52 UTC, sh111-coder approved these changes
수고하셨습니다!!! Approve 할게요!

2023-07-23 11:23 UTC, merged