[BE] 팀 캘린더 하루 일정 조회 구현
woowacourse-teams/2023-team-by-team pull request #156
Opened 2023-07-23 14:37 UTC by sh111-coder

# [FE|BE|ALL] PR 타이틀 
## 이슈번호
> #154 

## PR 내용

- 팀 캘린더 하루 일정 조회 구현

 
## 참고자료

## 의논할 거리

- 작업하면서 의논해볼 부분 생겼는데 코드단에 코멘트로 달겠습니다!

2023-07-23 14:44 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
>      public SchedulesWithTeamPlaceIdResponse findScheduleInPeriod(
### 의논1. 팀 캘린더 조회 & 통합 캘린더 조회 메소드 네이밍 분리?

작업하다보니 Service에서 팀 캘린더 조회 & 통합 캘린더 조회 메소드 네이밍이 
`findScheduleInPeriod`로 같은데 다르게 하는게 좋을듯??

2023-07-23 14:46 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/schedule/domain/CalendarPeriod.java
> +    }
### 정적 팩토리 메소드 네이밍 변경

* CalendarPeriod 생성 정팩메 네이밍 of -> createPeriod로 변경
  * 하루 Period 생성 정팩메 네이밍을 createDailyPeriod로 하기 위함
  * 메소드 오버로딩도 생각해봤는데 처음 봤을 때 파라미터로만 의미를 판단하는게 어려울 것 같아서 네이밍을 바꿨음!

2023-07-23 14:47 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/schedule/domain/ScheduleRepository.java
>              LocalDateTime firstDateTime,
* `findAllByTeamPlaceIdAndPeriod` -> `List<Long> teamPlaceIds` 받으니까 네이밍에 복수형 's' 들어가야 할듯

2023-07-24 06:29 UTC, SproutMJ requested changes
good

2023-07-24 06:29 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
> +        checkTeamPlaceExist(teamPlaceId);
인터셉터에서 검증하는데 왜 한 번더 검증하시는지 고견을 듣고 싶습니다.

2023-07-24 06:29 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
>      public SchedulesWithTeamPlaceIdResponse findScheduleInPeriod(
저도 분리하는게 좋다고 생각합니다.

2023-07-24 06:29 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/schedule/domain/CalendarPeriod.java
> +    }
정팩메의 장점 중 하나가 메서드에 네이밍을 할 수 있다는 것이죠.
 좋은 것 같습니다.

2023-07-24 06:29 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
> +            @DisplayName("잘못된 연도 형식일 경우")
종결어미가 빠져있네요.

2023-07-24 06:29 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
> +            @DisplayName("잘못된 월 형식일 경우")
종결어미가 빠져있네요.

2023-07-24 06:29 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
> +            @DisplayName("잘못된 일 형식일 경우")
종결어미가 빠져있네요.

2023-07-24 06:29 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/schedule/application/ScheduleServiceTest.java
> +            @DisplayName("잘못된 연도 형식일 경우")
종결어미가 빠져있네요.

2023-07-24 06:29 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/schedule/application/ScheduleServiceTest.java
> +            @DisplayName("잘못된 월 형식일 경우")
종결어미가 빠져있네요.

2023-07-24 06:29 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/schedule/application/ScheduleServiceTest.java
> +            @DisplayName("잘못된 일 형식일 경우")
종결어미가 빠져있네요.

2023-07-24 07:07 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
>      public SchedulesWithTeamPlaceIdResponse findScheduleInPeriod(
(의논1) 조회 대상에 차이가 있는 만큼 메서드 네이밍이 분리되는 것이 좋을 듯 합니다.

(의논2) 통합 캘린더, 팀 캘린더의 레이어를 구분(서비스 역시) 하는 게 좋다고 생각합니다

2023-07-24 07:14 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/schedule/domain/CalendarPeriod.java
> +    }
저도 of 보다는 의미가 드러나는 네이밍이 좋다고 생각합니다.

특히 캘린더의 경우 대상이 구분(팀 캘린더, 통합 캘린더)이 중요한 만큼, 정팩메 네이밍으로 해당 기능을 구분하는 것이 좋을 듯 합니다.

2023-07-24 13:32 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
>      public SchedulesWithTeamPlaceIdResponse findScheduleInPeriod(
## 의논1

해당 부분은 제가 작성하며는 의도적으로 함수 오버로딩으로 사용했습니다..!
이유는 의미(행위)에 대해서는 메서드명으로 `findScheduleInPeriod` 잘 표현이 되었다고 생각하고, 멤버의 스케쥴인지 팀플레이스의 스케쥴인지는 파라미터로 잘 표현이 되었다고 생각해서 입니다.
메서드 명 구분에 대해서는 고민을 해보고 싶지만, 아래 의논2의 내용에서 함께 다루기 위해서 의논1에관한건 이정도만 우선 작성하겠습니다.


## 의논2

스케쥴(일정)이라는 도메인을 관리한다는 입장에서 같은 서비스에서 있는것이 좋지 않을까 하여 컨트롤러 구분시에 구분하지 않았습니다.

하지만 후에 여러 기능들이 추가가 될 가능성을 염두해 둔다면 분리를 해보는 것도 나쁘지는 않을 것 같다고 생각합니다.
전 분리하는것이 더 좋다는 생각은 아니긴 하지만, 그렇다고 싫은것도 아니여서, 다수의 의견에 맞추어 분리하는것도 좋다고 생각합니다.

여기서 의논1에 대한 의견을 다시 말하자면, 서비스 클래스 명으로 이제 어떠한것이 팀플에이스용이고 어떠한 것이 개인사용자용인지가 명확히 나타낼 수 있다고 생각합니다.
그래서 클래스분리를 한다면 메서드명은 지금처럼 그대로 똑같이 가도 될 것 같습니다.

```java
teamPlaceScheduleController.findScheduleInPeriod(~~~);
myScheduleController.findScheduleInPeriod(~~~);
```

처럼 구분이 될 것 같습니다.

2023-07-24 13:33 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
> +        checkTeamPlaceExist(teamPlaceId);
해당 부분은 저도 굳이 다시 검증을 해야할까라는 의미에 동감합니다..!

2023-07-24 13:42 UTC, pilyang reviewed
해당 부분들에 커멘트 남겼습니다..!!

2023-07-24 13:50 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/schedule/domain/ScheduleRepository.java
>              LocalDateTime firstDateTime,
이부분도 함수 오버라이딩을 위해서 부러 이리함... teamPlaceId에 하나의 값만 들어온다면 해당 팀플레이스로, 컬랙션이 들어온다면 모든 컬랙션에 해당되는 것들을 반환하도록

최대한 의미와 행위가 같고, 파라미터만 다른 것들은 메서드명을 동일하게 가져가려고 함. 그래야지 나중에 해당 메서드 호출할때 어떤 파라미터들이 사용 가능한지를 한번에 보기 쉬워서

2023-07-24 23:31 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
> +        checkTeamPlaceExist(teamPlaceId);
저번에 필립 일정 조회 pr에서 의견 남겼었는데 아무런 코멘트 없었어서 그냥 진행했습니다!
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/95729738/28e32dc7-4468-4417-872d-8ebd4ed051eb)

2023-07-24 23:37 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
>      public SchedulesWithTeamPlaceIdResponse findScheduleInPeriod(
저는 작게 쪼개는 것이 관리할 때 더 쉬울 것 같아요!

물론 스케쥴 입장에서는 내 캘린더와 팀 캘린더가 같은 로직이겠지만 
유스케이스? 에 따라 분리하는 것이 좋다고 생각합니다!

Save, Update가 아닌 이러한 도메인느낌의 기준으로도 유스케이스라고 부르는지는 아직 잘 모르겠지만
내 캘린더 로직이랑 팀 캘린더 로직이 분리되면 더 관리하기가 쉬워질 것이라고 생각합니다!!

만약 분리한다면 필립 마지막 의견처럼 메소드명은 그대로 가도 될것 같아요!

리팩토링 시 의견 마지막으로 물어보고 리팩토링 하겠습니당

2023-07-24 23:45 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/schedule/domain/CalendarPeriod.java
> +    }
필립 의견 잘 들었습니다!!

저도 파라미터로 해당 메소드가 어떤 역할을 하는지 파악이 바로 되면 써도 된다고 생각합니다!

제가 of가 아닌 네이밍을 직접 준 이유는
제가 작업한 createDailyPeriod의 파라미터가 year, month, day를 받는데
of 메소드에서 해당 파라미터만 보고 하루 기간을 반환해주는 메소드라고 생각하기가 힘들 것 같았기 때문입니다!

이와 같은 이유로 기존 메소드도 변경했었습니다!

이 부분도 한번 의견 다 들어보고 리팩토링하겠습니다!

2023-07-24 23:47 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/schedule/domain/ScheduleRepository.java
>              LocalDateTime firstDateTime,
아하!
이 부분은 파라미터로 파악이 가능할 것 같아서 놔둬도 괜찮을 것 같네요!!

2023-07-24 23:48 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
> +            @DisplayName("잘못된 연도 형식일 경우")
위에 Nested 클래스에 이미 실패한다라는 의미가 있어서 중복같아서 뺐는데 넣는게 좋을까요?

2023-07-25 01:32 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
> +            @DisplayName("잘못된 연도 형식일 경우")
근데 이거 결국에는 테스트 메서드에서는 최종적으로 보여지는거는 통일하는 것이 좋지 않을까 싶은데 어떤가요?

2023-07-25 07:23 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/schedule/domain/CalendarPeriod.java
> +    }
충분한 논의를 거친 후, 
정팩메 메소드 네이밍은 기본적으로 `of`(파라미터 2개 이상) , `from` (파라미터 1개)로 정하고
추가적으로 비즈니스 로직이 들어가면 취향에 맞게 네이밍하는 것으로 컨벤션 정했습니다!

2023-07-25 07:24 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
>      public SchedulesWithTeamPlaceIdResponse findScheduleInPeriod(
충분한 논의를 거친 후,
내 캘린더, 팀 캘린더 서비스를 분리하는 것으로 결정헀고 메소드 네이밍은 서비스 네이밍에 따라 분리되므로
똑같은 네이밍으로 하기로 결정했습니다!

2023-07-25 08:31 UTC, SproutMJ approved these changes
good

2023-07-25 08:54 UTC, the9kim approved these changes
구현 기능은 하나였지만 다방면으로 변경 사항을 고민하고 반영하셨네요! 고생 많으셨습니다 👍

2023-07-25 12:14 UTC, pilyang approved these changes

2023-07-25 12:48 UTC, merged