[BE] jwt token 생성, 검증, email 추출 기능 구현
woowacourse-teams/2023-team-by-team pull request #159
Opened 2023-07-24 06:01 UTC by SproutMJ

## 이슈번호
#79

## PR 내용
jwt 토큰 생성, 검증, email 추출 기능 구현

## 참고자료

## 의논할 거리
jwt 시크릿 키 관리 방법(현재 테스트 전용 키 a32개임, 현재 노션 갱신 안됨)

2023-07-24 23:22 UTC, sh111-coder commented on backend/src/test/resources/application.yml
> +  expiration: 3600000
동의합니다~!

2023-07-24 23:28 UTC, sh111-coder reviewed
모르겠는 부분 코멘트 남겼는데 답변해주시면 approve하겠습니다!

2023-07-24 23:28 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/global/configuration/JwtTokenProvider.java
> +            throw new MemberException.UnSupportAuthenticationException("TODO: 토큰 검증 실패");
이 TODO 예외 메시지는 무슨 의미인가요??

2023-07-25 07:26 UTC, the9kim commented on backend/src/test/resources/application.yml
> +  expiration: 3600000
좋습니다!

2023-07-26 00:50 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/global/configuration/JwtTokenProvider.java
> +            throw new MemberException.UnSupportAuthenticationException("TODO: 토큰 검증 실패");
이거 사실 AuthException으로 빼야될 필요성을 느끼고 있어서 TODO로 일단 적어두긴 했습니다.

2023-07-26 00:51 UTC, SproutMJ commented on backend/src/test/resources/application.yml
> +  expiration: 3600000
good

2023-07-26 08:01 UTC, sh111-coder approved these changes
수고하셨습니다 ㅎㅎ

2023-07-27 00:55 UTC, pilyang approved these changes

2023-07-27 00:56 UTC, pilyang commented
approve 했습니다!! merge하기전에 말해주세여 같이 application-dev.yml작성해서 업로드 하는 작업 진행하면 될 것 같습니다.

머지하면서 빌드 배포가 동시에 되서 머지전에 application-dev.yml업데이트 필요해보입니다!!

2023-07-27 01:33 UTC, the9kim submitted a review, later dismissed
엔델 수고하셨습니다!

2023-07-27 04:30 UTC, pilyang reviewed
수정 완료되면 다시 말해주셔요

2023-07-27 04:31 UTC, pilyang requested changes
수정 완료되면 다시 말해주셔요

2023-07-27 07:36 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/global/configuration/JwtTokenProvider.java
> +            throw new MemberException.UnSupportAuthenticationException("TODO: 토큰 검증 실패");
적용중입니다.

2023-07-27 23:44 UTC, sh111-coder submitted a review, later dismissed
수고하셨슴다 ㅎㅎ

2023-07-28 02:36 UTC, pilyang submitted a review, later dismissed
Good

2023-07-28 02:38 UTC, the9kim submitted a review, later dismissed
JWT의 제왕 엔델 감사합니다.

2023-07-28 02:44 UTC, pilyang approved these changes

2023-07-28 02:45 UTC, the9kim approved these changes
훌륭합니다

2023-07-28 02:45 UTC, sh111-coder approved these changes
수고하셨습니다 ^^ conflict 해결도 good

2023-07-28 02:47 UTC, merged