Feat/fe/공지 스레드 컴포넌트 구현
woowacourse-teams/2023-team-by-team pull request #230
Opened 2023-07-27 13:56 UTC by wzrabbit

## 이슈번호
> #close #188

## PR 내용
**아직 완전히 구현되지 않았습니다.**  

본 PR에서는 공지 스레드 컴포넌트를 구현하고, 구현하기 위해 필요한 하위 컴포넌트들을 일부 구현하였다.

- 공지 스레드 컴포넌트 구현
  - 내부에 들어가는 내용이 많아 `300px` 을 넘길 경우 **펼치기/접기** 버튼이 추가로 랜더링되며, 사용자는 이 버튼을 눌러 긴 내용을 펼쳐 볼지 그렇지 않을지 결정할 수 있다.
  - 날짜의 경우 아직 미구현 상태이다 (의논할 사항 참고)

- 확장 버튼 컴포넌트 구현

- 카테고리 컴포넌트 구현
  - 카테고리 컴포넌트의 경우 공지 태그만 디자인된 재사용이 불가능한 미구현 컴포넌트이다 (의논할 사항 참고)

## 참고자료
- 공지 스레드 컴포넌트
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/bfde130d-1bcb-46eb-80d1-e6f20249260d)
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/9b63e967-3436-4993-bc9a-ea166e4cad08)

- 확장 버튼 컴포넌트
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/59602c87-b697-49d6-abdd-1b033c521f4b)
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/b2b378c4-5cd9-4b19-bc30-8e711c5a4a26)

- 카테고리 컴포넌트 (재사용이 불가능한 임시 컴포넌트)
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/9425da11-2d9d-43c2-a6e9-8f75196b0bf1)

## 의논할 사항
1. 날짜의 경우 props로 어떠한 타입의 정보를 넘겨줘야 할지?
  - `Date` 객체?
  - 문자열 형태의 데이터? (ex: `startDateTime`)
2. 앞서 관련 컴포넌트들을 구현했던 루루의 디자인과 많이 다른데 어떻게 통일할 지?
3. 폴더 구조를 어떻게 바꾸면 좋을 지? 현재 폴더 구조는 구현한 컴포넌트들이 이 컴포넌트에서만 사용될 것이라고 가정하고 구조를 짰지만, 일반 스레드 컴포넌트와 공통정이 많은 컴포넌트인만큼 공유하게 되는 하위 컴포넌트들이 있을 것 같음. 현재 구조는 아래와 같음:
```
📦NoticeThread
 ┣ 📂ExpandButton
 ┃ ┣ 📜ExpandButton.stories.tsx
 ┃ ┣ 📜ExpandButton.styled.ts
 ┃ ┗ 📜ExpandButton.tsx
 ┣ 📂Tag
 ┃ ┣ 📜Tag.stories.tsx
 ┃ ┣ 📜Tag.styled.ts
 ┃ ┗ 📜Tag.tsx
 ┣ 📜NoticeThread.stories.tsx
 ┣ 📜NoticeThread.styled.ts
 ┗ 📜NoticeThread.tsx
```
4. 태그 컴포넌트의 경우 어떤 태그인지를 props로 어떻게 줄지? 
  - `Button` 공용 컴포넌트의 `variant` 처럼 미리 몇 개의 형식을 정해놓고 props에서 내려줄 수 있도록 구현하는 것이 좋을까?
  - 아니면, 직접 아이콘과 css를 props로 받아 랜더링하는 것이 좋을까?

코드가 개스레기입니다 양해해 주시면 감사하겠읍니다...

2023-07-28 01:17 UTC, wzrabbit commented on frontend/src/components/NoticeThread/NoticeThread.tsx
> +            <ClockIcon width="24px" height="24px" />
TODO:
- [ ] 시계 아이콘을 작성일자에서 제거
- [ ] 작대기 (`|`) 추가

2023-07-28 05:21 UTC, suyoungj requested changes
👍

2023-07-28 05:21 UTC, suyoungj commented on frontend/src/components/NoticeThread/NoticeThread.styled.ts
> +export const Content = styled.p``;
지워도 될듯?

2023-07-28 05:21 UTC, suyoungj commented on frontend/webpack.config.js
> +        use: ['file-loader'],
file-loader를 사용할 필요는 없을거 같아

https://webpack.kr/guides/asset-modules/

2023-07-28 05:39 UTC, hafnium1923 reviewed
구우우웃

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/assets/svg/megaphone.svg
width랑 height는 여기에서 정하면 굳이 동적으로 스타일링 할 필요 없지 않나? 
똑같이 흰색 메가폰 SVG 사용하면 될 것 같은데

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/ExpandButton/ExpandButton.tsx
나중에 더보기를 스레드에도 적용하게 된다면 그때 common으로 이동시켜도 될듯!

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/ExpandButton/ExpandButton.stories.tsx
> +  title: 'ExpandButton',
지금처럼 파일 구조 가져가면 Feed 하위로 어때? common으로 이동할거면 Common/ExpandButton 도 좋고

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/ExpandButton/ExpandButton.tsx
> +        <S.Container>
접기 펼치기 모두 Container 을 사용하고 있으니
```
<S.Container>
 {isExpanded ? () : ( )}
</S.Container>
```
이렇게 해도 될 것 같아!

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/ExpandButton/ExpandButton.styled.ts
> +export const expandButton = css`
common으로 이동하게 되면 얘는 이름을 바꾸면 좋을 듯!

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/NoticeThread.stories.tsx
> +  title: 'NoticeThread',
얘두 Feed 하위!

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/NoticeThread.styled.ts
> +  padding: 25px;
짝수로 통일하면 좋을듯!

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/NoticeThread.styled.ts
> +  padding-bottom: ${({ isExpanded }) => (isExpanded ? '90px' : '25px')};
얘두~

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/NoticeThread.styled.ts
> +
여기서부터 아래도 홀수인거 짝수로 바꾸는게 좋아보여!

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/NoticeThread.tsx
> +  const { author, profileImageSrc, children } = props;
<img width="356" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/50d2d15c-9976-440b-8886-4eb720582feb">
모아보기 페이지 사이즈도 하나 만들면 좋을 것 같아! 지금은 이렇게 가리게 되네ㅠㅠ 모아보기 페이지에서는 태그가 확성기 아이콘만 보여주는게 어때?

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/NoticeThread.tsx
> +  const { author, profileImageSrc, children } = props;
그리고 아마 작성자 정보랑 작성시간은 모아보기에서 안보이기로 했던걸로 기억하는데 어떻게 생각해?

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/NoticeThread.tsx
> +const NoticeThread = (props: PropsWithChildren<NoticeThreadProps>) => {
글을 children으로 받으면 어떤게 좋을까? 나는 어차피 이걸 렌더링 하는 곳에서 받아올거라 생각해서 content또한 prop으로 받았거든

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/Tag/Tag.tsx
> +const Tag = (props: TagProps) => {
Tag라고 하니까 되게 범용적인 것 처럼 보이는데 실제로는 공지사항 하나로만 이용되고 있어! 헷갈리지 않게 다른 네이밍을 하는 건 어때?

2023-07-28 05:39 UTC, hafnium1923 commented on frontend/src/hooks/thread/useThreadHeight.tsx
> +const DEFAULT_MAX_THREAD_HEIGHT = 300;
상수 파일 빼는거 어때? 나는 상수는 상수끼리 관리하는걸 좋아하는 편이라서ㅋㅋ 나중에 수정하면 맨날 찾아다녀야 하더라구

2023-07-28 07:28 UTC, wzrabbit commented on frontend/src/hooks/thread/useThreadHeight.tsx
> +const DEFAULT_MAX_THREAD_HEIGHT = 300;
그래, 얘는 공지 스레드 뿐만 아니라 다른 종류의 스레드에서 쓰일 확률이 높아보이니, 따로 빼는 게 좋겠다

2023-07-28 07:29 UTC, wzrabbit commented on frontend/src/components/NoticeThread/NoticeThread.tsx
> +const NoticeThread = (props: PropsWithChildren<NoticeThreadProps>) => {
아... 이건 내가 실수한 것 같다
`children` 으로 바꿔놓을게

2023-07-28 13:05 UTC, wzrabbit commented on frontend/src/assets/svg/megaphone.svg
코멘트의 요지가 해당 `svg` 파일에 직접 스타일을 넣고 그대로 사용하면 되는데 왜 굳이 import 한 후에 별도의 스타일을 적용하는지 이유를 묻는 거야?

이렇게까지 하면서 스타일을 적용해 준 이유는 해당 `svg` 이미지가 기본적으로 크기가 어느 정도일지, 색상은 어떨지 등의 여러 속성에 있어서 개발자가 기본 속성을 예측하기 어려울 거라고 생각하고 있어서야.

`<Button>`, `<Text>` 과 같은 컴포넌트들은 기본값들을 비교적 예측하기 쉽기에 일부 속성을 생략할 수 있었지만, 일반 `svg` 이미지의 경우는 그렇지 않다고 생각해. 물론 지금 구현하는 것에 한해서는 아예 기본 `svg` 이미지를 흰색으로 칠하고, 크기를 `???px` 로 정할 수 있겠지만, 이후 다양한 스타일의 이미지를 사용하게 된다면 어떻게 될까?

개발자가 봤을 때 기본 스타일을 `svg` 파일에서 설정해 주고
```tsx
<MyIcon />
```
와 같이 아이콘 컴포넌트만 넣어두면, 이 컴포넌트가 무슨 스타일인지 알기 위해 가독성 떨어지는 `svg` 파일을 열어서 봐야할 것 같아. 특히 흰색으로 칠해두면 아이콘이 기본적으로 흰색일 거라는 것을 예측하기는 기본색인 검은색보다도 더 어려울 것 같고. 아이콘들의 경우 다른 스타일로 이후에 사용될 확률이 높다고 생각하는데, 이렇게 하면 기본적으로 색상을 흰색으로 한 것의 메리트도 떨어질 것 같아보여.

그래서 `svg` 파일에서 기본적으로 어떤 스타일이 적용되었든, 나는 가져오는 `svg` 파일마다 항상 모든 스타일들을 일일이 적용하려고 하는 편이야. 적어도 `svg` 이미지들을 대표할 수 있는 공용 컴포넌트가 없는 한.

이제 루루의 생각도 적어 줘!

2023-07-28 13:38 UTC, wzrabbit commented on frontend/src/components/NoticeThread/NoticeThread.styled.ts
> +export const Content = styled.p``;
공용 컴포넌트인 `Text` 를 사용할 수 있으니까, 지워도 무방하겠다. 그 대신 유스한테 질문 하나만 할게 -
오로지 "시멘틱" 을 이유로 사용하는 스타일 컴포넌트에 대해서는 어떻게 생각해?

2023-07-28 13:40 UTC, wzrabbit commented on frontend/src/components/NoticeThread/Tag/Tag.tsx
> +const Tag = (props: TagProps) => {
스레드 내에서 한정적으로 사용되면 `<ThreadTag>` 정도면 되겠다!

2023-07-29 08:23 UTC, wzrabbit commented on frontend/src/components/NoticeThread/ExpandButton/ExpandButton.tsx
> +        <S.Container>
```tsx
<S.Container>
  {isExpanded ? (
    <>
      <Text weight="bold" size="lg">
        접기
      </Text>
      <ArrowExpandLessIcon />
    </>
  ) : (
    <>
      <Text weight="bold" size="lg">
        펼치기
      </Text>
      <ArrowExpandMoreIcon />
    </>
  )}
</S.Container>
```

2023-07-29 08:26 UTC, wzrabbit commented on frontend/src/components/NoticeThread/NoticeThread.tsx
> +  const { author, profileImageSrc, children } = props;
모아보기는 당시 고려를 안 했었는데, 루루가 이전에 `size` property 줘서 모아보기 페이지에서의 스레드와 그렇지 않은 상황에서의 스레드를 구분한 것처럼 구현해 볼게

2023-07-29 09:42 UTC, wzrabbit commented on frontend/src/components/NoticeThread/NoticeThread.styled.ts
> +export const Content = styled.p``;
생각해보니 `Text` 컴포넌트를 사용하는 게 적합해 보여서 `Text` 공용 컴포넌트를 사용하는 것으로 교체했어.
단 문제가 생겼는데, `Text` 공용 컴포넌트는 `ref` 를 지원하지 않아서 결국 `ref` 를 적용하기 위해 `S.ContentWrapper` 를 사용해야 했어.
결과적으로 각 컴포넌트을 사용해야 하는 이유는 보다 뚜렷해졌지만, 구조는 더 복잡해진 것 같아.
새로운 구조에 대해서는 어떻게 생각하는 지 유스의 생각을 말해주면 좋을듯!

```ts
// NoticeThread.styled.ts
export const ContentWrapper = styled.div``;
```

```
// NoticeThread.tsx
<S.ContentWrapper ref={contentRef}>
  <Text>{children}</Text>
</S.ContentWrapper>
```

2023-07-29 09:42 UTC, wzrabbit commented on frontend/src/components/NoticeThread/NoticeThread.styled.ts
> +export const Content = styled.p``;
그리고, 이건 다른 질문인데 -  `S.Content` 와 같이 아무 스타일을 가지지 않는 스타일 컴포넌트들을 오직 시멘틱 요소로 사용하는 것에 대해서는 어떻게 생각해?

2023-07-29 18:17 UTC, wzrabbit commented on frontend/src/components/NoticeThread/ExpandButton/ExpandButton.stories.tsx
> +  title: 'ExpandButton',
`ExpandButton`, `Tag` 두 컴포넌트 모두 스레드 관련 컴포넌트 내에서 한정적으로 쓰일 것으로 보이니, `common` 에 들어갈 정도로 범용적인 컴포넌트는 아닌 것 같아 보여. 아마 이미 있는 `Feed` 분류에 컴포넌트들을 추가해 볼 것 같아

2023-07-30 08:16 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/NoticeThread.styled.ts
> +export const Content = styled.p``;
나는 아무 스타일이 없다면 스타일 컴포넌트로 사용하는 것에 대해서 약간 회의적이야. 요술토끼 말처럼 생각할 수 있겠지만, 나라면 어떤 스타일에 대해서 문제가 생겼을 때 해당 스타일 컴포넌트가 시멘틱 요소로 사용되고 있는지, 스타일이 있는건지 모르니까 하나하나 확인하면서 어디서 문제가 생겼는지 볼 것 같거든. 애초부터 시멘틱 태그로 사용되었다면 다른 곳에서 문제를 찾을 수 있는 것도 하나하나 스타일일 확인 해야하니 시간낭비가 되지않을까?

또한 시멘틱 태그를 사용한다고 가독성이 떨어진다고 생각하지 않아. 오히려 요소들을 묶어야지만 적용되는 스타일이 있구나 하고 코드 이해에 도움을 줄 것 같아

2023-07-30 08:21 UTC, hafnium1923 commented on frontend/src/assets/svg/megaphone.svg
재활용을 생각해서 인라인으로 스타일을 적은 요토의 생각 충분히 이해해! 하지만 적어도 지금 우리 서비스에서는 관리하는 SVG가 많지도 않고, 해당 SVG 가 어떤 아이콘인지 네이밍을 통해 유추할 수 있다고 생각하기 때문에 개발자가 svg 파일을 봐야될 일은 없을 것이라고 생각해.  또 현재 같은 SVG가 여러곳에서 서로 다른 크기나 색상으로 사용되고 있지 않기 때문에 고정해서 사용해도 된다고 생각하구! 

요토가 아이콘 컴포넌트만 넣어서 개발자가 확인하기 힘들다라고 한 부분은 스토리북을 통해서 해결할 수 있는 부분이기도 하지! 그래서 재사용을 위해 인라인 스타일을 적용해야만 한다 는 아직까지 이유가 부족한 것 같다고 생각해. 언제일지 모르는 재사용보다는 우리 코드의 일관성이 지금 시점에서는 중요하지 않을까? 

어떻게 생각해?

2023-07-30 08:22 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/ExpandButton/ExpandButton.stories.tsx
> +  title: 'ExpandButton',
좋아! 후에 확장하게 된다면 그때 옮기자ㅎㅎ

2023-07-30 08:23 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/ExpandButton/ExpandButton.tsx
> +        <S.Container>
난 이걸 더 선호하는 편이긴 해ㅎㅎ 좋아!

2023-07-30 08:24 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/NoticeThread.tsx
> +const NoticeThread = (props: PropsWithChildren<NoticeThreadProps>) => {
오잉? 나는 children 말고 props으로 받자는 의견이긴 했는데! 저건 질문이였어ㅋㅋㅋ 요토가 한 것 처럼 children으로 받으면 어떤 부분이 좋은지 정말 궁금해서 물어본 것!

2023-07-30 08:25 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/Tag/Tag.tsx
> +const Tag = (props: TagProps) => {
웅 아니면 <NoticeTag> 도 좋을 것 같아!

2023-07-30 12:50 UTC, wzrabbit commented on frontend/src/components/NoticeThread/NoticeThread.tsx
> +const NoticeThread = (props: PropsWithChildren<NoticeThreadProps>) => {
어떤 점이 더 좋다기 보다는, 별도의 `props` 로 주는 방식과 `children` 으로 주는 방식은 가독성 차이이며 취향 차이라고 생각하고 있어.

`children` 방식을 조금 더 좋아하는 이유는 HTML에서의  `<p>`, `<h1>`  등의 글을 담을 수 있는 태그의 경우 `children` 위치에 핵심적인 내용을 적기에 좀 더 익숙하다고 생각해서야.

공지 스레드도 결국 글 상자의 일종이기에, `children` 을 사용했을 때 `children` 에 "해당 컴포넌트의 핵심 내용" 이 오게 될 것이라는 것을 충분히 예측할 수 있어 보여서 적용이 가능해 보이고, 그 외의 정보인 작성자 정보, 글을 작성한 시간 등의 정보는 부가 정보라 생각해 `props` 의 속성들로 주면 좋을 거라고 생각했어.

명확하게 `children` 을 사용하기 유리한 상황이라고 하면 내부에 들어가는 내용들이 명확하게 정해지지 않은 경우라고 생각해. 예를 들면 `<Modal>` 의 경우 내부에 들어가는 내용이 단순 글인지, 여러 컴포넌트들의 조합인지 명확하게 정의하기가 힘들어 보여.
하지만 지금의 공지 스레드 컴포넌트는 들어가는 내용이 예측하기 힘든 경우가 아니니 두 방법 모두 유효한 방식이라고 생각해.

다만 내부에 들어가는 내용이 명확한 공용 컴포넌트인 `<Text>`, `<Button>` 모두 `children` 방식을 사용하고 있으니, 일관성을 지키자면 `children` 으로 내용을 넣는 것은 어떨까? 

```tsx
<Text>여기에 내용을 입력하세요</Text>
<Button>삭제하기</Button>
```

2023-07-30 12:52 UTC, wzrabbit commented on frontend/src/components/NoticeThread/Tag/Tag.tsx
> +const Tag = (props: TagProps) => {
그래, 지금은 용도가 상당히 한정적이니까, `<NoticeTag>` 으로 이름을 짓고, 이후 기능이 확장되어 기존 이름으로는 컴포넌트의 기능을 설명하기 힘들다고 판단되면 그 때 생각해 보자.

2023-07-30 13:08 UTC, hafnium1923 commented on frontend/src/components/NoticeThread/NoticeThread.tsx
> +const NoticeThread = (props: PropsWithChildren<NoticeThreadProps>) => {
Text와 Button은 공용 컴포넌트라 children을 사용해서 재사용성을 높이는게 좋아보였는데 이건 공지만을 위한 컴포넌트이기도 하고 다른 필드(공지 작성자, 공지 작성 시간 등등)는 다 props로 받으면서 content만 children으로 받는게 어색해 보이는 것 같아가지구..
나는 어느 쪽도 이유가 타당하고 일관성있다면 괜찮을 것 같아. 그래서 과반수쪽으로 갈게 난! 
아 그리고 만약 요토 말대로 하게된다면 스레드 컴포넌트도 일관성있게 바꾸는 게 좋을 것 같아.

2023-07-30 13:34 UTC, wzrabbit commented on frontend/src/assets/svg/megaphone.svg
svg 파일들도 결국 이미지 파일들과 비슷하게 생각해 보면 루루의 생각 역시 일리 있어보인다. 이미지들도 스타일들이 제각각이지만 사용하는 입장에서 무리 없이 사용하고 있고, 코멘트를 남긴 부분에 해당하는 컴포넌트는 현재로써 확실히 하나의 스타일만 사용할 것이 자명하네. 
이번에 넣게 되는 svg 파일들은 svg 파일에서 직접 스타일을 넣어 볼게.

이외에도, 내 생각을 코멘트로 적어 놓을게.

> 해당 SVG 가 어떤 아이콘인지 네이밍을 통해 유추할 수 있다고 생각하기 때문에  

해당 svg가 어떤 아이콘인지는 이미 컴포넌트 이름으로 충분히 유추된다는 것에 나도 동감해. 내가 이야기한 것은 "컴포넌트의 스타일" 이 유추되지 않을 수도 있다는 뜻이었어.

> 스토리북을 통해서 해결할 수 있는 부분  

이 부분은 이해가 잘 가지 않는 것 같아.
스토리북을 켜는 것은 결국 코드의 실행 결과를 보는 것과 같은 것으로 보이는데, 코드를 직접 실행시켜 보지 않고도 스타일 파일과 컴포넌트 파일 등을 먼저 보는 것으로 실행 결과를 예측할 수 있으면 더 좋지 않을까? 지금껏 우리가 클린 코드를 짜려고 토론을 반복하는 것도 읽기 쉽고 결과를 예측하기 쉬운 코드를 짜려 했던 거잖아.

> 언제일지 모르는 재사용보다는 우리 코드의 일관성이 지금 시점에서는 중요하지 않을까?  

재사용이라면 루루의 주장이 더 일리 있는 것 같아 보인다. 그렇네, 가까운 미래에 여러 스타일의 svg 파일을 사용할 것으로 예측되지 않는 컴포넌트인데 하나로 고정하면 되지 왜 재사용을 그렇게 그려했을까 🤣 이번 코멘트에 답변 적으면서 내가 좀 고집을 피웠다는 생각이 들기도 한다

일관성에 대해서는 스타일을 적용하는 방식과 svg 파일에 스타일을 적용하는 두 방식 모두 일관성을 지킨다고 생각해. 두 방법 모두 마치 프론트엔드 코드 컨벤션을 짠 것처럼 딱 떨어지지 않아?

### svg에서 먼저 import한 후, 스타일을 주는 방식
1. 스타일이 적용되지 않은 svg 아이콘 컴포넌트들은 기본적으로 검은 색상의 크기가 정해진 컴포넌트임을 알 수 있다.
2. 부가적으로 적용해야 하는 스타일이 있는 경우 별도의 스타일을 정의(`Wrapper` 등)하여 사용하며, 그렇지 않은 경우 스타일을 적용하지 않는다.

### svg 파일 자체에서 먼저 스타일을 주고, import해서 그대로 사용하는 방식
1. 해당 svg 파일에서 여러 스타일을 사용할 일이 없을 경우에는 svg 파일에서 스타일을 직접 지정하여 사용한다.
2. 그렇지 않을 경우, svg에 스타일을 지정하지 않고 import로 가져온 후 스타일을 적용한다.

더 하고 싶은 코멘트가 있다면 이 아래에 언제든지 적어 줘!

2023-07-30 14:03 UTC, hafnium1923 commented on frontend/src/assets/svg/megaphone.svg
> 코드를 직접 실행시켜 보지 않고도 스타일 파일과 컴포넌트 파일 등을 먼저 보는 것으로 실행 결과를 예측할 수 있으면 더 좋지 않을까?

그런이야기였구나! 확실히 코드상으로 예측하면 좋은 점이 많긴하지. 요토랑 열심히 토론하니까 되게 재밌는 것 같아! 왜 SVG에 직접 스타일을 주지? 하고 궁금증이 있었는데 덕분에 해결한 것 같다. 역시 여러 사람의 의견을 듣는건 여러 방안이 보여서 좋은 것 같아.
요토의 의견을 듣고 보니 가능하다면 동적으로 스타일링을 주는 것도 굉장히 일리있어보여. 어느쪽이든 이제 나는 이해가 가니 요토가 원하는 대로 해도 좋아요! 

건전한 토론 아주아주 재밌었습니다👍👍👍

2023-07-31 05:40 UTC, closed without merging