[BE] 공지 등록 기능 구현
woowacourse-teams/2023-team-by-team pull request #238
Opened 2023-07-29 03:22 UTC by the9kim

## 이슈번호
> #216 

## PR 내용
- 공지 등록 기능 구현
- 공지 관련 테스트용 빌더 및 fixtures 추가
- 공지 관련 테스트(인수, 서비스, 레포지토리, 도메인) 구현

## 참고자료

## 의논할 거리

2023-07-29 05:16 UTC, pilyang requested changes
전반적으로 깔끔하게 기능구현 잘 해주신것 같아요!!

컨벤션이나 개행 관련 부분들만 좀 수정해주시면 좋을 것 같아요!👍👍

2023-07-29 05:16 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/dto/MemberEmailDto.java
> +
공백이 왜 추가되어있을까요...ㅎㅎㅋㅋㅋㅋㅋㅋㅋㅋ

2023-07-29 05:16 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +    public Long register(final NoticeRegisterRequest noticeRegisterRequest, final Long teamPlaceId, final MemberEmailDto memberEmailDto) {
메서드 파라미터가 길어지면 final을 기준으로 줄바꿈을 해줘도 좋을 것 같아요.

```java
        public Long rgister(
                final NoticeREgisterRequest noticeRegisterREquest,
                final Long teamPlaceId,
                final MemberEmailDto memberEmailDto
        ){
        ...
        }
```

처럼요

2023-07-29 05:16 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +        final IdOnly memberId = memberRepository.findIdByEmail(new Email(memberEmailDto.email()))
오 IdOnly사용해서 필요한 정보만 가져온기!! 좋아요!!!

2023-07-29 08:25 UTC, SproutMJ requested changes
고생하셨습니다.

2023-07-29 08:25 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +
여기에 빈줄이 있네요

2023-07-29 08:25 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/notice/presentation/NoticeController.java
> +
필립은 ) {도 개행하는 것 같아요
```suggestion
    public ResponseEntity<Void> register(
            @RequestBody @Valid final NoticeRegisterRequest reqeust,
            @PathVariable final Long teamPlaceId,
            @AuthPrincipal final MemberEmailDto memberEmailDto
    ) {

```
근데 이게 안되어 있는 부분이 다른데도 많네요(저포함)

2023-07-29 08:25 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/NoticeAcceptanceFixtures.java
> +            ) {
이부분도 마찬가지긴 한데 다들 통합해야될 것 같아요

2023-07-29 08:25 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/NoticeAcceptanceFixtures.java
> +
빈줄입니다.

2023-07-30 01:24 UTC, sh111-coder requested changes
수고하셨습니다!!!

첫 구현이라 힘들었을 텐데 중요한 컨벤션들을 다 지켜주신 것 같아서 짱짱이었습니다!

테스트 코드 중에 테스트 케이스 추가할 부분만 보완해주시면 Approve 하겠습니다!!

2023-07-30 01:24 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
> +        void setup() {
오 이렇게 BeforeEach로 묶으니까 테스트가 깔끔해지네요!! 굿굿

2023-07-30 01:24 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
> +    class RegisterNotice {
팀 플레이스 ID가 존재하지 않을 때 실패하는 테스트 케이스가 빠진 것 같아요!!

2023-07-30 01:24 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
> +    class RegisterNotice {
'공지 등록 시 멤버 이메일로 조회한 멤버가 없으면 예외가 발생한다' 테스트 케이스가 없는 것 같아요!

이 부분은 위임 테스트(중복 테스트)를 하냐 마냐가 의견이 있을 것 같아요.

1. 위임 테스트 작성 X
 1-1. MemberRepository 테스트에서 findIdByEmail 메소드에 대한 테스트를 만들고 
       이후 Service에서 사용하는 부분은 중복 테스트로 봐서 생략하기
  
 1-2. MemberRepository는 테스트하지 않고 서비스에서 사용할 때마다 테스트하기


2. 위임 테스트 작성 O
MemberRepository 테스트에서 findIdByEmail 메소드에 대한 테스트를 만들고
서비스에서도 해당 테스트 중복으로 작성하기

저는 테스트 작성도 리소스가 많이 든다고 생각하기 때문에 MemberRepository에서 한번 작성하는 것이 좋다고 생각합니다!

2023-07-30 01:45 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/notice/domain/NoticeRepository.java
> +    List<Notice> findByTeamPlaceId(Long teamPlaceId);
이 부분 여러 요소 가져오니까 메소드 네이밍을
`findByTeamPlaceId` -> `findAllByTeamPlaceId`로 고쳐주세요!

2023-07-31 09:58 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/notice/domain/NoticeRepository.java
> +    List<Notice> findByTeamPlaceId(Long teamPlaceId);
그렇군요! 

놓친 부분을 짚어주셔서 감사합니다!!

2023-07-31 10:15 UTC, the9kim commented on backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
> +    class RegisterNotice {
테스트가 없다는 사실을 알려주는 것에서 지치지 않고 훌륭한 가이드라인을 주셨군요👍

테스트 작성에 리소스가 많이 든다는 의견에는 적극 동의합니다.

기존에 팀플레이스 id가 존재하지 않을 경우 예외 처리에 관란 테스트가 service 레이이어에 있었기 때문에,

'존재하지 않는 멤버를 이용하여 공지 등록'에 관한 예외 처리 역시 서비스 관련 테스트에 추가해봤습니다!

2023-07-31 10:38 UTC, the9kim commented on backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
> +    class RegisterNotice {
1. 애초에 DB에 존재하지 않는 TeamPlace Id로 요청이 들어올 경우.
2. DB에는 존재하는 Teamplace Id이지만, 요청한 Memeber가 소속된 Teamplace가 아닐 경우.

두 가지 경우를 구분해서 테스트하지 못했군요!

말씀하신 내용 반영해서 테스트 추가해봤습니다!

2023-07-31 11:25 UTC, sh111-coder approved these changes
코멘트 드린 부분 반영해주셔서 Approve 하겠습니다!! ✌🏻

2023-07-31 11:28 UTC, pilyang approved these changes

2023-07-31 11:55 UTC, SproutMJ approved these changes
good

2023-07-31 12:34 UTC, merged