[PR] Member, MemberTeamPlace, TeamPlace 구조 및 연관관계 리팩터링
woowacourse-teams/2023-team-by-team pull request #239
Opened 2023-07-29 08:38 UTC by pilyang

## 이슈번호
> close #237 

## PR 내용
- MemberTeamPlace 필드 추가
  - DisplayMemberName
  - DisplayTeamPlaceName

- MemberTeamPlace와 TeamPlace간 의존관계 단방향으로 변경
  - MemberTeamPlace -> TeamPlace (n:1)

- 사용자가 요청을 보낸 팀플레이스 소속인지 확인하는 로직 변경
  - 기존 : 팀플레이스 엔티티 사용
  - 변경내용 : 멤버도메인 사용
  - 해당 변경으로 없는 팀플레이스로의 요청시 예외 메시지 및 코드 변경 - 자세한 내용은 의논할 거리 확인

- TeamPlaceInterceptor의 이름을 더 직관적으로 변경
  - 변경된 이름 : TeamPlaceParticipationInterceptor

- 멤버팀플레이스에서 사용자의 디스플레이네임과 아이디만 조회하는 repository method 구현
  - @SproutMJ 이 작업중인 피드조회시에 확인해보고 필요한거 사용하면 될듯

## 참고자료

## 의논할 거리

기존에 멤버가 팀플레이스 소속인지 확인하던 방식
- 팀플레이스 엔티티에서 확인
수정후 사용할 방식
- 멤버 엔티티에서 확인
  - 이유 : 팀플레이스 도메인에서 멤버팀플레이스 안가지고있음

생긴문제
- 없는 팀플레이스로 요청시
  - 기존 : 없는 팀플레이스에 대한 요청이라는 오류 반환
  - 변경후 : 접근할 수 없는 팀플레이스라는 오류 반환

해결방안
1. 소속확인 전에 팀플레이스 아이디로 있는지 확인한다.
  - 장점 : 기존의 예외발생대로 처리를 할 수 있다.
  - 단점 : 리팩터링을 진행함으로 팀플레이스에 대한 쿼리를 안날려도 되도록 조회 요청 횟수가 줄게되었는데, 다시 팀플레이스로 조회요청이 들어가야한다.

2. 해당 오류를 접근할 수 있는 팀플레이스 오류 반환하는것으로 한다. (바뀐 오류대로 한다)
  - 장점 : 팀플레이스 db에 접근을 하지 않아도 된다.
  - 단점 : 기존 테스트들에 대한 수정이 (약간?) 들어가야한다.
    - 혹시라도 컨플릭트가 난다면 유감인 상황이 발생하게 된다..^^;

내생각
- 2번 방향으로 한다. (해당 케이스에서 발생하는 예외를 수정하는 방향으로)

이유
- team_place 엔티티에 대한 접근을 줄여 db연결을 줄이고, 해당 트랜색션에서 물리는 엔티티를 줄일 수 있다.
- 사용자가 속하지 않은 팀이니까 해당 팀의 존재 유무에 대한 정보를 알려주지 않아도 될 것 같다.
  - 오히려 사용자가 팀플레이스 아이디를 조작해 마구잡이로 보내서 존재하는 팀플레이스인지 아닌지에 대한 확인을 못하게 할 수 있다.

이러한 이유로 해당 테스트케이들에 대한 예외 검증을 바꾸었습니다.

2023-07-29 12:43 UTC, SproutMJ commented
[PR]은 뭐죠(아직 코드리뷰 아님)

2023-07-30 01:50 UTC, sh111-coder approved these changes
수고하셨습니다!! 👍🏻👍🏻

넘 깔끔하게 해주셔서 Approve 하곘습니다!!

2023-07-30 01:50 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
> +    List<MemberIdAndDisplayNameOnly> findAllByTeamPlaceId(Long teamPlaceId);
이거 보고 생각났는데 지금 develop 코드에 List로 여러 조회 값 받을 때 findAll 말고 find로 받는 것도 있는데 findAll로 리팩토링하면 좋을 것 같습니당

2023-07-30 05:44 UTC, SproutMJ requested changes
흠잡을 수 없군요.
빈줄만 잡습니다.
감사합니다.

2023-07-30 05:44 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/member/domain/vo/DisplayMemberNameTest.java
> +
빈줄 발견.

2023-07-30 05:44 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/member/domain/vo/DisplayTeamPlaceNameTest.java
> +
빈줄 발견.

2023-07-30 05:44 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepositoryTest.java
> +
빈줄 발견.

2023-07-30 05:44 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceTest.java
> +
빈줄 발견.

2023-07-30 05:44 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceTest.java
> +
빈줄 발견.

2023-07-30 05:48 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/member/domain/vo/DisplayMemberNameTest.java
> +
빈줄잡기 귀신이시네요
다 반영했습니다

2023-07-31 01:18 UTC, sh111-coder approved these changes
Approve가 풀렸네요 ㅜㅜ

2023-07-31 03:39 UTC, SproutMJ approved these changes
good

2023-07-31 03:46 UTC, merged