[BE] 팀 피드 일정 알림 기능 구현
woowacourse-teams/2023-team-by-team pull request #240
Opened 2023-07-29 19:09 UTC by sh111-coder

# [FE|BE|ALL] PR 타이틀 
## 이슈번호
> #215 

## PR 내용

- 일정 Event 추상화 구현
- Event 발행 기능 구현
- Event 실행 (일정 알림) 기능 구현

## 참고자료

기본적인 스프링 이벤트 개념들 설명해놓은 블로그 첨부합니다!

[스프링 이벤트 적용기 테코블](https://tecoble.techcourse.co.kr/post/2022-11-14-spring-event/)
[스프링 이벤트 - 망나니개발자](https://mangkyu.tistory.com/292)

## 의논할 거리

## 1. CQRS
* TeamCalendarService에 ApplicationEventPublisher 객체를 주입받는데, 이벤트가 R을 제외한 CUD 시에 생성되므로 R 메소드는 해당 객체를 사용하지 않음
-> CQRS(조회 Service와 CUD Service 분리) 고려
-> 지금 당장은 오버인 것 같기도 해서 생각만 해놓으면 될듯!

## 2. 일정 Event 추상화
* 일정 Event 추상화 구현 중
  * `NotificationService`에서 메소드를 CUD에 따라서 나눌지, 추상화해서 하나의 메소드로만 처리할지 고민
  * `Feed(Notification)`이 `Schedule`을 참조하긴 하지만, `일정 알림 Service`에서 구체적인 EventType을 알 필요가 없다고 생각해서 EventType을 추상화해서 메소드 1개만 만들었음
  * ScheduleNotification Entity에도 Create, Update, Delete Type이 존재하지 않으므로 추상화해도 괜찮다고 생각했음
  * ScheduleNotification Entity에서 Factory에 추상화된 Event를 넘겨서 Notification을 생성하는데 이러면 구체화된 Event를 아는 건가?... 잘 모르곘음..ㅠ 
  * 그리고 NotificationServiceTest에서는 타입에 따라 테스트하고 있는데 테스트는 추상화되지 않아도 되는건가..? ㅠㅠ 모르겠더

## 3. 스프링 이벤트 관련 설계
이 부분은 나중에 미니 테코톡? 해서 설명하는 게 나을듯
일단 이유만 적어 둘게요!

### 3-1. @EventListener -> @TransactionalEventListener 사용
* Trigger로직 (Schedule CUD) 실행(Commit) 후 EventListener 로직(일정 알림)에서 예외가 발생했을 때
  * Trigger 로직(Schedule CUD)은 Commit 되어야 함
-> @TransactionalEventListener의 phase 속성 AFTER_COMMIT(기본값) 설정해서 Trigger 로직이 커밋된 이후에 EventListener 로직이 실행되도록 설정

### 3-2. Transactional(propargation = Propargation.REQUIRES_NEW) 설정 X
* Trigger 로직 -> EventListener 로직1 -> EventListener 로직2 이렇게 리스너 메소드 하나의 트랜잭션에서 insert, update, delete 쿼리가 나가는 로직이 여러개 일때 사용
* 현재는 save하는 로직 1개밖에 없으므로 사용하지 않았음

## 4. 스프링 이벤트 테스트
* Test 클래스 레벨에 `@RecordApplicationEvents`을 선언하고, `ApplicationEvents` 객체를 주입받아서 사용
  * 테스트 시 이벤트를 추적해서 카운트로 검증
* SpringBootTest가 RANDOM_PORT일 때(인수 테스트)는  @RecordApplicationEvents로 주입받아도 해당 이벤트를 추적하지 못하는 것 같음.

2023-07-31 12:08 UTC, SproutMJ requested changes
너무 잘해주셔서 스타일에 대한 부분만 리뷰 남겨보아요~

2023-07-31 12:08 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/ScheduleNotification.java
> +import jakarta.persistence.*;
import가 *이 되었네요
내마음속의 *로~~

2023-07-31 12:08 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/ScheduleNotificationFactory.java
> +
빈줄이 있네요

2023-07-31 12:08 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
> +        LocalDateTime endDateTimeToUpdate = scheduleUpdateRequest.endDateTime();
final 없네요

2023-08-01 02:38 UTC, pilyang approved these changes
우선 작동은 잘 된다고 판단하여 Approve합니다!!!

리팩터링이 필요하다고 느낀 부분들과 개선 가능해보이는 방향성에대해서 이슈생성해두었습니다.
해당 부분들에 대해서는 나중에 여유가 되면 진행하도록 하겠습니다.


리팩터링 방향성 issu

#254

2023-08-01 02:38 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/NotificationContentGenerator.java
> +public class NotificationContentGenerator {
추후 리팩터링할 방향

- 인터페이스로 생성
- implement 하는 ScheduleNotificationContentGenerator생성
- 각각의 경우에 따라 구현체 생성 (지금은 각각의 메서드로 이루어져있는것들)

2023-08-01 02:38 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/event/ScheduleEvent.java
> +    public abstract ScheduleUpdateEventDto getScheduleUpdateEventDto();
구현체에 대한 정보가 메서드에 담가는것같습니다.

후에 더 범용적인 상황으로 리팩터링이 필요해보입니다.

2023-08-01 02:38 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/event/ScheduleEvent.java
> +
필드에서 title, span을 제거하고 각각의 구현체에서 변경이전 또는 이후 또는 모두의 정보를 가지는 식으로 하면 어떤부분에서 변경이 되었는지에 따라 다른 구현을 가져가기 편할 것 같습니다.

2023-08-01 02:53 UTC, the9kim approved these changes
어떻게 해야할지 감이 안잡히던 알림 기능을

주말 동안 뚝딱 만들어 오시다니, 정말 놀랍습니다. 앞으로 형님으로 모셔도 될까요??

또 블로그로 내용을 잘 정리해주신 덕분에 공부도 많이 했습니다.

저 역시 필립의 의견과 마찬가지로 일단 기능 구현에 집중하고 추후에 리팩터링을 진행하는 방향이 좋을 듯 합니다.
추후 Notification 생성 로직을 인터페이스로 리팩터링 한다면, if문이나 여러 메서드를 통합할 수 있을 듯합니다!

어려운 기능 구현하느라 수고 많으셨습니다!!

2023-08-01 04:53 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/ScheduleNotification.java
> +import jakarta.persistence.*;
다음부터 주의해서 하도록 하겠습니다!!

이번만 봐주십시오 엔델 선생님 🙇🏻‍♂️

2023-08-01 04:54 UTC, SproutMJ approved these changes
good

2023-08-01 04:55 UTC, merged