[FE] 팀피드 스레드 작성 바텀시트 구현
woowacourse-teams/2023-team-by-team pull request #246
Opened 2023-07-31 07:44 UTC by suyoungj

# [FE] 팀피드 스레드 작성 바텀시트 구현
## 이슈번호
> close #182 

## PR 내용
- 팀피드 스레드 작성 바텀시트 구현
- UI만 구현
- css animation을 theme에 추가

<img width="1250" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/a43e8d31-bfb1-4d0f-a395-f6514d9bc8de">

2023-07-31 08:02 UTC, wzrabbit requested changes
바텀 시트 예쁘다, 수고 많이 했어... 체크박스 늦게 내서 미안

현재 스토리북에서 바텀시트가 올라오는 것을 보면 배경이 흰색이 부분이 있을 경우 바텀시트의 경계가 잘 보이지 않는 것 같은데, 혹시 그림자 등의 속성을 넣어서 바텀시트의 경계를 명확히 하는 것에 대해서는 어떻게 생각해!?

이외에도 코멘트 몇 개 적어뒀어!

2023-07-31 08:18 UTC, hafnium1923 requested changes
구우우ㅜ우우웃

2023-07-31 08:18 UTC, hafnium1923 commented on frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.styled.ts
> +export const Backdrop = styled.div`
백드롭 자주 쓰이는데 이쯤되면 스타일 빼야하나?ㅋㅎㅋㅎ

2023-07-31 08:18 UTC, hafnium1923 commented on frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.styled.ts
> +`;
동의합니다

2023-07-31 08:18 UTC, hafnium1923 commented on frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
> +    <Modal>
모달로 왜 감싼거야?

2023-07-31 08:18 UTC, hafnium1923 commented on frontend/src/hooks/useBottomSheet.ts
> +    timerId.current = setTimeout(() => {
이거 코드 한번 설명해줄 수 있어? 어떤 것을 위해 있는지 잘 모르겠어

2023-07-31 08:18 UTC, hafnium1923 commented on frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.styled.ts
> +    0.3s ease-in-out forwards;
조금 더 천천히 애니메이션을 해도 좋을 것 같아. 지금 너무 휙휙 나타났다 사라지는 느낌?

2023-07-31 08:24 UTC, suyoungj commented on frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.styled.ts
> +export const Backdrop = styled.div`
약간 회색빛 도는 영역으로 통일할거면 Dimmed 컴포넌트로 빼도 좋을듯? 일단 유지할게

2023-07-31 08:25 UTC, suyoungj commented on frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
> +            maxLength={1500}
굳굳 feed 파일이 있었네 거기 빼두면 좋겠다

2023-07-31 08:43 UTC, suyoungj commented on frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
> +            maxLength={1500}
이거 rebase하면 컨플릭트 나서 이후 PR에서 반영할게!

2023-07-31 08:44 UTC, suyoungj commented on frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
> +    <Modal>
바텀시트도 화면 위에 나타나야 하니까 Portal 적용하는게 맞는거 같아서 Modal로 감쌌어

2023-07-31 08:45 UTC, suyoungj commented on frontend/src/hooks/useBottomSheet.ts
> +    timerId.current = setTimeout(() => {
좀 지저분하긴 한데, 애니메이션을 위한 코드야
모달이 바로 닫히면 애니메이션이 안보여서, 닫히는 중임을 나타내는 상태(`isClosing`)를 따로 주고 애니메이션이 끝나면 모달이 닫히도록 하는 로직이야

2023-07-31 12:04 UTC, wzrabbit approved these changes
LGTM

2023-08-01 00:57 UTC, hafnium1923 approved these changes
수고하셨슴둥~~

2023-08-01 00:57 UTC, merged