[BE] 팀피드 스레드 조회 기능 구현
woowacourse-teams/2023-team-by-team pull request #251
Opened 2023-07-31 11:53 UTC by SproutMJ

## 이슈번호
#213

## PR 내용
팀 피드를 최신 순으로 조회합니다.
처음에 사용하는 api와 이후에 조회한 피드의 마지막 id를 재사용하는 재조회 api로 나뉘어 있습니다.

## 참고자료
https://tecoble.techcourse.co.kr/post/2021-08-15-pageable/

## 의논할 거리

2023-08-01 01:42 UTC, pilyang requested changes
몇몇 부분 커멘트 달았습니다!!

이전에 전반적으로 잘 설명해줘서 이해하기 편했습니다!

2023-08-01 01:42 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +
threadId 라는 이름으로 파라미터를 받아서 사용하는데, threadId라고 하면 feed에  등록된 thread의 아이디만 사용된다는 오해가 생길 수 있을 것 같습니다.

Feed에는 Thread와 Notification이 모두 있으니 feedId라는 네이밍을 사용하는것이 조금 더 적절하지 않을까 합니다.

2023-08-01 01:42 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +    }
```suggestion
    private List<FeedResponse> mapFeedResponses(final List<Feed> feeds) {
        return feeds.stream()
                .map(this::mapToResponse)
                .toList();
    }

    private FeedResponse mapToResponse(final Feed feed) {
        if (FeedType.THREAD == feed.getType()) {
            final Optional<Member> member = memberRepository.findById(feed.getAuthorId());
            final Member member1 = member.orElseThrow(MemberException.MemberNotFoundException::new);
            return FeedResponse.from(feed, member1.getName().getValue(), member1.getProfileImageUrl().getValue());
        }
        if (FeedType.SCHEDULE_NOTIFICATION == feed.getType()) {
            return FeedResponse.from(feed, "schedule", "");
        }
        throw new IllegalArgumentException("지원하지 않는 타입입니다.");
    }
```

다음과 같이 메서드 분리해서 리팩터링 할 수 있을 것 같습니다.
이런식으로 해두면 후에 enum타입을 활용해서 response를 만드는 방식등에 패턴을 적용하거나 할 때도 `mapToResponse`로 빼둔 메서드만 리팩터링 하는 등의 방법으로 쉽게 할 수 있고 가독성도 좋아질 것 같습니다.

2023-08-01 01:42 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +                final Member member1 = member.orElseThrow(MemberException.MemberNotFoundException::new);
```suggestion
                final Member member = memberRepository.findById(feed.getAuthorId())
                        .orElseThrow(MemberException.MemberNotFoundException::new);
```

위와같이 하면 member1같은게 안생기지 않을까요...?

2023-08-01 01:47 UTC, sh111-coder requested changes
테스트 관련 부분에서 수정할 부분들이 몇 개 보여서 코멘트 남겼습니다!! 
반영하고 슬랙에 올려주세욥

프로덕션 코드 로직은 잘 짜주신 것 같습니다!! 굿굿

2023-08-01 01:47 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +                final Member member1 = member.orElseThrow(MemberException.MemberNotFoundException::new);
```suggestion
final Member findMember = memberRepository.findById(feed.getAuthorId()).orElseThrow(MemberException.MemberNotFoundException::new);
```
위처럼 Optional 변수 뺄 필요 없이 한번에 처리하면 좋을 것 같아요!

2023-08-01 01:47 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/feed/domain/Feed.java
> +    public abstract Long getAuthorId();
추상 메소드 굿굿

2023-08-01 01:47 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
> +    class GetThread {
인증 관련 실패 테스트 케이스가 빠져있는 것 같아요!

인증되지 않은 멤버면 실패하는 테스트 케이스와 소속되지 않은 팀 플레이스면 실패하는 테스트 케이스가 빠진 것 같습니다!

2023-08-01 02:35 UTC, the9kim commented
짦은 시간에 빠르게 기능을 구현해주셨네요!

엔델이 재야의 고수라는 소문이 있던데 하루 빨리 세상밖으로 나오시기 바랍니다.

세부적이 리팩터링 요소를 코멘트를 남겼습니다. 

대세에는 지장이 없는 관계로 일단 머지 하겠습니다!

2023-08-01 02:35 UTC, the9kim submitted a review, later dismissed

2023-08-02 04:17 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +
적용 완료

2023-08-02 04:36 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +    }
적용 완료 했습니다.

2023-08-02 04:38 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +                final Member member1 = member.orElseThrow(MemberException.MemberNotFoundException::new);
적용 완료 했습니다.

2023-08-02 04:56 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/feed/domain/FeedRepositoryTest.java
> +        insertFeeds.add(new ScheduleNotification(1L, new Content("테스트 알림"), 3L));
픽스처를 리스트로 만들어보려고 했는데 리스트 내용이 3개, 4개, 5개, 6개 등이거나 일정 알림, 스레드 조합 등 다양한 구성이 필요해서 메서드마다 각각 만들어주는게 좋을 것 같아요.......

2023-08-02 04:57 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +                final Member member1 = member.orElseThrow(MemberException.MemberNotFoundException::new);
처리했습니다.

2023-08-02 06:36 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
> +    class GetThread {
4개 케이스 추가 완료.

2023-08-02 06:42 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +        final List<Feed> list = feedRepository.findByTeamPlaceId(teamPlaceId, pageable);
pageSize로 변경했습니다.

2023-08-02 06:42 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +        final List<Feed> list = feedRepository.findByTeamPlaceIdAndIdLessThan(teamPlaceId, threadId, pageable);
pageSize로 변경했습니다.

2023-08-02 06:44 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +                return FeedResponse.from(feed, member1.getName().getValue(), member1.getProfileImageUrl().getValue());
일단 member1과 member는 합쳤구요, member가 가진 정보가 어차피 필요해서 member를 한번 가져오긴 해야할 것 같아요.

2023-08-02 08:56 UTC, the9kim approved these changes

2023-08-02 08:59 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/feed/domain/FeedRepositoryTest.java
> +        insertFeeds.add(new ScheduleNotification(1L, new Content("테스트 알림"), 3L));
제가 생각이 짧았네요... 죄송합니다,...

2023-08-02 09:03 UTC, sh111-coder approved these changes
수고하셨습니당!! 페이지네이션 짱짱맨 👍🏻👍🏻👍🏻👍🏻

2023-08-02 09:20 UTC, pilyang approved these changes
고생하셨습니다~~ approve 할께요!!

2023-08-02 10:37 UTC, merged