[FE] 팀피드 공지 조회 API 연결
woowacourse-teams/2023-team-by-team pull request #276
Opened 2023-08-01 11:56 UTC by wzrabbit

[FE] 팀피드 공지 조회 api 연결

## 이슈번호
> close #189

## PR 내용
본 PR에서는 팀 피드의 공지를 조회할 수 있도록 API를 연결하고, 공지를 스레드 리스트에 포함시켰다.

- 스레드 조회에 대해 msw 모킹을 진행하였다.
- 스레드 조회를 위한 비동기 로직을 구현하였다.
- 스레드 리스트 컴포넌트의 최상단에 공지를 불러와 랜더링할 수 있도록 구현하였다.

## 참고자료
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/def82ada-7855-4e1f-9410-532c6dacca49)

## 참고사항
지금은 API 연결이 목적이니까, UI가 이상하고 일치하지 않더라도 일단은 넘어가 줄 수 있어? UI를 통일시키는 작업은 그 이후에 진행하자.

2023-08-01 12:56 UTC, hafnium1923 requested changes
좋아요~

2023-08-01 12:56 UTC, hafnium1923 commented on frontend/src/components/ThreadList/ThreadList.tsx
> +          profileImageSrc={noticeThread.profileImageUrl || ''}
```suggestion
          profileImageSrc={noticeThread.profileImageUrl ?? ''}
```

2023-08-01 12:56 UTC, hafnium1923 commented on frontend/src/types/feed.ts
> +export type NoticeThread = Omit<Thread, 'type'> | Record<string, never>;
` profileImageUrl: string | null; `
유저 url은 무조건 들어오니까 null을 없애도 될 것 같아

2023-08-01 12:56 UTC, hafnium1923 commented on frontend/src/components/ThreadList/ThreadList.tsx
> +          profileImageSrc={noticeThread.profileImageUrl || ''}
근데 ` profileImageUrl: string `이렇게 들어올거면 없어도 될 것 같은데

2023-08-01 12:56 UTC, hafnium1923 commented on frontend/src/hooks/queries/useFetchNoticeThread.ts
> +  const { noticeThread } = data;
객체로 감싸서 오지 않아..

2023-08-01 12:56 UTC, hafnium1923 commented on frontend/src/hooks/queries/useFetchNoticeThread.ts
> +  const { noticeThread } = data;
```
{
		"id" : 1
		"content" : "블라블라블라브블라",
		"authorName" : "endle",
		"authorId" : userid,
    "profileImageUrl" : "http://example.com/profile/image.png"
		"createdAt" : "2023-07-27 08:20"
}

```

2023-08-01 12:56 UTC, hafnium1923 commented on frontend/src/mocks/handlers/feed.ts
> +        ctx.json({
```
ctx.json(noticeThread)
```
 로 와야할듯?!

2023-08-01 12:56 UTC, hafnium1923 commented on frontend/src/hooks/queries/useFetchNoticeThread.ts
> +  const { data } = useQuery(['noticeThread'], () =>
```suggestion
  const { data } = useQuery(['noticeThread', teamPlaceId], () =>
```

2023-08-01 12:56 UTC, hafnium1923 commented on frontend/src/components/ThreadList/ThreadList.tsx
> +      {noticeThread && noticeThread.authorId && (
```suggestion
      {noticeThread && noticeThread.Id && (
```
공지가 없는 경우를 한번 더 확인하는거면 thread 고유번호인 Id를 검사하는게 더 좋을 것 같아요

2023-08-01 12:57 UTC, wzrabbit commented on frontend/src/components/ThreadList/ThreadList.tsx
> +          profileImageSrc={noticeThread.profileImageUrl || ''}
백엔드에서 `null` 줄 일 없으니까 `null` 빼버릴게

2023-08-01 12:57 UTC, wzrabbit commented on frontend/src/types/feed.ts
> +export type NoticeThread = Omit<Thread, 'type'> | Record<string, never>;
백엔드에서 `null` 줄 일 없다는 걸 알게됐으니 `null` 빼버릴게

2023-08-01 13:03 UTC, wzrabbit commented on frontend/src/components/ThreadList/ThreadList.tsx
> +          profileImageSrc={noticeThread.profileImageUrl || ''}
맞아, 무조건 `string` 으로 추론된다면 - 이 부분은 필요 없겠지.
이 부분은 지워서 반영할게

2023-08-01 13:04 UTC, wzrabbit commented on frontend/src/hooks/queries/useFetchNoticeThread.ts
> +  const { noticeThread } = data;
<img src="https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/696ad40d-a9df-44a6-8a8e-c3f50f083227" width="50px" />

2023-08-01 13:06 UTC, wzrabbit commented on frontend/src/components/ThreadList/ThreadList.tsx
> +      {noticeThread && noticeThread.authorId && (
OK!

2023-08-01 13:17 UTC, wzrabbit commented on frontend/src/hooks/queries/useFetchNoticeThread.ts
> +  const { data } = useQuery(['noticeThread'], () =>
이렇게 해야 `teamPlaceId` 도 캐싱에 관여해서 다른 결과를 얻을 수 있는 거구나. 고마워
수정사항을 반영하지 않을 경우에는 이후 다른 팀플레이스 아이디를 넣어도 캐싱되서 같은 결과가 나오겠네

2023-08-02 01:18 UTC, suyoungj approved these changes
👍

2023-08-02 01:30 UTC, hafnium1923 approved these changes
수고하셨슴둥~

2023-08-02 01:30 UTC, merged