[BE] 공지 조회 기능 구현
woowacourse-teams/2023-team-by-team pull request #298
Opened 2023-08-02 11:13 UTC by the9kim

## 이슈번호
> #218 

## PR 내용
- 공지 조회 기능 구현
    - (공지 기등록 시) 가장 최근에 등록된 공지 조회
    - (공지 미등록 시) 빈값 반한
- 공지 조회 기능 관련 레포지토리, 서비스, 인수 테스트 구현

## 참고자료

## 의논할 거리

2023-08-02 13:52 UTC, pilyang requested changes
null사용하는 부분에 대해서만 커멘트 남겼습니다!! 혹시 다른부분 더 보이면 추가하도록 할 것 같은데,

전반적으로 잘 구현된것 같습니다!!!

최신공지 조회 레포지터리 쿼리도 매우좋아요~~

2023-08-02 13:52 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +    }
method 의 response로 null이 반환되는 경우는 피하는것이 좋을 것 같습니다. 차리리 Optional로 반환을 해서 해당 반환값을 받아서 isEmpty등을 사용하는것이 해당 메서드에서 반환할 데이터가 없음을 나타낼 수 있는 방법이라고 생각합니다.

2023-08-02 13:52 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/notice/presentation/NoticeController.java
> +        return ResponseEntity.ok(noticeResponse);
Service에서 단 Comment처럼 `Optional`로 반환을 한다면 `==null`로 검사를 하는것이 아닌 isEmpty를 통해 검사를 할 수 있을것이라고 생각합니다.

혹시 다른 좋은 방법이 있어도 좋을 것 같습니다. null로 확인하는것만 아니라면...ㅎㅎ

2023-08-03 00:51 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +    }
사실 null을 직접 다뤄 본 경험이 없어서 필립이 지적한 내용을 미처 생각해보지 못했네요.

아래 코멘트에서 언급하신 것 처럼, null을 직접 반환 할 경우, 해당 null값의 출처가 불명확해서 코드의 가독성이 떨어지는 문제가 있을 듯 합니다. 

따라서 Optional을 반환 후  isEmpty()메서드로 빈 값 여부를 확인하는 방식으로 수정해봤습니다!

2023-08-03 01:20 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/notice/presentation/NoticeController.java
> +        return ResponseEntity.ok(noticeResponse);
동의합니다!! 그래도 null 사용 시 어떤 부분이 안 좋은지 대충만 알고 있었는데 구체적인 코드로 볼 수 있어서 좋았습니다!

2023-08-03 01:24 UTC, SproutMJ requested changes
잘해주셨는데 null에서 Optional로 리팩토링해주신 부분까지 잘 봤습니다. 근데 DisplayNmae이 최신화가 된건지 확인만 해주시면 좋을 것 같습니다.

2023-08-03 01:24 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/notice/domain/NoticeRepositoryTest.java
> +    @DisplayName("공지를 조회할 때 등록된 공지가 없을 경우 null을 반환한다.")
null이 아니라 Optional 아닌가요?? 이부분은 혹시 수정이 안된건지요

2023-08-03 01:30 UTC, the9kim commented on backend/src/test/java/team/teamby/teambyteam/notice/domain/NoticeRepositoryTest.java
> +    @DisplayName("공지를 조회할 때 등록된 공지가 없을 경우 null을 반환한다.")
역시 날카로우시군요.

냅다 수정했습니다.

2023-08-03 01:35 UTC, sh111-coder requested changes
수고하셨습니다!! ㅎㅎ
공지 조회 잘 해주신 것 같아요 짱짱!

수정 사항 몇 부분 코멘트 했는데 수정하면 바로 Approve 하겠습니다!!

2023-08-03 01:35 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/notice/presentation/NoticeController.java
> +    }
리팩토링 하니까 훨씬 깔끔하네요!!

2023-08-03 01:35 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +    }
flatMap 잘 안 써봐서 해당 코드 설명 가능할까요??

2023-08-03 01:35 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/notice/domain/NoticeRepositoryTest.java
> +    @DisplayName("공지를 조회할 때 등록된 공지가 없을 경우 null을 반환한다.")
++ 공지 조회 시 등록된 공지가 없을 때에 대한 테스트 케이스이므로
teamPlaceId는 존재하는 teamPlaceId여야 할 것 같아요!

2023-08-03 01:35 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
> +            member = testFixtureBuilder.buildMember(ROY());
멤버 본인으로 한 거 깜찍하네요 ㅋㅋㅋㅋㅋ 😎

2023-08-03 01:35 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
> +            assertThat(noticeResponse).isEmpty();
해당 메소드 DisplayName도 수정해야 할 것 같습니다!

2023-08-03 01:38 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +    }
그럼요

2023-08-03 01:50 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +    public Optional<NoticeResponse> findMostRecentNotice(final Long teamPlaceId) {
@Transactional(readOnly = true) 붙여야 할 것 같습니다!

2023-08-03 01:51 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +    }
일단 배경 설명을 하자면,

1. NoticeRepository에서 팀플레이스 Id로 공지를 조회할 경우 Optional<Notice>가 (서비스 레이어로) 반환됩니다.

2. 서비스 레이어에서 목적은 NoticeResponse 객체를 Optional로 포장해서 반환하는 것입니다.(앞서 필립의 피드백을 반영한 사안이죠). 

3. 리스폰스 객체 생성 + Optional 포장에 앞서 레포지토리에서 넘어온 optional<Notice> 객체의 포장을 벗겨낼 필요가 있는데요. 이를 위해 사용한 기능이 FlatMap입니다. 플랫맵은 스트림이 배열 또는 Optional로 여러겹 포장됐을 경우 포장을 벗기고 단일 요소로 처리하는 기능으로 이해하고 있습니다. 아래는 간단한 예시코드입니다.

```
List<List<Integer>> nestedList = List.of(
    List.of(1, 2, 3),
    List.of(4, 5, 6),
    List.of(7, 8, 9)
);

List<Integer> flattenedList = nestedList.stream()
                                        .flatMap(List::stream)
                                        .collect(Collectors.toList()); 
```
4. 결론적으로 FlatMap이 아닌 Map을 사용할 경우, 필요로 하는 반환값 Optional<NoticeResponse> 가 아니라 Optional<Optional<NoticeReponse>>가 반환됩니다.

사실 저도 사용 경험이 많지 않아 정확히 이해하고 한 설명인지 확신을 못하겠네요.

추가로 궁금하신 부분이나 잘못된 내용이 있다면 알려주세요! 👍

2023-08-03 02:00 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +    public Optional<NoticeResponse> findMostRecentNotice(final Long teamPlaceId) {
꼼꼼하지 못햇네요. 수정했습니다!

2023-08-03 02:03 UTC, the9kim commented on backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
> +            member = testFixtureBuilder.buildMember(ROY());
위에 코멘트에 댓글이 안달리네요..

디테일한 지적 감사합니다. 역시 열심히 보셨군요👍

teamPlace 등록 후 존재하는 id를 이용하여 테스트 진행하도록 수정했습니다!

2023-08-03 02:03 UTC, the9kim commented on backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
> +            assertThat(noticeResponse).isEmpty();
수정 완료했습니다!

2023-08-03 02:04 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/notice/presentation/NoticeController.java
> +        return ResponseEntity.ok(noticeResponse);
ㅋㅋㅋ코드를 엉망으로 짜는 것도 그 나름 의미가 있겠군요!

이 한 몸 희생하겠습니다!

2023-08-03 02:12 UTC, pilyang reviewed
완전 RC는 아니여서 일단 Comment로 남깁니다.

명세 확인해주시고, 프런트랑 이야기 해서 명세를 바꾸던가 코드를 수정하는 방식으로 하면 될 것 같습니다.

2023-08-03 02:12 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +    }
Optional이 이중으로 사용되서 사용된 것 같네요.

지금 상황에서는 어쩔 수 없어보이긴 합니다! 좀 더 가독성 좋게 리팩터링하는 방법이 뭐가 있을까라는 고민이 들기는 하는데, 일단은 괜찮다고 생각됩니다..!

막 떠오르는게 있으면 다른 방법을 추천해줄 수 있을것같은데 저도 잘 아는 방식은 아니여서..ㅠㅜ

2023-08-03 02:12 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/notice/presentation/NoticeController.java
> +    }
<img width="598" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/30036534/d329d7d7-cefa-412f-b0ac-add10e93d064">


명세 확인 부탁드립니다..!!

처음 코드볼때 리뷰 남겨야지 했다가 급하게 한다고 까먹고 못남겼었네요ㅠㅜ

둘다 200 ok 반환하기로 변경했던 것 같습니다....
프런트에서 204에 빈 값이여도 상관없다고 하면 해당 방법도 상관 없이 명세를 수정하면 될 것 같습니다.

2023-08-03 02:17 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +    }
아하!! 설명이랑 코드보고 다시 프로젝트 코드 보면서 대충 이해했습니다!!!
친절한 설명 감사합니다... 🌠

2023-08-03 02:20 UTC, sh111-coder approved these changes
수정 사항 반영돼서 Approve 하겠습니다!!

꼼꼼하게 잘 반영해주셔서 감사합니다 ㅎㅎ 👍🏻👍🏻👍🏻

2023-08-03 05:40 UTC, pilyang approved these changes
반영해주신 내용들 확인 완료ㅕ했습니다!

2023-08-03 05:41 UTC, SproutMJ approved these changes
good

2023-08-03 05:42 UTC, merged