[FE] 유틸함수, 컴포넌트 구조 간단 리팩터링
woowacourse-teams/2023-team-by-team pull request #340
Opened 2023-08-07 03:09 UTC by hafnium1923

# [FE] 유틸함수, 컴포넌트 구조 간단 리팩터링
## 이슈번호
> 간단해서 없어요

## PR 내용
1.  왜인지 모르겠지만 tsx확장자로 되어있던 파일 ts로 확장자 변경
2. 유틸함수 비슷한 기능 하는 애들끼리 묶음
3. 스레드, 일정알림 컴포넌트를 스레드 리스트 컴포넌트 하위로 이동

## 참고자료

## 의논할 거리

2023-08-07 06:11 UTC, suyoungj reviewed
👍 고생했어

음.. 지금 구조도 괜찮아 보이긴 하는데 테스트 코드랑 얽힌게 보기 안좋다면 각각을 폴더로 만들고 그 안에 유틸 함수 + 테스트 코드를 넣는 건 어때? get, format, generate라는 폴더명이 잘 안 와닿기도 하고 1 depth가 불필요하게 늘어나는 느낌도 들어

2023-08-07 06:13 UTC, hafnium1923 commented
그것도 괜찮아보인다 각각으로 해볼게

2023-08-08 00:59 UTC, suyoungj approved these changes

2023-08-08 01:22 UTC, wzrabbit requested changes
수고했읍니다!

1. `ThreadList` 에 `NoticeThread` 를 합치면서, 미처 파일 구조는 바꾸지 못 했는데 파일 구조를 **After** 와 같이 바꾸는 건 어떻게 생각해?

`NoticeThread` 가 `ThreadList` 안에 긴밀하게 결합해 있으면서도 `ThreadList` 외에 쓰이는 곳이 없어보여서

```
Before:
📦components
 ┣ 📂NoticeThread
 ┣ 📂ThreadList
 ┃ ┣ 📂Notification
 ┃ ┗ 📂Thread

After:
📦components
 ┣ 📂ThreadList
 ┃ ┣ 📂Notification
 ┃ ┣ 📂Thread
 ┃ ┗ 📂NoticeThread
```

2. 지금은 괜찮지만, 나중에 유틸 함수/테스트 코드가 더 많아지면 이것도 분류별로 나누는 걸 고려하면 좋을 것 같아, 그 때는 팀원 중 누구든지 이슈를 새로 파봐도 좋을 것 같어

2023-08-08 02:46 UTC, pilyang requested changes
BE filechanged 없으면 될 것 같습니다.

2023-08-08 02:59 UTC, suyoungj approved these changes

2023-08-08 03:02 UTC, wzrabbit approved these changes
👍🏻

2023-08-08 03:06 UTC, pilyang approved these changes

2023-08-08 04:07 UTC, merged