[BE] 팀 플레이스 도메인 작성
woowacourse-teams/2023-team-by-team pull request #38
Opened 2023-07-12 11:41 UTC by sh111-coder

## 이슈번호
> #27 

## PR 내용

- 팀 플레이스 도메인 구현
  - 팀 플레이스 이름 VO 구현
  - 팀 플레이스 이름 VO 검증 테스트 

- 팀 플레이스 Exception 구현

## 참고자료

## 의논할 거리

2023-07-12 11:43 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/teamplace/domain/Name.java
> +import jakarta.persistence.Embeddable;
리뷰를 시작합니다.

2023-07-12 11:44 UTC, SproutMJ requested changes
변경 요청

2023-07-12 11:46 UTC, pilyang requested changes
내용은 좋은데 중간에 컨벤션 안맞는 부분이 있어서 request change 남겨요
수정하고 다시 요청 부탁드립니다!!

2023-07-12 11:46 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/teamplace/domain/Name.java
> +    private String value;
style로 해서 개행 해주세요
```suggestion

    private static final int MAX_LENGTH = 30;
    
    @Column(name = "name", nullable = false, length = MAX_LENGTH)
    private String value;
```

2023-07-12 11:52 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/teamplace/domain/Name.java
> +    private String value;
수정했슴다!! ^^

2023-07-12 11:59 UTC, pilyang approved these changes

2023-07-12 13:07 UTC, pilyang requested changes

2023-07-12 13:07 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/teamplace/domain/Name.java
> +        if (value.length() > MAX_LENGTH) {
해당 부분은 개발자의 실수를 방지하기 위한 것이니까 메시지를 `null`로 수정하는것이 좋을 것 같습니다.

2023-07-13 01:28 UTC, the9kim approved these changes
고생하셨습니다! 특별한 이상은 없는 듯 해서 머지합니다.

같이 이야기 해볼 부분은 코멘트 달았습니다!

2023-07-13 01:28 UTC, the9kim commented on backend/src/test/java/team/teamby/teambyteam/teamplace/domain/NameTest.java
> +        Assertions.assertThatThrownBy(() -> new Name(nullName))
컨벤션 관련해서 Assertions 라이브러리를 static으로 뽑을 지도 같이 한번 이야기 해봅시다!

2023-07-13 01:52 UTC, pilyang approved these changes

2023-07-13 01:53 UTC, SproutMJ approved these changes
good

2023-07-13 01:53 UTC, merged