[BE] 멤버 도메인 작성
woowacourse-teams/2023-team-by-team pull request #41
Opened 2023-07-13 04:39 UTC by sh111-coder

## 이슈번호
> #25 

## PR 내용

-Member 도메인 작성
- MemberTeamPlace 도메인 작성
- MemberRepository, MemberTeamPlaceRepository 구현

## 참고자료

## 의논할 거리

- Member <-> MemberTeamPlace <-> TeamPlace 연관관계 생각해보기

2023-07-13 04:39 UTC, the9kim approved these changes

2023-07-13 04:42 UTC, pilyang requested changes

2023-07-13 04:42 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Email.java
> +public class Email {
```java
@Emabadalbe
```

이 빠진 것 같습니다.

2023-07-13 04:43 UTC, SproutMJ requested changes
확인 바랍니다!

2023-07-13 04:43 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Email.java
> +public class Email {
임베더블 없습니다!

2023-07-13 04:43 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
> +
@Repository 안붙여도 되나요?

2023-07-13 04:43 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/member/domain/MemberRepository.java
> +
@Repository 안붙여도 되나요?

2023-07-13 04:46 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
> +
필요 없다네요 ^^

2023-07-13 04:50 UTC, SproutMJ approved these changes
good

2023-07-13 04:50 UTC, pilyang approved these changes

2023-07-13 04:51 UTC, merged

2024-05-11 11:37 UTC, 0Jaemin0 commented
현재 초대 코드에 대한 에러 부분은 응답으로 받은 에러 메세지를 보여주고 있고, 팀 스페이스 참가에 대한 초대 코드를 입력하는 화면으로 전체적으로 '초대 링크'에서 '초대 코드'로 텍스트를 바꿔도 좋을 것 같습니다.
참가 링크가 유효한 경우에는 초대 코드를 통해 팀 스페이스 확인 -> 해당 팀 스페이스 가입 여부 확인 -> 해당 팀 스페이스 참가 요청 -> 가장 최근 접근 팀 스페이스 기록 -> 해당 팀 페이지 이동
위와 같은 과정으로 동작하고 있습니다.