[BE] feed api 문서화
woowacourse-teams/2023-team-by-team pull request #424
Opened 2023-08-10 08:04 UTC by SproutMJ

## 이슈번호
#212
#214

## PR 내용
팀 피드 작성, 조회 기능 문서화

## 참고자료

## 의논할 거리

2023-08-10 09:44 UTC, sh111-coder approved these changes
수고하셨습니다 ㅎㅎㅎ 문서화는 html 봐야 할 것 같네유 
일단 approve 할게요!

2023-08-10 14:14 UTC, pilyang requested changes
다양하게 전반적으로 잘 작성해준것같아서 좋습니다!!

좀더 이쁘게 출력하는거 커멘트 달았습니다 반영 부탁드립니다~~

2023-08-10 14:14 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
> +                    );
```java
.andDo(document("feeds/read/first/success",
                                    preprocessRequest(prettyPrint()),
                                    preprocessResponse(prettyPrint()),
                                    pathParameters(
                                            parameterWithName("teamPlaceId").description("멤버가 속한 팀 플레이스 ID")
                                    ),
                                    queryParameters(
                                            parameterWithName("size").description("요청할 최신 피드의 개수")
                                    ),
                                    requestHeaders(
                                            headerWithName(AUTHORIZATION_HEADER_KEY).description("사용자 JWT 인증 정보")
                                    ), responseBody(
                                    )
                            )
                    );
```


위에처럼 `preprocessResponse(prettyPrint())`를 추가해주면 Response도 한줄로 출력이 되는것이 아닌 매우 pretty하게 잘 출력이 됩니다^^

2023-08-10 14:14 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
> +                                    ),
이부분도 위에서 말한것처럼 `preprocessResponse(prettyPrint())`를 추가해지면 이뻐집니다ㅎㅎ

추가적으로 다른부분도 필요하다고 생각되는 부분에 추가하면 좋을 것 같습니다.

2023-08-13 07:47 UTC, the9kim approved these changes
고생 많으셨습니다 엔델!

저도 빨리 문서화 마무리 하겠습니다ㅠ

2023-08-14 14:19 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
> +                                    ),
전부 적용했습니다.

2023-08-14 14:19 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
> +                    );
전부 적용했습니다.

2023-08-15 05:49 UTC, pilyang approved these changes
확인했습니다!!

2023-08-15 06:21 UTC, pilyang requested changes
예외상황들 반영된거 한번 머지시키고 잘 동작하는지 확인하고 머지된 커밋 포함해서 다시 푸시 부탁드립니다!

머지하고 확인해본 다음에 member domain 문서화 pr에 날린 코멘트들 있는데 해당 부분도 확인하고 혹시 여기서도 예외 response에서 비슷한 현상이 생긴다면 반영 부탁드립니다.

2023-08-15 07:10 UTC, pilyang approved these changes
반영해주신 내용들 확인했습니다!!

2023-08-15 07:10 UTC, merged