[FE] 팀 정보 / 개인 정보 조회 기능 및 UI 구현
woowacourse-teams/2023-team-by-team pull request #467
Opened 2023-08-12 10:45 UTC by suyoungj

# [FE] 팀 정보 / 개인 정보 조회 기능 및 UI 구현
## 이슈번호
> close #393 close #399 

## PR 내용
- 팀 정보, 초대코드 조회
- 개인 정보 조회
- 팀 나가기 기능 위치 수정
<img width="348" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/4cde91f6-49a1-496e-b82b-fcd2587ff2f9">

![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/fbd1580c-c1e2-45ba-b5e0-f9880f4b9acc)

2023-08-12 11:35 UTC, hafnium1923 requested changes
너무 잘해서 코멘트 달게 없네

2023-08-12 11:35 UTC, hafnium1923 commented on frontend/src/apis/auth.ts
> +  return http.get<{
비슷한 타입들이 계속 재사용되는 것 같은데 따로 타입을 정의하지 않은 이유가 있다면 알려줘!

2023-08-12 11:35 UTC, hafnium1923 commented on frontend/src/apis/team.ts
> +  return http.get<{
얘는 여기서만 사용해서 따로 타입 선언안한건가?

2023-08-12 11:35 UTC, hafnium1923 commented on frontend/src/components/common/Header/Header.styled.ts
> +  width: 1px;
어쩔수없는 1px인가요?

2023-08-12 11:35 UTC, hafnium1923 commented on frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
> +  height: 1px;
어쩔수없는 1px인가여?2

2023-08-12 11:35 UTC, hafnium1923 commented on frontend/src/components/user/UserInfoModal/UserInfoModal.styled.ts
> +  margin: 10px auto;
마진이랑 높이, 넓이는 굳이 띄울 필요없을드?

2023-08-12 11:35 UTC, hafnium1923 commented on frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
> +  &:hover {
hover가 있으니까 뭔가 클릭이 될 것 같은데 그냥 hover 효과만 있는거라 어색한 것 같아! 없어도 될듯?

2023-08-12 11:54 UTC, suyoungj commented on frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
> +  &:hover {
구분선대신 hover로 구분하는게 더 괜찮아보여서 이렇게 했는데, 없는게 더 나을까?? 너무 구분이 안될 것 같다는 생각도 들어

2023-08-12 11:55 UTC, suyoungj commented on frontend/src/apis/auth.ts
> +  return http.get<{
일단 다른 api 메서드처럼 작성하고, 나중에 api 응답 관련 타입을 전반적으로 리팩토링하는게 나을 것 같다는 생각이 들어서 이렇게 작성했어

2023-08-12 11:55 UTC, suyoungj commented on frontend/src/apis/team.ts
> +  return http.get<{
위 댓글이랑 같은 이유야!

2023-08-12 12:18 UTC, hafnium1923 commented on frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
> +  &:hover {
그것때문에 그렇다면 나는 구분선이 더 좋을 것 같아! hover는 정말 클릭이벤트가 있을 것 같은 느낌이거든

2023-08-12 14:34 UTC, wzrabbit reviewed
msw 전부 제대로 작동하는 거 확인했어~ 메뉴 예쁘게 구현했던데?
코멘트 몇 개만 확인해줘!

2023-08-12 14:34 UTC, wzrabbit commented on frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
> +  overflow-y: auto;
```
2. overflow - 넘침

6. margin & padding(그룹) - 간격
```

2023-08-12 14:34 UTC, wzrabbit commented on frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
> +  &:hover {
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/cebff040-fcb0-43b4-a268-db6709e80d45)

이 메뉴 이야기구나
나도 구분선 좋을 것 같아, 넣는다면 얇은 굵기로 넣으면 좋을 것 같아

그리고 개인적인 생각이지만 아예 구분선이 없는 것도 딱히 어색하지는 않았어

2023-08-12 14:34 UTC, wzrabbit commented on frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
> +  object-fit: cover;
프사 짜부 방지 속성 좋은데 👍🏻
나도 좋아하는 속성이야

2023-08-12 14:34 UTC, wzrabbit commented on frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
> +  height: 1px;
고것은 디자이너의 마음이자 생각입니다

2023-08-12 14:34 UTC, wzrabbit commented on frontend/src/components/user/UserInfoModal/UserInfoModal.tsx
> +        <S.Email href={`mailto:${email}`}>{email}</S.Email>
클릭하면 바로 이메일 전송 창이 열리도록 구현했구나
색다르기는 한데, 이 기능이 꼭 필요한 기능인지는 잘 모르겠어

다른 팀원의 이메일을 눌렀을 때 이 창이 열리도록 구현한다면 다른 팀원에게 빠르게 이메일을 보낼 때 유용해서 기능을 구현하는 이유가 이해되는데,
지금 이 기능은 자신의 이메일로 `mailto` 스킴을 켜는 거라 어색하다는 생각이 들어, 자기 자신의 이메일 주소가 받는 사람의 주소로 등록되는 것도 어색해 보이고

이 기능을 왜 넣었는지, 유스의 의도가 궁금한데 알려줄 수 있어?

2023-08-12 14:34 UTC, wzrabbit commented on frontend/src/hooks/queries/useFetchTeamPlaceMembers.ts
> +  const { members } = data ?? {};
오 이것도 괜찮은 방법 같은데?

2023-08-13 06:14 UTC, suyoungj commented on frontend/src/components/user/UserInfoModal/UserInfoModal.tsx
> +        <S.Email href={`mailto:${email}`}>{email}</S.Email>
뭔가 허전해서 넣었는데, 굳이 필요없다는 의견에 나도 동의ㅋㅋㅋㅋ
다른 사람 메일 주소가 클릭돼서 메일을 바로 보낼 수 있는 기능이 되야 의미가 있겠네

2023-08-13 06:35 UTC, hafnium1923 approved these changes

2023-08-13 10:22 UTC, wzrabbit approved these changes
수고하셨습니다

2023-08-13 10:22 UTC, merged