[BE] 팀공유링크 추가 조회 삭제 기능 구현
woowacourse-teams/2023-team-by-team pull request #473
Opened 2023-08-12 14:49 UTC by SproutMJ

## 이슈번호
#447
#448
#449

## PR 내용
# 이벤트 아직 안붙임

예외 상황
공통적으로 인증되지 않으면 401, 없거나 참여하지 않은 팀플레이스면 403
### 추가 시
정상: 201
공유링크 제목 또는 공유링크가 빈칸: 400
### 조회 시
정상: 200
### 삭제 시
정상: 204
존재하지 않음: 404
작성하지 않은 사용자인 경우: 403

## 참고자료

## 의논할 거리

2023-08-13 06:16 UTC, sh111-coder requested changes
작업 단위가 컸는데 빠르게 잘 작업해주셔서 감사합니다!! 짱짱

몇 부분 수정하면 좋을 사항이 보여서 코멘트 남기고 RC 하겠습니다!!
수정하시고 멘션주세요!!

2023-08-13 06:16 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
> +                softly.assertThat(successRequest.statusCode()).isEqualTo(HttpStatus.BAD_REQUEST.value());
예외 시에 예외 메시지도 검증하면 좋을 것 같아요!
토요일에 예외 처리부분 에러날 것 같다고 해서 안하신 걸까요??
그런 의도였다면 굿굿!

근데 나중에 예외 처리 컨플릭트 or 에러 해결할 때 에러 안나면 놓치고 진행할 수 있으니
지금 돌아가는 검증 (기존대로 isEqualTo)해서 추가하는게 좋다고 생각합니다!
이 부분은 필립과 상의 후 진행하면 좋을 것 같아요

2023-08-13 06:16 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
> +            final String invalidToken = "aaaa.bbbb.cccc";
이 부분 RefreshToken 작업 하면서 TokenFixtures에 잘못된 토큰 케이스별로 만들어놔서 해당 픽스쳐 사용해서 리팩토링하면 좋을 것 같습니다!

아래 테스트들도 모두 픽스쳐 사용하면 될 것 같습니다!

2023-08-13 06:52 UTC, pilyang requested changes
공유링크의 권한에 대한 이해와 생각이 서로 다른 부분이 있었던 것 같습니다.

해당 부분에 대해서 코멘트 남겼습니다.

1. 공유링크의 소유권은 등록한 사용자에게 있다.
2. 공유링크의 소유권은 등록된 팀에 있다.

엔델이 이해하기로는 1로 생각을 하여서 진행을 한 것 같네요. 그런데 공유링크 자체는 일정과 동일하게 팀플레이스에 종속된 것으로 생각을 해서 2번으로 생각을 하는게 좋을 것 같다는 생각이 듭니다.

공유링크에 작성한 사용자를 저장하고 보여주는것 또한 초기 기획회의에서는 없었는데, 프런트에서 보여주는 것이 좋을 것 같다고 하여 보여주는 쪽으로 변경하면서 해당데이터도 추가를 하게 된 것이여서, 더욱 2번으로 생각하는게 기획과 좀 더 가깝게 되지 않을까 합니다.

만약에 2번으로 생각하고 변경을 한다면 삭제시 403예외가 발생되는 기준이 해당 멤버와 링크의 작성자가 아닌 요청이 들어온 팀플레이스와 링크 사이의 관계에 따라 해당 팀플레이스의 링크가 아닐 때 발생되게 하는것으로 해야할 것 같습니다.

2023-08-13 06:52 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/SharedLink.java
> +    }
서비스 코드에서 커멘트를 남긴대로라면 Owner에 대한 검증이 멤버가 아닌 팀플레이스로 될 것 같네요!

혹시라도 누가 작성한것인지에 대한 검증이 필요하다면 validateWriter validateAuthor 정도로 유지해도 될 것 같습니다

2023-08-13 06:52 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/presentation/SharedLinkController.java
> +    }
커멘트로 남긴것처럼 만약에 링크수정을 팀플레이스를 통해서만 권한 확인을 한다면 멤버이메일디티오도 안가져와도 될 것 같네요

2023-08-13 06:52 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
> +        return sharedLinkResponses;
해당 부분 좀 더 가독성 좋아지면 좋을 것 같네요..ㅎㅎ

스케쥴은 사용자에 대한 정보가 없었어서, 사용자에 대한 정보가 있는 NoticeService에서 작성했던 예시 아래 작성해두겠습니다.

NoticeService 에서 코드 확인해보면 참고 될 것 같습니다..ㅎㅎ

```java
private NoticeResponse mapToNoticeResponse(final Notice notice) {
        final MemberTeamPlace memberTeamPlace = memberTeamPlaceRepository.findById(notice.getAuthorId())
                .orElse(MemberTeamPlace.UNKNOWN_MEMBER_TEAM_PLACE);
        return NoticeResponse.of(notice, memberTeamPlace);
    }
```

참고로 위에는 지금 엔델이 develop브랜치 최신 상태로 적용이 안되어 있어서 엔델 코드로 체크아웃 한 상태에서 복붙해서 그런거고,, 지금 develop코드는 아래와 같습니다.. 아래 코드에서 확인하거나 최신 develop브렌치에서 확인해주세요ㅎㅎ 위에코드처럼 하면 오류나요..ㅠㅜㅋㅋㅋ

```java
private NoticeResponse mapToNoticeResponse(final Notice notice) {
        final MemberTeamPlace memberTeamPlace = memberTeamPlaceRepository.findById(notice.getAuthorId())
                .orElse(MemberTeamPlace.UNKNOWN_MEMBER_TEAM_PLACE);
        return NoticeResponse.of(notice, memberTeamPlace);
    }
```

2023-08-13 06:55 UTC, pilyang commented
+ 중간에 테스트 오류가 생길수도 있고 해서 가끔씩 메인브랜치에 적용된 최신 코드들 머지해서 코드 최신상태로 유지해도 좋을 것 같아요...ㅎ
지금은 좀 이전상태 코드들이 베이스로 되어있는것 같았어서요

2023-08-13 07:42 UTC, the9kim reviewed
엔델!!

주말에 작업하시느라 고생 많으셨습니다!!

필립과 성하가 남긴 피드백 외에 제 의견을 남겨봤습니다!

엔델이 취사 선택해서 반영해주시면 좋을 듯 해요!

2023-08-13 07:42 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/SharedLink.java
> +    private Long id;
혹시 클래스에 final 붙은 이유가 있으실까요?? 궁금해서 여쭙습니다!

2023-08-13 07:42 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
> +        return sharedLinkResponses;
저 또한 
링크 조회에 대한 반환값으로 List<SharedLinkResponse>인 것 보다는,

SharedLinksResponse가 바로 나가는 것이 좋다고 생각합니다. 

가독성이나 기존 코드와의 통일성 측면에서 더 낫지 않나 싶네요!

2023-08-13 07:42 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
> +        sharedLink.validateOwner(member);
흠 저도 의견을 덧붙이자면,
팀원들도 삭제할 수 있는 방식이 좀 더 괜찮을 듯 합니다!

2023-08-13 07:42 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/exception/SharedLinkException.java
> +        public URLException() {
개인적인 생각입니다만,

위 성하의 피드백(TitleBlankException)을 반영한다고 가정하면

해당 메서드 또한 UrlBlankException으로 바꿔도 괜찮을 듯 합니다!

2023-08-13 07:42 UTC, the9kim commented on backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
> +                softly.assertThat(sharedLinksResponse.teamLinks().get(0).title()).isEqualTo("title");
얼마 전 Response 내 하나의 필드값만 검증하다 보니, 테스트가 에러를 걸러내지 못한 경우가 있었던 것으로 기억합니다!

이왕 검증하는 김에 title 뿐만 아니라 URL도 같이 검증하는 방식도 좋을 듯 합니다!

2023-08-13 15:03 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
> +    public Long create(MemberEmailDto memberEmailDto, final Long teamPlaceId, final @Valid SharedLinkCreateRequest sharedLinkCreateRequest) {
오 그렇군요

2023-08-13 15:20 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
> +        sharedLink.validateOwner(member);
적용갑니다~~

2023-08-13 15:51 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/SharedLinkRepository.java
> +    List<SharedLink> findByTeamPlaceId(final Long teamPlaceId);
변경했습니다.

2023-08-13 15:53 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/exception/SharedLinkException.java
> +    }
포함해서 URLException도 변경했습니다.

2023-08-13 15:54 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
> +    public Long create(MemberEmailDto memberEmailDto, final Long teamPlaceId, final @Valid SharedLinkCreateRequest sharedLinkCreateRequest) {
적용했습니다.

2023-08-13 16:09 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
> +        return sharedLinkResponses;
적용했습니다.

2023-08-13 16:22 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
> +            final SharedLinkCreateRequest sharedLinkCreateRequest = new SharedLinkCreateRequest("title", "/");
적용했습니다.

2023-08-13 16:32 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
> +            final String invalidToken = "aaaa.bbbb.cccc";
적용했습니다.

2023-08-13 16:36 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
> +    }
sharedLink.validateOwnerTeamPlace(teamPlaceId);
을 해서 
인터셉터에서 사용자가 팀플레이스의 소속인지 검증
service 계층에서 공유링크가 팀플레이스의 소속인지 검증하도록 했습니다.
예시의 1번에 가까운 것 같네요

2023-08-13 16:37 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/SharedLink.java
> +    }
sharedLink.validateOwnerTeamPlace(teamPlaceId); 로 팀플레이스만 검증하도록 변경했습니다.

2023-08-13 16:37 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/presentation/SharedLinkController.java
> +    }
이제 안가져옵니다.

2023-08-13 16:38 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/SharedLink.java
> +    private Long id;
저는 자동으로 붙습니다. 원래 final 붙이면 좋긴 한데 지금 하나도 없어서 일관성을 위해 제거했습니다.

2023-08-13 16:39 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/exception/SharedLinkException.java
> +        public URLException() {
동일하게 변경했습니다.

2023-08-13 18:23 UTC, SproutMJ commented
여기까지 리뷰하신 내용입니다.

2023-08-13 18:24 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
> +                softly.assertThat(successRequest.statusCode()).isEqualTo(HttpStatus.BAD_REQUEST.value());
확실히 로깅할 때 한번에 하는 것이 낫겠네요

2023-08-14 04:37 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
> +                softly.assertThat(sharedLinksResponse.teamLinks().get(0).title()).isEqualTo("title");
````java
assertSoftly(softly -> {
                softly.assertThat(successRequest.statusCode()).isEqualTo(HttpStatus.OK.value());
                softly.assertThat(sharedLinksResponse.teamLinks().size()).isEqualTo(1);
                softly.assertThat(sharedLinksResponse.teamLinks().get(0).title()).isEqualTo("title");
                softly.assertThat(sharedLinksResponse.teamLinks().get(0).url()).isEqualTo("/");
            });
````
이런식으로 변경했습니다.

2023-08-14 04:38 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
> +            final SharedLinkCreateRequest sharedLinkCreateRequest = new SharedLinkCreateRequest("title", "/");
대부분 픽스처를 만들어서 했는데요 일부 request body는 바로 인자를 보여주는게 나을거같아서 즉시 만드는걸로 해봤습니다.

2023-08-14 06:41 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
> +            final SharedLinkCreateRequest sharedLinkCreateRequest = new SharedLinkCreateRequest("title", "/");
"/" URL을 정상 URL로 수정하는 부분이 반영 안된 것 같아요!

2023-08-14 06:51 UTC, sh111-coder requested changes
이벤트까지 큰 작업 하느라 고생 하셨습니다! 굿굿
대부분 잘 해주셨는데 
반영 안된 부분 하나랑  알림에서 수정하면 좋을 사항 코멘트로 남겼어요!
반영 해주시면 Approve 하겠습니다!

2023-08-14 06:51 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/feed/application/NotificationServiceTest.java
> +            assertThat(feeds.get(0)).usingRecursiveComparison()
usingRecursive 좋네요!

2023-08-14 06:51 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/sharedlinknotification/SharedLinkNotificationContentGenerator.java
> +        final String content = String.format("'%s'[%s] 공유링크가 등록되었습니다.", title, url);
공유 링크 등록 알림에 URL까지 들어가면 피드가 조금 어지러울 것 같아서 URL은 빼는게 좋을 것 같아요!

2023-08-14 06:53 UTC, pilyang requested changes
컨벤션적인 부분도 좀 있고, 해당 부분만 있었으면 그냥 진행해도 될 것 같았는데, 예외메시지 부분에서 추가해야 할 내용들이 있어서 반영하면서 컨벤션도 맞춰주면 좋을 것 같습니다.

2023-08-14 06:53 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/dto/SharedLinkResponse.java
> +        return new SharedLinkResponse(sharedLink.getId(), sharedLink.getTitle().getValue(), sharedLink.getSharedURL().getValue(), sharedLink.getMemberId(), memberTeamPlace.getDisplayMemberName().getV
이런부분들은 개행 해서 가독성 높여주면 좋을 것 같습니다.

코드 확인할때 순서확인하면서 옆으로 넘기면서 보려니까 힘드네요.

2023-08-14 06:53 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
> +
컨벤션으로는 `.toList`는 다음 줄에 적는게 좋을 것 같습니다.

2023-08-14 06:53 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/SharedLink.java
> +    }
저희가 예외에서 예외 상황에 대한 정보를 담기로 결정했어서, 해당 예외는 아래와 같이 던져주는것이 좋을 것 같습니다.

```java
throw new SharedLinkException.OwnerForbiddenException(this.id, teamPlaceId);
```

그러면 예외메시지에서는 아래와 같이 표기될 수 있을 것 같습니다.

`요청 권한이 없는 공유링크입니다. - request info { shared_link_id : id, team_place_id : id }`

메시지에 대한 형식은 다른 예외들 참고하면 될 것 같습니다.

2023-08-14 06:53 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
> +        sharedLink.validateOwnerTeamPlace(teamPlaceId);
해당 부분의 예외에서는 요청이 들어온 sharedLinkId의 정보를 예외메시지에 추가 해 줄 수 있을 것 같네요.

2023-08-14 06:53 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/exception/SharedLinkException.java
> +}
다른 코멘트에서 남긴것과 같이 해당 예외들은 요청에 대한 정보를 담을 수 있을 것 같서 코멘트 남겨두었습니다.

해당 부분들 반영해주시면 좋을 것 같습니다. 예외메시지 형식이나 남기는 방법들은 전에 작업되어있는 다른 코드들 참고하면 됩니다.

2023-08-14 06:53 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
> +            });
위에 성하가 남긴것같은데, 예외메시지 검증을 추가하는것이 좋아보입니다.
예외메시지 검증을 추가하지 않을거라면 assertSoftly를 사용하지 말고 그냥 assertThat으로 검증하면 될 것 같습니다.

2023-08-14 07:34 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
> +            });
로깅에 한번에 추가될 예정입니다

2023-08-14 07:34 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/exception/SharedLinkException.java
> +}
로깅에 한번에 추가될 예정입니다

2023-08-14 07:35 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/SharedLink.java
> +    }
로깅에 한번에 추가될 예정입니다 그때 한번더 확인해주시면 감사하겠습니다!!!!

2023-08-14 07:38 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
> +        sharedLink.validateOwnerTeamPlace(teamPlaceId);
로깅에 한번에 추가될 예정입니다 그때 한번더 확인해주시면 감사하겠습니다.

2023-08-14 07:38 UTC, SproutMJ commented
아래부터 추가 리뷰 반영입니다.

2023-08-14 07:40 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
> +
날카로우시군요

2023-08-14 07:41 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/sharedlink/application/dto/SharedLinkResponse.java
> +        return new SharedLinkResponse(sharedLink.getId(), sharedLink.getTitle().getValue(), sharedLink.getSharedURL().getValue(), sharedLink.getMemberId(), memberTeamPlace.getDisplayMemberName().getV
, 단위로 개행했습니다.

2023-08-14 07:41 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/sharedlinknotification/SharedLinkNotificationContentGenerator.java
> +        final String content = String.format("'%s'[%s] 공유링크가 등록되었습니다.", title, url);
아쉽군요 제거할게요

2023-08-14 07:41 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/feed/application/NotificationServiceTest.java
> +            assertThat(feeds.get(0)).usingRecursiveComparison()
베낀겁니다

2023-08-14 08:03 UTC, pilyang approved these changes
로깅이랑 메시지에 대해서는 슬랙메시지 확인했습니다. 나머지 분들 확인되면 머지 시키고 pr올려주셔요

2023-08-14 08:03 UTC, sh111-coder approved these changes
Approve 하겠습니다!!! 굿굿

2023-08-14 08:04 UTC, merged