[BE] url base64 디코딩 문제 해결
woowacourse-teams/2023-team-by-team pull request #572
Opened 2023-08-19 14:34 UTC by SproutMJ

## 이슈번호
없음

## PR 내용
url base64 디코딩 시 발생하는 문제 해결
주의: 안되면 다시해야됨

## 참고자료

## 의논할 거리

2023-08-19 14:44 UTC, pilyang approved these changes
와우 빠른 확인 감사합니다!!!

url인코딩 디코딩 더 공부해봐야겠네요

2023-08-19 14:44 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
> +                .get(key);
오 base64 인코딩, 디코딩시 url safe하게 하는게 따로 있었네요,....!!!

빠르게 찾아보고 수정해줘서 감사합니다!!!

2023-08-20 01:14 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
> +                .get(key);
이 부분 저도 처음 알았네요,,, 대박
감사합니다 엔델

2023-08-20 01:14 UTC, sh111-coder approved these changes
빠르게 처리해주셔서 감사합니다!!
아마 이렇게 하면 되지 않을까요?? (Flag)

2023-08-20 02:04 UTC, sh111-coder requested changes
좀 더 공부해보다가 고칠 부분 찾아서 코멘트 남겨놓겠습니다!
수정해야 할 것 같아요!

2023-08-20 02:17 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
> +                .get(key);
공부를 좀 해보니 에러가 발생한 원인을 알 것 같아요! 여기 코멘트에 자세하게 달겠습니다!

저희가 구글 IdToken을 받아서 해당 JWT Token의 PayLoad를 디코딩해서 사용하잖아요!
그래서 찾아보니 공식문서에 아래와 같이 나와있었습니다!
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/95729738/67738a15-d2a8-4f07-bb09-69c8a4170506)
보면 ID 토큰은 `Base64`가 아닌 `Base64Url` 인코딩을 거치는 것을 알 수 있습니다!
공식문서 링크도 첨부합니다!
위 부분은 3.1.3.6 목차에 있습니다!
[OpenID Connect Core 1.0 incorporating errata set 1](https://openid.net/specs/openid-connect-core-1_0.html#IDToken)

그래서 `Illeagal baset64 Character 2d` 문제가 발생했던 원인은
구글 ID 토큰이 Base64Url로 인코딩해서 오는데 Base64로 디코딩해서 발생하는 문제 같습니다!

Base64와 Base64Url의 차이는 변환표의 62, 63번 인덱스가 다른 걸 알 수 있었습니다.
[Base64와 Base64Url의 차이](https://seahrin.com/entry/Base64-Encoding-%EC%99%80-Base64Url-Encoding-%EA%B3%BC%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90)

그래서 일부 사용자만 오류가 발생했던 이유가 인코딩된 문자열 중에 '-' 나 '_'는 Base 64로는 디코딩할 수 없기 때문에
에러가 발생한 것 같아요!

결론적으로, googleIdToken 전체를 Base64가 아닌 Base64Url로 디코딩 해야할 것 같습니다!
(지금은 picture만 하고 있는데, 나머지 키에 대해서도 다 Base64Url로 인코딩되어 있어서)

그래서 다음과 같이 수정하면 어떨까 싶어요!





```suggestion
    private OAuthMember createOAuthMember(final String googleIdToken) {
        Map<String, Object> payLoadMap = getPayLoadMap(googleIdToken);
        String email = (String) payLoadMap.get("email");
        String rawName = (String) payLoadMap.get("name");
        String picture = (String) payLoadMap.get("picture");

        if (rawName.length() > Name.MAX_LENGTH) {
            final String substringName = rawName.substring(NAME_BEGIN_INDEX, Name.MAX_LENGTH);
            return new OAuthMember(email, substringName, picture);
        }
        return new OAuthMember(email, rawName, picture);
    }

    private Map<String, Object> getPayLoadMap(final String googleIdToken) {
        String payLoad = googleIdToken.split("\\.")[PAYLOAD_INDEX];
        String decodedPayLoad = new String(Base64.getUrlDecoder().decode(payLoad));
        JacksonJsonParser jacksonJsonParser = new JacksonJsonParser();
        Map<String, Object> payLoadMap = jacksonJsonParser.parseMap(decodedPayLoad);
        return payLoadMap;
    }
```

2023-08-20 02:19 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
> +                .get(key);
음.. Suggestion 뺄 부분이 잘못 선택해서 이상하게 되긴 했는데 뭔 말인지 알죠?!!

2023-08-20 02:53 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
> +                .get(key);
성하가 추천해준 코드에서

```java
Map<String, Object> payLoadMap = jacksonJsonParser.parseMap(decodedPayLoad);
```

이부분 아래처럼 바꿀 수 있을 것 같아요.

```java
return jacksonJsonParser.parseMap(payload)
                .entrySet()
                .stream()
                .collect(Collectors.toMap(Map.Entry::getKey, e -> (String) e.getValue()));
```

그러면 해당 맵 사용하는 부분에서 매번 String으로 변환 안해도 될 것 같습니다.

2023-08-20 05:28 UTC, sh111-coder approved these changes
고생하셨습니다!!! ㅎㅎㅎ

2023-08-20 05:49 UTC, merged