[BE] 팀플레이스 색상 변경 기능 / 문서화 구현
woowacourse-teams/2023-team-by-team pull request #590
Opened 2023-08-31 12:55 UTC by sh111-coder

## 이슈번호
> close #588 #589 

## PR 내용
- 팀 플레이스 색상 변경 기능 / 문서화 구현
 - `TeamPlaceColor` ENUM에서 ColorNumber에 해당하는 색상 찾아서 반환하는 기능 추가
   -  색상 번호에 해당하는 TeamPlaceColor가 없다면 커스텀 예외 발생해서 Handler에서 400으로 처리하도록 구현
  - API URI가 `/api/team-places/{teamPlaceId}/color` 이므로 TeamPlaceController가 존재하는 TeamPlace 패키지(TeamPlaceService)에서 구현

## 참고자료

## 의논할 거리

2023-09-01 06:21 UTC, pilyang requested changes
final만 한번 확인해주시면 될 것 같아요..ㅎㅎ

2023-09-01 06:21 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
> +        TeamPlaceColor findTeamPlaceColor = TeamPlaceColor.findTeamPlaceColor(request.teamPlaceColor());
`final`이 좀 많이 빠져있네요 ^^

2023-09-01 06:21 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/member/domain/TeamPlaceColor.java
> +    }
이런 경우 `static map` 으로 미리 만들어두고 매번 스트림을 안돌리는 방법 같이 이야기 했었는데, 해당 메서드 (api)요청이 많지 않을것이라 생각해서 매번 stream을 돌려도 될것같다는 생각에는 동의해서 전 해당 방식도 상관없을것 같긴 합니다.

혹시 다른분들은 해당 부분에 대한 다른 의견 있으면 같이 의견 나눠도 좋을 것 같아요.

2023-09-01 06:25 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
> +        TeamPlaceColor findTeamPlaceColor = TeamPlaceColor.findTeamPlaceColor(request.teamPlaceColor());
수정했습니다!! ㅎㅎ;;; 😂

2023-09-01 06:27 UTC, pilyang approved these changes
확인 했습니다!!

2023-09-01 09:01 UTC, SproutMJ approved these changes
코드를 정말 잘 작성해주셔서 감사합니다.

2023-09-02 06:51 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/member/domain/TeamPlaceColor.java
> +    }
성능에는 크게 지장이 없는 듯 하여 이대로도 괜찮을 것 같습니다!

2023-09-02 06:53 UTC, the9kim commented on backend/src/test/java/team/teamby/teambyteam/member/domain/TeamPlaceColorTest.java
> +}
세심한 테스트 굿입니다!

저는 valueSource로 테스트 할 때,

파라미터(int notExistColorNumber)에는 final을 못붙이는 줄 알았는데, 알고보니 가능 하더라구요!

수정사항은 아니고 그냥 참고하시면 좋을 듯합니다!

2023-09-02 06:58 UTC, the9kim approved these changes
빠르고 신속하게 구현해주셨네요!

그에 반에 제 리뷰가 늦어서 죄송합니다ㅠ

특별히 수정사항은 없는 듯 하여 approve 하겠습니다!

2023-09-02 06:58 UTC, the9kim commented on backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
> +        @DisplayName("만료된 토큰으로 요청을 보내면 실패한다.")
토큰에 대한 예외처리를 꼼꼼하게 해주셨네요.

굿입니다 굿!

2023-09-02 07:22 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/member/domain/TeamPlaceColorTest.java
> +}
빼먹었네요!!! 감사합니다 ㅎㅎㅎ 수정하고 머지할게요!

2023-09-02 07:37 UTC, merged