[BE] 회원 탈퇴 api 구현
woowacourse-teams/2023-team-by-team pull request #601
Opened 2023-09-01 06:21 UTC by SproutMJ

## 이슈번호
#591 

## PR 내용
회원 탈퇴 api
회원 없을 시 404 에러
회원 탈퇴 시 팀플레이스 모두 탈퇴
회원 탈퇴시 즉시 회원 정보 삭제(기타 기록은 삭제되지 않음)

## 참고자료

## 의논할 거리

2023-09-01 06:59 UTC, sh111-coder requested changes
테스트 부분 인증 파트 보강하면 될 것 같습니다!!
수고하셨어요 ㅎㅎㅎ

2023-09-01 06:59 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
> +    class DeleteAccount {
401 인증 실패 테스트 (만료 토큰, 잘못된 형식 토큰, 이메일 클레임 누락 토큰 요청) 추가해야 할 것 같아요!

2023-09-01 08:48 UTC, pilyang approved these changes
cascade옵션이 있어서 잘 적용이 되게 바로 개발완료된것 같네요.

회원 탈퇴시 팀플레이스 탈퇴 테스트등 기능적으로 필요한 테스트는 잘 되어있다고 생각해서 approve 할께요

2023-09-02 07:03 UTC, the9kim approved these changes
수고많으셨습니다 엔델!!

2023-09-04 03:59 UTC, sh111-coder approved these changes
수고하셨습니다! 인증 테스트는 1개로 아쉽지만 ^^

2023-09-04 03:59 UTC, merged