[FE] 회원 정보 수정 기능 구현
woowacourse-teams/2023-team-by-team pull request #603
Opened 2023-09-01 07:24 UTC by suyoungj

# [FE] 회원 정보 수정 기능 구현
## 이슈번호
> close #579, close #580

## PR 내용
- 회원 정보 수정 기능 구현
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/001b2823-f468-4472-8f43-4c04cebfd6ee)
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/875af574-f356-4b83-97d8-dcfab1a24a23)

2023-09-04 02:17 UTC, hafnium1923 requested changes
굿

2023-09-04 02:17 UTC, hafnium1923 commented on frontend/src/components/user/UserInfoModal/UserInfoModal.tsx
> +    userInfo,
개인적인 생각으로는 useInfo는 기존처럼 userInfoModal안에서 불러오는게 더 자연스러워 보여! useUserInfoModal훅 안에서 해당 정보가 사용되고 있긴 하지만 userInfoModal에서 보여주는 핵심 정보니까 userInfoModal에서 데이터를 불러올 거라고 예상되거든. 그렇지만 유스가 useUserInfoModal에 넣은 이유는 알 것 같애!

2023-09-04 02:17 UTC, hafnium1923 commented on frontend/src/hooks/user/useUserInfoModal.ts
> +  const handleContainerClick: MouseEventHandler<HTMLDivElement> = (e) => {
얘는 편집 도중 다른 곳을 누르면 편집이 막히게 하려고 한거지? 그러면 내 생각엔 프로필 사진을 눌러도 편집이 닫히는게 좋을 것 같아. 밖을 누르면 일관성있게 편집히 막히는게 사용자가 예측하기 쉽다는 생각이거든

2023-09-04 05:48 UTC, wzrabbit requested changes
수고했습니다! 코멘트 확인해 주면 고맙겠으

2023-09-04 05:48 UTC, wzrabbit commented on frontend/src/apis/user.ts
> +};
유저 프로필 변경사항을 `patch` 하는 로직이 `/user` 에 있다면, `/auth` 에 있는, 유저 프로필을 `get` 하는 로직 또한 `/user` 로 두면 좋겠다는 생각을 했는데, 유스는 어떻게 생각해?

유저 정보를 불러오는 것, 유저 정보를 수정하여 반영하는 것. 모두 `/user` 주제에 속하는 로직이라 생각하고 있어.마침 `msw` 에서도 두 로직을 한 파일에 묶고 있고.

2023-09-04 05:48 UTC, wzrabbit commented on frontend/src/hooks/user/useUserInfoModal.ts
> +  const handleContainerClick: MouseEventHandler<HTMLDivElement> = (e) => {
나도 동의~ 프로필 사진도 인풋 바깥이라 생각되기에 프로필 사진 눌러도 편집 취소 되게 하면 유저 입장에서 좀 더 예측하기 쉬운 UI 되고 좋을듯

2023-09-04 05:48 UTC, wzrabbit commented on frontend/src/hooks/user/useUserInfoModal.ts
> +      { name },
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/3454945b-2326-40d6-97b0-342770edff97)

현재 닉네임이 비어있지만 않으면 공백으로만 구성되어 있을 때 통과하는데, 백엔드에서는 이 경우를 오류로 간주하거든, 공백을 제외한 글자가 0글자라서.

백엔드에서도 검증을 하지만 프론트엔드에서도 검증이 필요한 것 같아서, 아래의 조건을 모두 만족해야만 요청이 되도록 로직을 개선하면 좋겠어!

- 닉네임은 앞뒤의 공백을 제외했을 때 1글자 이상 20글자 이하여야 한다.

2023-09-08 05:06 UTC, suyoungj commented on frontend/src/components/user/UserInfoModal/UserInfoModal.tsx
> +    userInfo,
자연스러운건 나도 동의해! 근데 `handleSubmit`에서 `userInfo`를 사용하다보니 커스텀 훅으로 분리하려면 어쩔 수 없더라고..
그래서 커스텀 훅 안에서 필요한 데이터를 전부 불러오는 방식으로 작성했어

2023-09-08 08:46 UTC, wzrabbit commented on frontend/src/hooks/user/useUserInfoModal.ts
> +  const handleContainerClick: MouseEventHandler<HTMLDivElement> = (e) => {
<img src="https://user-images.githubusercontent.com/87642422/233828081-bec1bb8b-7c29-4fac-8c67-0c84bb814ee2.png" width="35px" />
이제 작동 잘 되네

2023-09-08 08:55 UTC, wzrabbit requested changes

2023-09-08 08:55 UTC, wzrabbit commented on frontend/src/hooks/user/useUserInfoModal.ts
> +      { name },
HTML 단에서 사용자의 입력을 막는 것 뿐만 아니라 요청 전에도 추가 검증을 하는 건 어떨까?

![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/c1661f9e-06b1-4533-b654-15e956a594e9)

Ex)
```tsx
const name = nameInput.value.trim();

// 여기서부터 추가된 내용
if (name.length > 20) {
  showToast('error', '닉네임은 1글자 이상 20글자 이하여야 합니다.');
  return;
}
// 여기까지 추가된 내용

if (name === '' || name === userInfo?.name) {
  setIsUserInfoEditing(() => false);
  return;
}
```

2023-09-08 08:55 UTC, wzrabbit commented on frontend/src/components/user/UserInfoModal/UserInfoModal.tsx
> +                placeholder={name}
닉네임의 중간에 공백이 2칸 이상 들어갔을 때, 여기서 랜더링될 때는 공백이 1칸으로 나오는 문제가 있는 것 같아 보여.
예를 들면 `Yo   u th` 가 닉네임일 때 `Yo   u th` 가 아닌 `Yo u th` 가 랜더링되고 있어.

나도 이 문제를 해결해 보고 싶어서 검색해 본 결과 `white-space` 를 `pre-wrap` 으로 바꾸면 공백 문제를 해결할 수 있지만, `white-space: nowrap` 을 사용하지 못 하기에 `ellipsis` 를 더 이상 적용할 수 없는 것 같네...

해결 방법이 있으면 좋겠지만, 지금 문제만 봤을 때 나도 해결 방법을 잘 모르겠더라.
여기는 일단 넘어갈게. 혹시나 유스가 해결 방법을 찾았다면, 공유해 주면 좋을듯?

2023-09-08 08:56 UTC, hafnium1923 reviewed
질문 하나만 답변 부탁드려요!

2023-09-08 08:56 UTC, hafnium1923 commented on frontend/src/components/user/UserInfoModal/UserInfoModal.tsx
> +    userInfo,
아 어차피  useUserInfoModal();는 userInfoModal에 종속적이니까 
 useUserInfoModal(userInfo);
이 방식을 말한거긴 했어.
이 방식은 어떤 이유로 별로라고 생각했는지 궁금해!

2023-09-12 04:41 UTC, suyoungj commented on frontend/src/components/user/UserInfoModal/UserInfoModal.tsx
> +                placeholder={name}
`white-space: pre`로 일단 해결했어!

2023-09-12 04:46 UTC, hafnium1923 approved these changes
수고하셨슴둥

2023-09-12 05:02 UTC, wzrabbit approved these changes
![blobsip](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/cad39a59-c42b-4d9f-bec0-b2bf2d4e152d)

2023-09-12 05:02 UTC, merged