[BE] 회원정보 수정 기능 구현
woowacourse-teams/2023-team-by-team pull request #609
Opened 2023-09-01 13:04 UTC by the9kim

## 이슈번호
> #595 

## PR 내용
- 회원의 본인 정보(이름) 수정 기능 구현 및 테스트
  - 회원의 변경 전 이름과 DisplayName 일치 시 -> DisplayName을 새로운 이름으로 변경
  - 회원명의 앞뒤에 공백이 있을 경우 해당 공백을 제거(Trim)

## 참고자료

## 의논할 거리
- member 이름과 DisplayName의 일치할 경우 DisplayName을 변경하는 로직에서 indent Depth가 2임
```
for (final MemberTeamPlace memberTeamPlace : memberTeamPlaces) {
    if (memberTeamPlace.getDisplayMemberName().getValue().equals(member.getName().getValue())) {
        memberTeamPlace.changeDisplayMemberName(new DisplayMemberName(memberUpdateRequest.name()));
    }
}
```
- stream 사용할 경우 foreach로 메서드를 실행해야하는 문제가 있어 적용의 어려움 발생
- 해당 코드를 리팩터링 할 방법이 있을지?

2023-09-01 17:03 UTC, pilyang requested changes
전반적으로 잘 구현해주신것같아요!!

다만 서비스에있는 로직을 도메인으로 이동시키면 좋을것 같은 부분과, 정상작동시킬 수 있을 것 같지만 예외가 터지게 되는 부분이 있어서 해당 부분에 커멘트 남겼습니다!

확인 부탁드립니다!

2023-09-02 00:10 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
> +        }
저도 동의합니다!

2023-09-02 00:30 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
> +    }
이 부분 메소드 네이밍이 `change`면 멤버의 모든 요소(Name, Email, ProfileImageUrl)가
바뀐다고 생각이 들 것 같아서 `changeName`으로 특정해주시면 좋을 것 같아요!

나중에 오버로딩으로 나머지 요소 바꾸는 메소드를 확장한다고 하면 괜찮을 것 같은데
하나만 있을 때는 좀 오해할 수 있을 것 같습니다!

오버로딩을 고려하고 하신 거라면 놔둬도 괜찮을 것 같긴 한데 로이의 판단에 맡기겠습니다!

2023-09-02 00:30 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
> +        final List<MemberTeamPlace> memberTeamPlaces = member.getMemberTeamPlaces();
필립이 말한 if문 로직 뿐만 아니라 member.getMemberTeamPlaces() + for문 로직도 도메인(Member)으로 이동하면 좋을 것 같습니다!
Member가 List<MemberTeamPlace>를 가지고 있기 때문에 
Member가 속한 팀플레이스의 보일 이름 변경을 도메인 로직으로 가져가는게 좋을 것 같습니다!
(서비스보단 도메인에 로직을 넣자! 라는 초반 컨벤션이기도 하고요!)

2023-09-02 00:30 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Name.java
>      }
동의합니다!! 👍🏻

2023-09-02 00:43 UTC, sh111-coder requested changes
이전 Review가 잘못 Submit됐네요!!
코멘트들 확인해주세요!!

비즈니스 로직 꼼꼼하게 잘 짜주신 것 같아요!
(기존 사용자명이 DisplayName과 다를 경우 DisplayName이 변경되지 않는 로직까지 Good!!)

Service 비즈니스 로직 부분이랑 Service Test, Acceptance Test 부분에서
수정 사항 코멘트로 남겼습니다!!
반영되면 바로 Approve 할게요!

2023-09-02 00:43 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
> +    class updateMemberInformation {
이 부분 노션 문서에 400 404 Status Code는 빠져있어서 제가 추가하겠습니다!

2023-09-02 00:43 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
> +        void successWithTrimmedMemberNameToUpdate(final String nameToUpdate) {
이 부분은 VO Test(NameTest)에서 검증할 내용이라고 생각하고, 
이미 NameTest에서 잘 해주셔서 
비즈니스 로직을 테스트하는 Service Test에서는 안 해도 된다고 생각합니다!

밑에 NameTest와 중복되는 부분은 마찬가지로 안 해도 된다고 생각합니다!!

2023-09-02 00:43 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
> +    class updateMemberInformation {
여기서 Service Test에서 안해도 됐다고 생각했던 NameTest 부분을 추가해야 할 것 같아요!
(20자 초과 시 실패, 공백 포함 입력 시 공백 제거하고 변경)

2023-09-02 06:56 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
> +        final List<MemberTeamPlace> memberTeamPlaces = member.getMemberTeamPlaces();
오 저도 이부분 성하 의견에 동의합니다!! 최대한 도메인으로 기능들을!

2023-09-02 07:38 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Name.java
>      }
흠 경우의 수를 꼼꼼하게 따지지 못했군요!!

null 체크 -> trim -> validate

로직으로 변경해봤습니다!

2023-09-02 07:40 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
> +    }
사용자 정보 변경이 '이름'에 한정되는 만큼

메서드를 명시적으로 바꾸는 게 좋겠네요!

좋은 지적 감사합니다!

2023-09-05 02:10 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
> +        }
너무 좋은 지적입니다!

말씀하신 로직을 도메인에서 담당하도록 변경했습니다!

2023-09-05 02:11 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
> +        final List<MemberTeamPlace> memberTeamPlaces = member.getMemberTeamPlaces();
성하도 너무 좋은 지적 해주셨네요ㅎㅎ

말씀하신 로직을 도메인으로 옮겨봤습니다!

2023-09-06 06:50 UTC, the9kim commented on backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
> +        void successWithTrimmedMemberNameToUpdate(final String nameToUpdate) {
해당 메서드 삭제 완료 했습니다!

2023-09-06 06:50 UTC, the9kim commented on backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
> +    class updateMemberInformation {
해당 테스트도 추가 완료했습니다!

2023-09-06 06:55 UTC, SproutMJ approved these changes
전에 크루분들이 리뷰를 잘 남겨주셔서 깔끔한 코드가 된 것 같아요!!!

2023-09-06 07:01 UTC, pilyang requested changes
리뷰 반영해주셔서 감사합니다!

다만 도메인 메소드를 2개의 퍼블릭메소드로 분리해서 사용하는 사람이 그 숫서를 맞춰서 사용해야만 잘 작동하게 하는것이 괜찮을까 하는 의문이 들어서 해당 부분에 대한 코멘트 남겼습니다.

확인 부탁드립니다!!

다른분들의 의견도 들어보고, 만약에 지금처럼 2개의 메서드로 구분해서 호출하는것이 좋다고 생각되는 이유가 있다면 남겨주시면 감사하겠습니다.

2023-09-06 10:40 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
> +    }
동의합니다!!!

2023-09-06 10:41 UTC, sh111-coder approved these changes
수정 사항 잘 반영해주셔서 Approve합니다!!
수정 사항 많았을텐데 고생하셨습니다!! 👍🏻👍🏻👍🏻👍🏻

2023-09-06 10:48 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
> +    }
생각해보니 굳이 파라미터를 전달하지 않아도 Name - DisplayName을 비교할 수 있었네요!

좋은 지적 감사합니다. 2번째 방향으로 수정했습니다!

2023-09-06 10:55 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
> +        for (final MemberTeamPlace memberTeamPlace : this.memberTeamPlaces) {
말씀을 듣고 보니, 서비스 레이어에서 '멤버 이름을 바꾸는 로직'과 'DisplayName을 바꾸는 로직'을 굳이 구분할 필요가 없을 듯하네요.

수정 사항은 다음과 같습니다.

1. (서비스 레이어) 호출되는 멤버 이름 수정 메서드를 하나로 통일
2. (Member) DisplayName 수정 메서드 접근제한자 private 변경 후 -> Member Name 수정 메서드 내에서 호출
3. 디스플레이명 변경 메서드 네이밍 수정( changeDislplayName -> changeAllDefaultDisplayName)

2023-09-08 04:59 UTC, pilyang approved these changes
내용 반영된거 확인했습니다!!

2023-09-08 06:27 UTC, merged