[BE] MemberInterceptor 예외 401로 변경 + 인증 예외 로깅 리팩토링
woowacourse-teams/2023-team-by-team pull request #614
Opened 2023-09-04 08:40 UTC by sh111-coder

## 이슈번호
> 해당되는 모든 번호를 태그해주세요

## PR 내용
* MemberInterceptor 예외 401로 변경 + 인증 예외 로깅 리팩토링
  * MemberInterceptor 404 -> 401로 변경
  * 모든 인증 예외 : '인증이 실패했습니다.' 로깅이었던 것 -> 로깅 정보 추가해서 로깅되도록 수정
    * AuthenticationException에서 message로 logMessage를 받아서 Handler에서 로깅 시 사용하도록 리팩토링
    * 사용자에게 나갈 ErrorResponse는 Handler에서 직접 설정("인증이 실패했습니다.")   

## 참고자료

## 의논할 거리

2023-09-04 08:56 UTC, SproutMJ requested changes
good
final만 붙여주세용

2023-09-04 08:56 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/auth/jwt/JwtTokenExtractor.java
> +        String logMessage = "인증 실패(액세스 토큰 추출 실패) - 토큰 : " + accessToken;
final이 없습니다.

2023-09-04 08:56 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/auth/presentation/MemberInterceptor.java
> +@Slf4j
제거해주세요.

2023-09-05 01:15 UTC, SproutMJ approved these changes
good

2023-09-05 01:53 UTC, pilyang requested changes
중간에 사용 안하는것같은 로깅 어노테이션이 보이는데 확인 부탁드립니다!

2023-09-05 01:53 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/auth/jwt/JwtTokenProvider.java
> +@Slf4j
여기서는 로깅이 빠진것 같은데 이친구는 왜 남아있는걸까요...??

2023-09-05 01:57 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/auth/jwt/JwtTokenProvider.java
> +@Slf4j
수정했습니다!

2023-09-05 01:57 UTC, the9kim approved these changes
귀찮은 작업이었을텐데 고생 많으셨습니다 성하!

2023-09-05 02:16 UTC, pilyang approved these changes
반영해주신 내용 확인했습니다!

2023-09-05 02:59 UTC, merged