[FE] Menu 컴포넌트 키보드 탐색 기능 구현
woowacourse-teams/2023-team-by-team pull request #615
Opened 2023-09-04 10:29 UTC by suyoungj

# [FE] Menu 컴포넌트 키보드 탐색 기능 구현
## 이슈번호
> close #608 

## PR 내용
- Menu 컴포넌트 키보드 탐색 기능 구현
- 위/아래 방향키, Enter, Escape 키 입력 감지
- 방향키에 따라 포커스 이동
- Enter 키 입력 시 포커스된 항목 선택
- Escape 키 입력 시 메뉴 닫기

## 참고자료
https://so-so.dev/react/make-select/

2023-09-08 08:35 UTC, hafnium1923 requested changes
코드,, 너무 어려워요😭😭😭😭😭😭
 1+1배웠는데 구구단 문제 나오는거 같애요

2023-09-08 08:35 UTC, hafnium1923 commented on frontend/src/components/common/Menu/MenuList/MenuList.tsx
> +  const selectItem = (value: string) => {
개인적인 생각으로는  handleMenuClick에서 selectItem 함수를 호출하고 있으니 selectItem이 handleMenuClick보다 위에 있으면 좋겠어!

2023-09-08 08:35 UTC, hafnium1923 commented on frontend/src/hooks/useListKeyboardNavigation.ts
> +    isMouseOver.current = false;
mouseEnter 했을 때 기존 select 된 메뉴의 class를 지웠다면 mouseLeave했을 때는 기존 select된 메뉴에 다시 class를 넣어주는게 맞지않을까?

2023-09-08 08:35 UTC, hafnium1923 commented on frontend/src/hooks/useListKeyboardNavigation.ts
> +          : focusChild(children[children.length - 1]);
select된게 없을 때 무조건 맨 마지막항목을 가리키는게 어색해보여.
차라리 
1. 직전 선택된 항목 기준으로 한 칸 위
2. 원래 선택되어있었던 항목 기준으로 한칸 위

가 더 맞을 것 같다는 생각! 

저게 어렵다면 난 윗키를 눌렀을 때 맨 처음 항목으로가고 아래키 눌렀을 때 맨 마지막 항목으로 가게 하는게 더 맞을 것 같애

2023-09-08 08:35 UTC, hafnium1923 commented on frontend/src/hooks/useListKeyboardNavigation.ts
> +          : focusChild(children[0]);
위 리뷰와 동일!

2023-09-08 08:35 UTC, hafnium1923 commented on frontend/src/hooks/useListKeyboardNavigation.ts
> +  const handleMouseEnter: MouseEventHandler<HTMLUListElement> = () => {
이거 뭐하는건지 한번 설명해줄 수 있어?
내가 생각한 로직은 마우스 호버를 위해서
마우스 들어왔을 때 selected된 항목에서 class를 지워주는 건데 맞나?

2023-09-08 08:35 UTC, hafnium1923 commented on frontend/src/hooks/useListKeyboardNavigation.ts
> +          ? focusPrevChild(children, getHoveredChildIndex(children))
키보드 탐색할 때는 선택된 항목과 hover되는 항목 둘다 보이는데 왜 마우스만 움직일 때는 선택된 항목은 표시가 지워지는거야?

2023-09-08 08:35 UTC, hafnium1923 commented on frontend/src/hooks/useListKeyboardNavigation.ts
> +    const { offsetTop } = child;
offsetTop은 모든 Element가 가지고 있는 속성이야? 신기하네!

2023-09-11 03:52 UTC, wzrabbit approved these changes
루루 피드백 반영해 줘!
수고 많았습니다

2023-09-12 04:42 UTC, suyoungj commented on frontend/src/components/common/Header/Header.tsx
> +                onSelect={handleTeamNameChange}
동작에 `선택한다`는 의미를 좀 더 담고 싶어서 수정했어!

2023-09-12 04:44 UTC, suyoungj commented on frontend/src/components/common/Menu/MenuList/MenuList.tsx
> +  const selectItem = (value: string) => {
난 호출하는 함수가 바로 아래에 있으면 확인하기 좋다는 생각이야!
보통 코드를 위에서 아래 방향으로 읽으니까 좀 더 확인하기 쉬운 느낌?

2023-09-12 04:48 UTC, hafnium1923 commented on frontend/src/components/common/Menu/MenuList/MenuList.tsx
> +  const selectItem = (value: string) => {
오 오히려 나는 위에서 아래 방향으로 읽으니 위에 호출되는 함수가 있어야 한다고 생각했는데 이건 그냥 취향차이 같네

2023-09-13 05:36 UTC, suyoungj commented on frontend/src/hooks/useListKeyboardNavigation.ts
> +          ? focusPrevChild(children, getHoveredChildIndex(children))
키보드 탐색할때는 선택된 항목을 지우는 과정이 너무 까다로워서 일단 배제했어

2023-09-13 05:38 UTC, suyoungj commented on frontend/src/hooks/useListKeyboardNavigation.ts
> +          : focusChild(children[children.length - 1]);
이건 정하기 나름인데, 난 HTML `<select>`랑 최대한 똑같이 구현하는걸로 했어!
`<select>`랑 다르게 동작하면 사용자가 오히려 헷갈릴 수 있다는 생각이 들었어
아예 비슷하게 하려고 선택된 항목에 체크 아이콘을 추가했는데 이건 어때??
<img width="317" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/5ac8f921-d368-451b-8482-1d1b20cfef61">

2023-09-13 05:50 UTC, hafnium1923 commented on frontend/src/hooks/useListKeyboardNavigation.ts
> +          : focusChild(children[children.length - 1]);
오 좋은데요? 근데 이거 푸쉬되어있나요? 확인하려고 보니까 추가로 수정된 사항이 없어보이는데

2023-09-13 06:05 UTC, suyoungj commented on frontend/src/hooks/useListKeyboardNavigation.ts
> +          : focusChild(children[children.length - 1]);
푸시해씀다

2023-09-13 07:09 UTC, hafnium1923 approved these changes
오래가네요 이 PR ㅋㅋㅋ 수고하셨습니다

2023-09-13 07:09 UTC, merged