[FE] 팀플레이스 내 정보 수정 기능 구현
woowacourse-teams/2023-team-by-team pull request #645
Opened 2023-09-14 07:10 UTC by suyoungj

# [FE] 팀플레이스 내 정보 수정 기능 구현
## 이슈번호
> close #644 

## PR 내용
- 팀플레이스 내 정보 수정 기능 구현

2023-09-15 02:50 UTC, hafnium1923 requested changes
깔꼼하네요

2023-09-15 02:50 UTC, hafnium1923 commented on frontend/src/hooks/team/useTeamPlaceInfoModal.ts
> +const getMe = (members: Omit<UserInfo, 'email'>[]) => {
getMe와 getMeFirstMembers는 왜 따로 빼둔거야?

2023-09-15 02:50 UTC, hafnium1923 commented on frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.tsx
> +                            >{`${myUserName.length}/${MAX_USER_NAME_LENGTH}`}</Text>
이거 의도하신건진 모르겠는데 21/20 이렇게 찍힙니다. 저는 20/20까지만 되고 20글자가 넘으면 아래에 빨간 글씨? 로 강조했으면 좋겠어요

2023-09-15 02:50 UTC, hafnium1923 commented on frontend/src/hooks/team/useTeamPlaceInfoModal.ts
> +    if (name.length > MAX_USER_NAME_LENGTH) {
이거 작동안해요

2023-09-15 02:50 UTC, hafnium1923 commented on frontend/src/hooks/user/useUserInfoModal.ts
> +  useEffect(() => {
얜 왜 추가되었나요? 기존에 문제없던걸로 기억하는데

2023-09-15 05:46 UTC, suyoungj commented on frontend/src/hooks/user/useUserInfoModal.ts
> +  useEffect(() => {
`useQuery`로 불러온 데이터를 state 초기값으로 주는게 안티패턴이라고 해서 `useEffect`로 동기화하는 방식으로 수정했어!

https://tkdodo.eu/blog/practical-react-query#keep-server-and-client-state-separate

2023-09-15 05:46 UTC, suyoungj commented on frontend/src/hooks/team/useTeamPlaceInfoModal.ts
> +const getMe = (members: Omit<UserInfo, 'email'>[]) => {
컴포넌트 안에 있을 필요가 없고, 렌더링 될 때마다 매번 생성되면 비효율적이라 밖으로 뺐어

2023-09-15 05:47 UTC, suyoungj commented on frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.tsx
> +                            >{`${myUserName.length}/${MAX_USER_NAME_LENGTH}`}</Text>
20자까지는 입력과 제출이 가능한데, 빨간 테두리로 강조하면 
제출이 아예 안된다는 느낌이 들어서 이대로 유지하는게 좋아보이는데 어때??

2023-09-15 06:53 UTC, hafnium1923 approved these changes
수고하셨슴둥~

2023-09-19 01:46 UTC, wzrabbit commented on frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.tsx
> +                            >{`${myUserName.length}/${MAX_USER_NAME_LENGTH}`}</Text>
오 빨간 테두리로 강조되도록 만들었구나
나는 21/20으로 찍히지 않아서 그러려니 하고 넘어갔었는데 브라우저마다 진짜 다른 점이 많네

2023-09-19 01:46 UTC, wzrabbit commented on frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.tsx
> +                          </Text>
👍🏻 👍🏻 👍🏻

2023-09-19 01:46 UTC, wzrabbit commented on frontend/src/hooks/team/useTeamPlaceInfoModal.ts
> +    if (name.length > MAX_USER_NAME_LENGTH) {
이거 작동 안 한다는 게 어디가 작동 안 한다는 거야?
근데 이 부분은 React로 관리되는 부분이라 HTML 장난질 치는 걸로는 이 토스트를 확인 못 하겠네
직접 state 값 조작해서 확인해씀

2023-09-19 02:05 UTC, wzrabbit approved these changes
수고 많이 하셨습니다
<img src="https://user-images.githubusercontent.com/87642422/233828081-bec1bb8b-7c29-4fac-8c67-0c84bb814ee2.png" width="35px" />

2023-09-19 02:06 UTC, merged