[BE] s3 presigned url 생성 기능 구현
woowacourse-teams/2023-team-by-team pull request #646
Opened 2023-09-14 09:01 UTC by SproutMJ

## 이슈번호
#637 

## PR 내용

###  S3 Presigned Url 생성 기능 구현
> 현재 로컬에서 테스트 할 수 없어서 DEV 환경에서 테스트해봐야 함.

* 패키지 : aws/s3 패키지 생성하여 작업
* 라이브러리 의존 : aws 공식문서의 awssdk-s3 사용
```java
    implementation platform('software.amazon.awssdk:bom:2.20.56')
    implementation 'software.amazon.awssdk:s3'
```
* S3Configuration 설정 클래스에서 PresignedUrl 작업을 해주는 S3Presigner 빈 생성하여 이후에 주입

### S3PresignedUrlProvider에서 PresignedUrl 생성 작업 진행
* `PutObjectRequest` : 실제 S3 객체 업로드 Request 생성
  * key는 S3UploadService에서 생성한 customKey로 지정
    * customKey : `directory + "/" + UUID.randomUUID() + encodedEmail`
    * bucket : S3 버킷 이름 -> yml에 추가해서 @Value로
    * contentType : 이미지만 업로드하도록 설정
    * contentLength : byte 단위로 max 5MB 되도록 여기서 설정
    * checksumSHA256 : 클라이언트에서 파일을 해싱한 값이 SHA256으로 한게 맞는지 + 값 검증
 
* `PutObjectPresignRequest` : PresignUrl 관련 Request 생성
  * signatureDuration : PresignedUrl의 유효 기간 -> 3분으로 지정

-> `s3Presigner.presignPutObject(putObjectPresignRequest).url().toString()`로 생성된 Presigned Url 반환

## 참고자료
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/86831441/02b6ab16-afb8-4688-9c95-8c7477cc05b8)

## 의논할 거리

2023-09-14 11:24 UTC, pilyang requested changes
워크플로우 실패한것 관련해서도 코멘트 남겼고, 설계적인 부분이랑 일부 코멘트 남겼습니다!!

확인 부탁드립니다..ㅎ^^

2023-09-14 11:24 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/aws/s3/application/S3UploadService.java
> +            String customKey = directory + "/" + UUID.randomUUID() + encodedEmail;
`final`,,ㅎㅎ

2023-09-14 11:24 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
> +    }
가독성을 위해서
```java
s3UploadService.getImageUploadPresignedUrl(memberEmailDto, images)
```
는 필드 분리해주는게 좋을 것 같긴 합니다..ㅎ


추가로 해당 로직이 teamPlace 컨트롤러에 있는 이유가 있을까요??

aws를 위한 패키지에 해당 컨트롤러도 생각을 해보았지만, 다시 생각해보니 그러면 외부 서비스(클라우드 서비스 - aws)에 의존적인 패키지 구조/컨트롤러 설계라 생각해서, 다른 feature package에 있는것은 좋겠다고 다시 생각이 들긴 했습니다.

하지만 지금까지 teamplace패키지에서는 팀플레이스와 관련된 로직들을 위한 api처리를 위한 패키지였는데,, 이것은 `스레드 피드`에 `이미지`등록을 위한 api라고 생각이 듭니다.
이런 의미에서는 피드관련 패키지에 추가를 하거나, 이미지 처리를 위한 패키지를 새로이 추가하는 방법도 있었을 것 같은데. 이런 두가지 패키지가 아닌 팀플레이스 패키지에서 구현한 이유가 궁금합니다.

2023-09-14 11:24 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/PresignedUrlsResponse.java
> +}
오 이건 몰라서 궁금함에 물어보는건데,,, Response에서도 validation annotation이 적용이 되나요..?
적용이 된다면 어느시점에 적용이 되나요..?

request같은 경우는 컨트롤러에서 @Valid 라는 어노테이션을 추가해주면, 파라미터로 해당 request body를 파싱해오는 과정에서 적용이 되게 되는데,, response 는 언제 어떻게 적용이 되는지 모르겠네요...ㅎㅎ

2023-09-14 11:24 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/aws/s3/S3PresignedUrlProvider.java
> +}
이부분은 그냥 일단은 간단한 의견입니다.

지금 저희는 우테코에서 플젝을 진행하고있고, aws를 이용하기 때문에 aws에 의존적인 서비스를 구현한다에 초점이 맞추어져 있어서 이런 구현에 대해서도 그럴 수 있다고는 생각하긴 합니다.
그래서 패키지 자체도 aws라는 명의 패키지가 생긴것이겠지요...ㅎㅎ

추가적으로 만약에 우리가 우테코가 끝나고도 서비스를 유지하기로 결정을 하고, 이후에 aws가 아닌 다른 클라우드 플랫폼으로 이동한다고 생각을 해보겠습니다.

그러고 해당 서비스에서 aws의 s3와같은 외부 저장소 서비스를 제공하고, 마찬가지로pre-signed url과 같은 기능을 제공하게 된다면,,, 어떻게 될까요...
다른 플렛폼에서는 어차피 해당  pre-signed url같은것을 제공한다는 확신도 없고, 어차피 aws를 계속 사용할거다라고 생각해도 될 것 같기는 하지만...ㅋㅋㅋ
다른 클라우드 플랫폼까지 안가고 단순히 aws sdk를 사용하지 못하고, pre-signed url을 얻는 과정을 직접 api통신을 통해 구현해야 하는 상황이 생겼다고만 생각을 해봐도 될 것 같네요

이런식으로 외부 라이브러리에 의존적으로 구현하게 된다면 이런 서비스의 변경시 `XXXPreSignedUrlProvider`라는 `component`를 새로 구현해야하고, 서비스코드 또한 해당 컴포넌트를 가져오도록 변경이 되어야 할 것 같네요.

이런 경우는 `PreSignedUrlProvider` interface를 만들어서 추상화를 한다음에 aws sdk를 사용하여 pre-signed url 을 생성해주는 Component를 구현하고, 서비스에서는 `PreSignedUrlProvider`를 주입받는 방식으로 구현을 하게  된다면, 외부 의존성이 변경이 되더라도 서비스 이하 계층에서는 코드의 변화가 없는 코드를 만들 수 있을 것 같습니다.
지금은 의존성에 따라 서비스코드까지 너무 크게 변동이 생기게 될 것 같네요..ㅎㅎ

반영을 꼭 해야한다는 아니지만 참고하시라고 코멘트 남겨보았습니다..ㅎㅎ

2023-09-14 11:24 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/aws/s3/S3PresignedUrlProvider.java
> +    private final S3Presigner s3Presigner;
이건 뭐죠..? aws skd에서 spring framework에 맞추어서 S3Presigner를 빈으로 생성해주지는 않았을것같은데..ㅎㅎ

이것때문에 테스트도 실패한것으로 보이네요

2023-09-14 11:39 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/aws/s3/S3PresignedUrlProvider.java
> +    private final S3Presigner s3Presigner;
앗 configuration에서 추가해주었었네요 호ㅓㄱ인 맷했습니다.. ㅈ히송합니디ㅠㅠㅠㅠ

음ㅁ 근데 에러로그에서는 이 빈생성에 문제여서 다시 로그함 봐바애겠네요..!

2023-09-15 00:42 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/PresignedUrlsResponse.java
> +}
@Valid가 ArgumentResolver에서 처리되는 거라서 Request에서만 동작하네요,,,
생각없이 Response에도 썼던 것 같습니다,, 😭
수정하겠습니다!

2023-09-15 00:50 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
> +    }
API 명세가 api/team-place로 시작해서 팀 플레이스 컨트롤러에 두게 되었는데, 완전 실수였네요,...
팀플레이스 컨트롤러 맵핑도 api/team-places로 되어 있네요.. 죄송합니다 ㅠㅠ😂

하면서도 팀플레이스 패키지에 있는게 맞나 싶어서 좀 고민했었는데 API 명세를 따라가려고 했었습니다!
근데 명세 URI 자체를 제대로 못 보고 했었네요 ㅠㅠ
FeedController로 옮기는게 맞는 것 같아요! 수정하겠습니다!

2023-09-15 01:00 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/aws/s3/S3PresignedUrlProvider.java
> +    private final S3Presigner s3Presigner;
test 패키지 application.yml에 프로퍼티 설정을 안해줘서 생긴 문제였습니다!
테스트 환경에서는 test 패키지의 application.yml로 설정 파일이 지정되는데
main 패키지의 application.yml에만 설정해줘서 생긴 문제였습니다!! 
수정하겠습니다!

2023-09-15 03:02 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/aws/s3/application/S3UploadService.java
> +                new String(Base64.getUrlEncoder().encode(memberEmailDto.email().getBytes(StandardCharsets.UTF_8)));
궁금한게 CustomKey 생성에 EncodedEmail을 사용하는 것은 UUID가 중복될 수 있는 경우에 대응하기 위함인가요?

2023-09-15 03:11 UTC, the9kim approved these changes
처음 접하는 내용일텐데 잘 구현해주셨군요!

코드를 읽다가, 궁금한 내용이 있어 코멘트 남겼습니다.

제가 뭘 모르는지 모르는 부분이 있긴한데, 정리해서 기술 공유 때 물어볼게요!

고생많으셨습니다!!

2023-09-15 03:25 UTC, pilyang requested changes
의견하나남겼고,,

서브모듈 application.yml관련해서 내용 남겼습니다!!
application-dev.yml, application-prod.yml도 반영 부탁드립니다!

2023-09-15 03:25 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/aws/s3/application/S3UploadService.java
> +                new String(Base64.getUrlEncoder().encode(memberEmailDto.email().getBytes(StandardCharsets.UTF_8)));
로이의 코멘트를 보니 떠오르는게 생겼는데,
해당 url은 이미지 임시 업로드 url 이여서 이메일을 인코딩만 해서 그대로 사용해도 될 수도 있을 같다는 생각이 들지만,,
이메일 정보는 개인정보임으로 해당 이미지를 실제 업로드된 이미지로 처리를 하며 디렉터리 이동을 할 때는 url에서 이메일 정보는 빼는게 좋을 것 같네요.
전에 제가 말한것처럼 해싱을 해서 사용을 하거나요.

+) 임시 url에서도 사실 가능하다면 이메일 정보는 숨기는게 좋을 것 같다는 생각이 들기도 합니다..
만약에 임시업로드에서도 이메일 정보를 숨긴다면 후에 피드업로드시에 해당 파일명은 그대로사용하고 디렉터리 위치만 변경해주면 도니까요..!

2023-09-15 03:25 UTC, pilyang commented on backend/src/main/resources/application.yml
> +
지금은 submodule로 배포가 이루어지게 작업이 안되어서 상관 없어보일 수 있긴 하지만...
submodule에 업로드하는것도 확인/연습겸 + 관련 정보를 저희끼리 공유하기도 해야하니 서브모듈에 있는 파일들에도 해당 내용 추가해서 푸시 부탁드립니다!!

추가로 아직은 secrete에서 관리되니, 머지하기 전에 submodule로 있는 프라이빗 레포 반영하고, 해당 내용 복붙해서 secrete도 변경 부탁드립니다! 

커밋에 보니 서브모듈 변경 관련 내용이 없네요.. filechanged 에도..

2023-09-18 06:02 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/aws/s3/S3PresignedUrlProvider.java
> +}
지금 로직이 S3에 너무너무 의존적인 것은 맞지만 S3를 대체할만한 대체제가 지금 상황에서 딱히 떠오르지 않아서 추상화하기가 어려운 것 같습니다.

2023-09-18 06:20 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/aws/s3/application/S3UploadService.java
> +                new String(Base64.getUrlEncoder().encode(memberEmailDto.email().getBytes(StandardCharsets.UTF_8)));
이메일에 해싱 완료했습니다.

2023-09-18 07:20 UTC, pilyang approved these changes
확인했습니당

2023-09-18 07:29 UTC, merged