[FE] 변경된 피드 공지 컴포넌트 UI 구현
woowacourse-teams/2023-team-by-team pull request #647
Opened 2023-09-14 09:06 UTC by hafnium1923

# [FE|BE|ALL] PR 타이틀 
## 이슈번호
> close #624  close #625 

## PR 내용
스레드 박스 효과때문에 스크롤시 공지 컴포넌트 옆으로 삐져나와보임 -> 어차피 말풍선 UI 변경하면 고쳐질 것
스레드 등록 바텀시트 열면 공지컴포넌트zindex가 1이라서 백드롭 위로 튀어나옴 -> 어차피 채팅창 UI 변경되면 고쳐질 것
 
## 참고자료

## 의논할 거리

stiky로 스레드 리스트에서 상단고정시켜놨는데 그 때문에 늘리거나 줄이면 리스트의 길이도 함께 바뀜.
최상단이 아닐경우는 리스트가 움직이지는 않지만 최상단의 경우 리스트의 길이가 아래로 밀림 
-> 해결방법 모르겠음 알려주면 함
-> 스레드 방향이 탑다운 에서 바텀업으로 바뀔 예정이라 스레드 방향 바꾸고나서 문제생기면 후에 픽스하겠음

2023-09-15 02:54 UTC, wzrabbit commented
스토리북에서 컴포넌트를 볼 때 공지를 확장시키면 하단의 파란 선이 컴포넌트와 떨어지는 것 같은데, 확인해 줄 수 있어?
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/c845a9d4-4b07-4541-a077-08bee5aaa34e)

2023-09-15 02:54 UTC, wzrabbit requested changes

2023-09-15 02:54 UTC, wzrabbit commented on frontend/src/components/feed/NoticeThread/NoticeThread.tsx
> +            aria-label="접기 버튼"
1. "무엇을" 접는 건지 스크린리더에 의존하는 사용자가 알아내기 힘들 것 같다는 생각이 들었는데, **공지 접기 버튼** 과 같은 표현을 사용하는 것에 대해서는 어떻게 생각해?
2. "버튼" 이라는 정보는 적었을 때 스크린 리더에서 두 번 들렸어서 유스가 이전에 피드백해줬던 걸로 기억해, 이 경우라면 **공지 접기** 로 바꾸는 것도 괜찮아 보이고?

어찌되었든 텍스트만 읽어도 무슨 뜻인지 알아들을 수 있는 표현이면 좋을 것 같아

2023-09-15 02:54 UTC, wzrabbit commented on frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
> +      `;
`noticeSize === 'sm'` 인 경우에는 `width` 속성과 `gap` 속성이 띄어져 있는데, `noticeSize === 'md'` 인 경우에는 붙어져 있는 것 같은데, 일관성을 위해 둘 중 하나로 통일하면 어떨까?

2023-09-15 02:54 UTC, wzrabbit commented on frontend/src/components/feed/NoticeThread/NoticeThread.tsx
> +  const handleExpendMoreClick = () => {
```suggestion
  const handleExpandMoreClick = () => {
```

요기에 오타 있는 것 같아!

2023-09-15 02:54 UTC, wzrabbit commented on frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
> +export const MegaPhoneWrapper = styled.div`
```suggestion
export const MegaphoneWrapper = styled.div`
```
메가폰 관련 변수명을 `Megaphone~` 으로 변경하는 걸 제안해 볼게!
왜냐하면, `megaphone` 은 한 단어이니까.

2023-09-15 02:54 UTC, wzrabbit commented on frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
> +`;
css 컨벤션에 맞게 수정해 주면 좋을듯!

```
5. width & height - 크기
6. margin & padding(그룹) - 간격

9. font(그룹) - 폰트
```

2023-09-15 03:08 UTC, hafnium1923 commented on frontend/src/components/feed/NoticeThread/NoticeThread.tsx
> +            aria-label="접기 버튼"
넹 반영하겠슴다~

2023-09-15 03:09 UTC, hafnium1923 commented on frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
> +      `;
넴 수정했습니당~

2023-09-15 03:13 UTC, hafnium1923 commented
> 스토리북에서 컴포넌트를 볼 때 공지를 확장시키면 하단의 파란 선이 컴포넌트와 떨어지는 것 같은데, 확인해 줄 수 있어? (데코레이터가 사용되지 않았다고 했는데 바깥쪽에 공지와 관련 없는 회색 컴포넌트가 보이는 것 같기도 하고?)

이건 아까 설명한대로 위쪽 배경은 내가 의도한거고 아래쪽은 요토가 알려준대로 수정해보도록 할게

2023-09-15 03:28 UTC, suyoungj requested changes
👍

확성기 아이콘 위치가 계속 변하는데, 그냥 고정시키면 좋을듯?

2023-09-19 02:00 UTC, wzrabbit approved these changes
<img src="https://user-images.githubusercontent.com/87642422/233828081-bec1bb8b-7c29-4fac-8c67-0c84bb814ee2.png" width="35px" />

컴포넌트 상태라서 100% 완벽하게 리뷰할 수는 없었지만
합치면서 고민해 볼 만한 점 있으면 고민해보자

2023-09-19 04:58 UTC, suyoungj approved these changes

2023-09-19 04:59 UTC, merged