[FE] 채팅 메뉴의 이미지 상세 보기 모달 구현
woowacourse-teams/2023-team-by-team pull request #649
Opened 2023-09-15 00:53 UTC by wzrabbit

# [FE] 채팅 메뉴의 이미지 상세 보기 모달 구현
## 이슈번호
> close #632 

## PR 내용

## 참고자료

## 의논할 거리

2023-09-15 03:20 UTC, wzrabbit commented on frontend/src/components/feed/ThreadImageModal/ThreadImageModal.styled.ts
> +  background-color: #00000070;
PR 코멘트에 적은대로, 색상 확정되면 `theme` 사용해서 다시 고칠게

2023-09-15 05:38 UTC, suyoungj reviewed
👍

오프라인에서 말했던 디자인 수정도 부탁드려요

2023-09-15 05:38 UTC, suyoungj commented on frontend/src/components/feed/Carousel/Carousel.tsx
> +                  죄송합니다. 이 이미지는 기간이 만료되었습니다.
만료된 이미지입니다. 정도로 충분하지 않을까?

2023-09-15 05:38 UTC, suyoungj commented on frontend/src/components/feed/Carousel/Carousel.tsx
> +                <img src={url} />
alt 넣어주세욥

2023-09-18 08:55 UTC, hafnium1923 requested changes
구생했어~~ 말해준 블러는 이쁘더라도 성능이 많이 떨어진다면 사용하지 않는편이 좋을 것 같아.
다른팀 이미지 모달 가져왔는데 이렇게 뒷 배경을 단색으로 칠하는 것도 이쁜데 어떻게 생각해?

<img width="1127" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/2e348a22-233d-48fe-8e6a-47b178890e75">

2023-09-18 08:55 UTC, hafnium1923 commented on frontend/src/components/common/PageIndicator/PageIndicator.stories.tsx
> +  title: 'common/PageIndicator',
얘만 왜 common 하위로 들어가 있는지 이유가 궁금해

2023-09-18 08:55 UTC, hafnium1923 commented on frontend/src/components/feed/Carousel/Carousel.tsx
> +                  죄송합니다. 이 이미지는 기간이 만료되었습니다.
인정합니다. 우리가 사과할 필요는 없는듯?

2023-09-18 09:32 UTC, wzrabbit commented
성능이랑 타협해야 된다는 사실이 슬프긴 하다 😭 
하지만 어쩔 수 없겠지? 성능 때문에 버벅거리는 현상이 심해지면 그게 더 사용자에게 안 좋은 경험이 될테니까
배경은 아마 blur 빼고 단색으로 작업해 볼듯

이 모달에서는 이미지의 화질을 최대한 좋게 보여줘야 하니, 이미지와 관련된 부분은 성능 저하가 있더라도 건드리지 않을게
기능이 제일 중요하니까

2023-09-18 09:37 UTC, wzrabbit commented on frontend/src/components/common/PageIndicator/PageIndicator.stories.tsx
> +  title: 'common/PageIndicator',
원래는 `PageIndicator`, `Carousel` 두 컴포넌트 모두 `common` 의 하위로 들어가 있었어. 컴포넌트가 시멘틱하고 한 가지 기능만을 담당하고 있었고, 어느 컴포넌트에 무조건 종속되야 하는 기능 없이 범용성이 높은 기능을 수행하고 있었던 것으로 보여서 이렇게 했었어.

그런데 이후 API 명세에 맞게 컴포넌트의 props를 변경해야 했고, `Carousel` 컴포넌트만 props가 바뀌었어. 그래서 이 시점부터는 `Carousel` 컴포넌트를 범용성이 높게 재사용하기는 힘들다고 판단해서 `Carousel` 컴포넌트만 `common` 밖으로 빼낸 거야.

항상 작업할 때마다 느끼는 건데 공통 컴포넌트에 넣을지 말지 결정하는 게 참 힘들더라 😓 혹시 괜찮은 대안이 떠오른다면 조언해 주면 고맙겠어! 나도 고민하고 있는 부분이니까

2023-09-18 09:39 UTC, wzrabbit commented on frontend/src/components/feed/Carousel/Carousel.tsx
> +                  죄송합니다. 이 이미지는 기간이 만료되었습니다.
나는 보통 예의상으로라도 정중하게 메시지를 적으려 하는 편인데, 만료된 이미지의 경우 단순 오류가 아니라 시스템에 의해 의도적으로 이미지가 만료될 수 있는 상황인 것으로 보이니까, "이 이미지는 기간이 만료되었습니다." 정도로 고쳐 볼게

2023-09-19 00:50 UTC, wzrabbit commented on frontend/src/components/feed/Carousel/Carousel.tsx
> +                <img src={url} />
별도로 넣을 만한 정보가 없어서 비웠는데 이미지 주소(이름)이라도 `alt` 에 넣어볼게!

2023-09-19 00:56 UTC, hafnium1923 commented on frontend/src/components/common/PageIndicator/PageIndicator.stories.tsx
> +  title: 'common/PageIndicator',
음 나는 아직까지 이 친구가 범용적으로 더 쓰일지 잘 모르겠어! carousel과 pageindicator가 같이 있는게 훨씬 자연스러워 보이기도 하고. 그래서 난 일단은 pageIndicator과 같이 feed 하위로 있으면 좋겠어

2023-09-19 02:07 UTC, wzrabbit commented on frontend/src/components/common/PageIndicator/PageIndicator.stories.tsx
> +  title: 'common/PageIndicator',
그러면 둘 다 `common` 에서 제외시키고, 이후 두 곳 이상 다른 주제(`feed`, `link`, `user`, ...)에서 컴포넌트가 사용되면 그 때 `common` 으로 옮겨보는 방향으로 진행해 볼게!

2023-09-19 03:20 UTC, wzrabbit commented
### 반영한 사항들!
- [x] 이미지에 `alt` 속성 추가
- [x] `PageIndicator` 를 `/common` 에서 제외 및 `/feed` 로 디렉토리 변경
- [x] "이미지 만료" 오류 메시지 수정 
- [x] 모달의 화살표 디자인 수정
- [x] 모달의 배경 변경 (`blur`) 제거

### 결과
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/df9793ca-2de9-4317-93ad-93eca76016c7)

2023-09-19 04:38 UTC, wzrabbit commented on frontend/src/components/feed/Carousel/Carousel.tsx
> +  onPageChange: (page: number) => void;
아이고 무의식중에 이름을 지었네... 바꾸고 다시 리뷰요청 할게!

2023-09-19 06:19 UTC, hafnium1923 approved these changes
수고하셨슴둥

2023-09-19 06:32 UTC, suyoungj approved these changes

2023-09-19 06:32 UTC, merged