[FE] 팀플레이스 전환 박스 디자인을 변경
woowacourse-teams/2023-team-by-team pull request #663
Opened 2023-09-19 11:03 UTC by wzrabbit

# [FE|BE|ALL] PR 타이틀 
## 이슈번호
> close #585

## PR 내용
본 PR에서는 팀플레이스 전환 박스의 디자인을 보다 사용자가 기능을 알아채기 쉽도록 개선하였다.
자세히 설명하고 싶지만 딱히 더 설명할 게 없으니 참고자료를 보여주는 것으로 마치겠다.

## 참고자료
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/bf5a96cc-e5db-4f99-9162-5fc0047eba87)

2023-09-19 11:12 UTC, wzrabbit commented
유스의 요청으로 디자인 소폭 수정 완료!

- 폰트 크기: `24px` → `22px`
- svg 요소 크기: `32px`  → `24px`

![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/3e3810c9-dc02-4806-8e6e-136177f590e0)

2023-09-19 11:14 UTC, hafnium1923 requested changes
굿 커멘트 하나만 확인해줘

2023-09-19 11:14 UTC, hafnium1923 commented on frontend/src/assets/svg/arrow-down-rounded.svg
ArrowExpandMoreIcon 이랑 생김새 같아보이는데 따로 추가한 이유가 있을까?!

2023-09-19 11:20 UTC, wzrabbit commented on frontend/src/assets/svg/arrow-down-rounded.svg
헉, 아무리 찾아봐도 `ArrowDown` 과 같은 이름을 가진 아이콘이 없어서 새로 넣은 건데, 생각해 보니 그 아이콘이 있었구나.
일부러 추가한 거 아니야, 아이콘이 없는 줄 알고 새로 만들었어. 이미 아이콘이 있다는 걸 알았으니 되돌릴게, 짚어줘서 고마워.

2023-09-20 00:41 UTC, hafnium1923 approved these changes
어제 늦은 시간 까지 고생했어~~~

2023-09-20 01:37 UTC, merged