[FE]MyDailyScheduleList Suspense적용
woowacourse-teams/2023-team-by-team pull request #685
Opened 2023-09-20 12:52 UTC by hafnium1923

# [FE|BE|ALL] PR 타이틀 
## 이슈번호
> #678 #150 

## PR 내용
spinner 추가했음다

## 참고자료

## 의논할 거리

2023-09-22 01:27 UTC, wzrabbit requested changes
신기한 걸 만들어왔구나! 코멘트 확인해 줘~

2023-09-22 01:27 UTC, wzrabbit commented on frontend/src/components/common/Spinner/Spinner.styled.ts
> +  }
오, 음수 `animation-delay` 를 사용했구나
나도 이거 보고 검색해 봤는데 `animation-delay` 가 음수이면 애니메이션이 중간부터 시작되는 걸로 동작하는 것 같더라

애니메이션이 10초짜리인데 `animation-delay` 가 -2초면 애니메이션은 8초부터 시작하고 그 이후부터는 애니메이션이 반복되는 걸로 보이는데 내가 이해한 게 맞으려나?

`animation-delay` 에 음수를 사용한 이유는 각 점들에 간격을 두면서도 처음부터 몇몇 점들이 안 움직이는 현상을 막고 싶어서 그랬던 걸까?

2023-09-22 01:27 UTC, wzrabbit commented on frontend/src/components/common/Spinner/Spinner.tsx
> +      </S.Loader>
항상 `S.Ball` 의 개수가 일정하기는 하겠지만 그래도 `map` 등을 사용하면 어떨까?

`S.Ball` 의 개수도 파악하기 쉬워지고, 이후 `S.Ball` 에 새로운 prop을 넣는다든지 그런 일을 할 때 여러 곳에 수정을 가하지 않아도 될 것 같아서

2023-09-22 01:27 UTC, wzrabbit commented on frontend/src/components/my_calendar/MyDailyScheduleList/MyDailyScheduleListFallback/MyDailyScheduleListFallback.stories.ts
> +    rawDate: new Date(),
스토리북에 `rawDate` 속성이 있어서 `MyDailyscheduleFallback` 컴포넌트 파일을 직접 봤는데 실제로는 `rawDate` 속성이 없는 걸로 보이네!
만약 의도한 게 아니라면 이 속성은 스토리북에서 빼 줄 수 있을까?

2023-09-22 01:32 UTC, hafnium1923 commented on frontend/src/components/common/Spinner/Spinner.styled.ts
> +  }
미안해.. css 긁어온거라 내가 설명할 수 없어ㅠㅠ

2023-09-22 01:33 UTC, hafnium1923 commented on frontend/src/components/common/Spinner/Spinner.tsx
> +      </S.Loader>
좋은 생각이다!

2023-09-22 01:38 UTC, hafnium1923 commented on frontend/src/components/my_calendar/MyDailyScheduleList/MyDailyScheduleListFallback/MyDailyScheduleListFallback.stories.ts
> +    rawDate: new Date(),
넹면

2023-09-22 01:47 UTC, wzrabbit commented on frontend/src/components/common/Spinner/Spinner.styled.ts
> +  }
https://drafts.csswg.org/css-transitions/#transition-delay-property

여기에 관련 내용이 있어서 이걸 참고했는데 한 번 보면 좋을듯

2023-09-22 01:50 UTC, wzrabbit approved these changes
<img src="https://cdn.dribbble.com/users/783963/screenshots/3995765/media/dfc23c62ac1d6f32dc7c4a9c00d736a3.gif" width="300px" />

2023-09-26 06:48 UTC, suyoungj reviewed
Suspense 이슈로 잠시 보류해야겠네요 🥲

2023-12-12 08:30 UTC, closed without merging