[FE] 이미지를 로컬에 업로드할 수 있는 기능 구현
woowacourse-teams/2023-team-by-team pull request #693
Opened 2023-09-21 19:43 UTC by wzrabbit

# [FE] 이미지를 로컬에 업로드할 수 있는 기능 구현
## 이슈번호
> close #634, close #636, close #638

## PR 내용
본 PR에서는 이미지를 로컬에 업로드할 수 있는 기본적인 기능들을 구현하였다. 로컬에 업로드만 가능할 뿐, 실제로 서버로 이미지에 대한 정보를 보내는 기능은 포함하지 않음에 유의한다.

## 참고자료
[MDN input type file](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file)

## 의논할 거리

2023-09-21 20:15 UTC, wzrabbit commented on frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
> +        <form onSubmit={handleSubmit} style={{ zIndex: 1 }}>
`z-index` 를 사용할 지 말지가 결정되면 이 부분 개선할 예정!

2023-09-25 04:58 UTC, hafnium1923 requested changes
> "공지로 등록" 글씨로 인해 채팅창의 height 가 고정이 아닌 것 같은데, 이건 어떻게 해결할까

고정 시킵시당

2023-09-25 04:58 UTC, hafnium1923 commented on frontend/src/hooks/thread/useImageUploader.tsx
> +  const updateImages = (e: ChangeEvent<HTMLInputElement>) => {
```suggestion
 const updateImages : ChangeEventHandler<HTMLInputElement> = (e) => {
```

2023-09-25 04:58 UTC, hafnium1923 commented on frontend/src/components/feed/ThumbnailList/ThumbnailList.tsx
> +  onChange: ChangeEventHandler<HTMLInputElement>;
뭔가 () => void 처럼 이쁘게 할 수 있을 것 같은데 아쉽네

2023-09-25 04:58 UTC, hafnium1923 commented on frontend/src/hooks/thread/useImageUploader.tsx
> +  const readImage = (file: File): Promise<string> => {
저번에 설명들었던 것 같긴한데 한번만 더 이 함수 설명해줄 수 있을까?

2023-09-25 04:58 UTC, hafnium1923 commented on frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
> +        <form onSubmit={handleSubmit} style={{ zIndex: 1 }}>
애니메이션을 살리는게 좋을 것 같아보이긴 함

2023-09-26 06:59 UTC, suyoungj reviewed
👍

2023-09-26 06:59 UTC, suyoungj commented on frontend/src/hooks/thread/useImageUploader.tsx
> +const useImageUploader = () => {
`useImageUpload`는 어때? 
Uploader라는 외부 API를 사용하는 네이밍같아

2023-09-26 06:59 UTC, suyoungj commented on frontend/src/hooks/team/useTeamFeedPage.ts
> +  const handleImageToggleButtonClick = () => {
나도 궁금해 함수를 두 개 만든 이유가 있을까?

2023-10-03 10:50 UTC, wzrabbit commented on frontend/src/hooks/thread/useImageUploader.tsx
> +const useImageUploader = () => {
오 듣고보니 그렇게 바꾸면 더 이름이 명확할 것 같아보이네

2023-10-03 15:01 UTC, wzrabbit reviewed
코멘트 하나만 이해가 잘 안 되서 다시 질문했고, 나머지 사항은 모두 반영 완료!

그런데 이 메뉴에서 "공지로 등록" 텍스트에 `ellipsis` 를 씌워보려고도 하고 아예 없애보려고도 했는데 쉽지가 않더라... flex 구조가 복잡하게 짜인 것 같아서 높이를 고정시킬 방법을 당장은 찾지 못했어

혹시 이 부분에 대해서 잘 알고 있으면 도와주면 고맙겠으!


![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/bcb982bb-b6fa-43b9-bd12-b4c3799cd3a5)

2023-10-04 01:52 UTC, hafnium1923 commented on frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
> +        <form onSubmit={handleSubmit} style={{ zIndex: 1 }}>
z-index: {({theme}) => theme.zIndex.NOTICE};
  
  어떰

2023-10-04 01:53 UTC, hafnium1923 commented on frontend/src/hooks/thread/useImageUploader.tsx
> +  const readImage = (file: File): Promise<string> => {
자세한 설명 고마워!

2023-10-04 05:24 UTC, wzrabbit commented on frontend/src/hooks/team/useTeamFeedPage.ts
> +  const handleImageToggleButtonClick = () => {
두 함수를 하나로 묶어야 하는 상황이라면, 로직은 토글링으로 통일하고 이름은 `handleImageDrawerToggle` 을 사용해 볼게

2023-10-04 05:26 UTC, wzrabbit commented
> 그런데 이 메뉴에서 "공지로 등록" 텍스트에 ellipsis 를 씌워보려고도 하고 아예 없애보려고도 했는데 쉽지가 않더라... flex 구조가 복잡하게 짜인 것 같아서 높이를 고정시킬 방법을 당장은 찾지 못했어

이 문제는 다른 PR에서 해결하고

> 네이밍 규칙을 위반하지 않고 열고 닫기를 한번에 구현할 수 있을 것 같아.

요거는 이름 통일해서 반영완료!

2023-10-04 05:31 UTC, hafnium1923 commented on frontend/src/hooks/thread/useImageUploader.tsx
> +  const updateImages = (e: ChangeEvent<HTMLInputElement>) => {
마쟈 그리고 일관성ㅋㅋㅋ

2023-10-04 05:32 UTC, hafnium1923 approved these changes
꼼꼼하게 구현하느라 수고많았어 요토!! height 관련해서 까먹지 않게 버그이슈만 하나 파줘~~

2023-10-04 06:29 UTC, suyoungj commented on frontend/src/hooks/team/useTeamFeedPage.ts
>      setIsImageDrawerOpen((prevIsImageDrawerOpen) => !prevIsImageDrawerOpen);
setter랑 함수명에서 어떤 동작을 할지 어느정도 예상이 돼서,
이정도는 `(prev) => !prev` 정도로 해도 괜찮을거 같아

2023-10-04 06:49 UTC, suyoungj approved these changes
👍

2023-10-04 06:49 UTC, merged