[BE] 일정 추가 기능 구현
woowacourse-teams/2023-team-by-team pull request #71
Opened 2023-07-15 07:50 UTC by sh111-coder

# [BE] 일정 추가 기능 구현
## 이슈번호
> #18 

## PR 내용

- 일정 추가(등록) 기능 구현 

- Repository Test : commit(https://github.com/woowacourse-teams/2023-team-by-team/commit/e172724ff6939cf9527af023bbd559445f45dc33)
- Service Test : commit(https://github.com/woowacourse-teams/2023-team-by-team/commit/3c19012cc67744bf2bab113ddf0e2e0a2a9dc319)

- acceptance Test : commit(https://github.com/woowacourse-teams/2023-team-by-team/commit/4c17c936b9e0bb8b02e58ca196758e59a24ca435)

---
###  추가 구현 사항 (특이 사항)

* Span에서 @AllArgsContructor 삭제, 모든 파라미터를 받는 생성자에 검증 로직 추가

* Request로 요청보낸 StartDateTime, EndDateTime의 형식도 검증한다.

* GlobalExceptionHandler 추가 (+ Handle 시 에러 로깅 추가)

* ScheduleFixtures 추가

* Repository 테스트 시 @DataJpaTest + @AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)

* ServiceTest 시 @nested로 공통 부분 (일정 등록) 추출

* 인수 테스트 예외 네이밍은 `실패한다`로 했음. (예외가 발생한다고 하면 비개발자가 이해하지 못할 수도 있을 것 같아서)

## 참고자료

- 2022 달록팀 코드

## 의논할 거리

2023-07-15 11:17 UTC, SproutMJ approved these changes
아주 좋습니다.
very good
すごい。

2023-07-16 09:48 UTC, pilyang requested changes
로깅사용하는거랑 해서 제가 놓친부분들이 많았네요..!!

보면서 제 코드도 많이 수정 했습니다!!

전반적으로 final이 있다가 없다가 해서 메서드 필드나 메서드 파라미터로,, 해당부분 한번씩 확인해주면 좋을 것 같아요.

requet change는 아니고 같이 컨벤션 정하고 이야기해보면 좋을 것 같은 부분들 있어서해당 부분들도 커멘트 남겨두었어요!!

2023-07-16 09:48 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/global/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
[Comment]

해당 부분에서는 전반적으로 사용될 예외 핸들링만 하고, 도메인에 가까운 예외들은 해당 도메인에 핸들러를 만드는거로 이해하면 되는건가요??

2023-07-16 09:48 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
> +
[Approve]

아 맞다 롬복..!! 까먹었다.. 👍

2023-07-16 09:48 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/schedule/presentation/ScheduleController.java
> +
[Commend]

해당부분은 같이 이야기해보면 좋을 것 같은 내용인데,

모든 일정관리 api를 해당 컨트롤러에 둘꺼면 팀일정이 아닌 통합일정 관련도 있어서 RequestMapping을 api까지만 해줘야할것같습니다.

통합일정을 컨트롤러 분리하는것도 괜찮을것 같다는 생각도 드는데, 만약에 그렇게 된다면 클래스 명의 변경이 필요할것 같습니다!!

같이 함 이야기 해봐요

2023-07-16 09:48 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/global/exception/GlobalExceptionHandler.java
> +    Logger log = LoggerFactory.getLogger(getClass());
[Approve & Comment]

Logger 사용..!! good... 저도 다시 적용해볼께요~~

해당부분은 finla안붙이는건가요..?ㅎㅎ

2023-07-16 09:48 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
> +        return savedSchedule.getId();
[RC]

`final` ㅎㅎ

2023-07-16 09:48 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/schedule/domain/Span.java
> +    private void validateDateTimeOrder(LocalDateTime startDateTime, LocalDateTime endDateTime) {
[RC]

final ㅎㅎ

2023-07-16 09:48 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/schedule/domain/Span.java
> +    private void validateDateTimeOrder(LocalDateTime startDateTime, LocalDateTime endDateTime) {
뒤에도 빠진부분이 많네여..ㅎㅎㅎ

2023-07-16 09:48 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/fixtures/ScheduleFixtures.java
> +}
[Approve]

오 픽스쳐 좋아요!!
제가 후에 남긴 PR에는 픽스처 적용 안되어있는데, 해당 부분들은 동일하게 이용하는 부분이 있어서 후에 본 피알 머지된 이후에나 다른 이슈를 생성하는등 해서 픽스쳐 사용으로 리팩터링 할께요!

2023-07-16 09:48 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
> +    }
[Comment]

메서드 명 한글로 만드는거는 같이 이야기해보면 좋을 것 같아요!!

2023-07-16 09:48 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
> +
[RC]

```suggestion
    @Nested
    @DisplayName("일정 등록 시")
    class RegisterSchedule {

```

클래스명 대문자요!!

2023-07-16 09:48 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/schedule/application/ScheduleServiceTest.java
> +
마찬가지로 클래스명 대문자 시작이면 좋을 것 같아요!!

2023-07-16 11:42 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/global/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
해당 부분 특정 일정 조회 PR에도 남겨놨는데 도메인 예외 핸들링도 global에서 하는 것으로 생각하긴 했습니다!

2023-07-16 11:43 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/schedule/presentation/ScheduleController.java
> +
특정 일정 조회 PR에 코멘트 남겨놨습니다!

2023-07-16 11:43 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/global/exception/GlobalExceptionHandler.java
> +    Logger log = LoggerFactory.getLogger(getClass());
넵 적용해주시면 감사하겠습니다!!!! PR 코멘트 달때 놓쳤네요 ㅋㅋㅋㅋ

final.... 붙이겠슴다!!!! 😂

2023-07-16 11:47 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
> +        return savedSchedule.getId();
ㅎㅎㅎㅎ... 인텔리제이 안 먹어서,,, 하ㅏㅏ 앞으로 조심하겠슴다

2023-07-16 11:48 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
> +    }
좋슴다!

2023-07-16 12:35 UTC, pilyang approved these changes
로깅사용하는거랑 해서 제가 놓친부분들이 많았네요..!!

보면서 제 코드도 많이 수정 했습니다!!

전반적으로 final이 있다가 없다가 해서 메서드 필드나 메서드 파라미터로,, 해당부분 한번씩 확인해주면 좋을 것 같아요.

requet change는 아니고 같이 컨벤션 정하고 이야기해보면 좋을 것 같은 부분들 있어서해당 부분들도 커멘트 남겨두었어요!!

2023-07-16 12:37 UTC, merged