[FE] ctrl,alt + enter로 개행기능 추가
woowacourse-teams/2023-team-by-team pull request #710
Opened 2023-09-26 08:32 UTC by hafnium1923

# [FE|BE|ALL] PR 타이틀 
## 이슈번호
> close #708 close #707 

## PR 내용
<img width="389" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/02404a08-1d42-4fd6-bc69-6d025a399d6f">

shift/ctrl/alt +enter로 개행이 가능합니다.
맥에서 option +enter로 개행이 되는지 확인해주셔야합니다.

## 참고자료

## 의논할 거리

2023-09-26 08:50 UTC, suyoungj requested changes
👍

2023-09-26 08:50 UTC, suyoungj commented on frontend/src/hooks/team/useTeamFeedPage.ts
> +    if ((e.key === 'Enter' && e.ctrlKey) || (e.key === 'Enter' && e.altKey)) {
isComposing 체크 로직 아래로 위치시키는게 좋을 것 같아

2023-09-26 08:50 UTC, suyoungj commented on frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
> +            placeholder="여기에 채팅을 입력하세요. &#13;&#10; &#13;&#10;(Shift/Ctrl/Option) + Enter로 새 행을 추가합니다."
Window 쓰시지 않나요? Alt는 어디간거죠?ㅋㅋㅋㅋ

슬랙처럼 Shift + Enter만 명시해줘도 좋을 것 같은데 어떻게 생각해?

2023-09-26 08:52 UTC, hafnium1923 commented on frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
> +            placeholder="여기에 채팅을 입력하세요. &#13;&#10; &#13;&#10;(Shift/Ctrl/Option) + Enter로 새 행을 추가합니다."
window는 알잘딱으로 Alt 써줄거야..ㅋ
>슬랙처럼 Shift + Enter만 명시해줘도 좋을 것 같은데

나도 동의! 바꿀게!

2023-09-26 08:53 UTC, hafnium1923 commented on frontend/src/hooks/team/useTeamFeedPage.ts
> +    if ((e.key === 'Enter' && e.ctrlKey) || (e.key === 'Enter' && e.altKey)) {
넵

2023-09-26 09:12 UTC, wzrabbit approved these changes
수고 많았어~

2023-09-27 01:35 UTC, suyoungj approved these changes

2023-09-27 01:35 UTC, merged