[BE] 피드 등록 이미지 업로드 추가
woowacourse-teams/2023-team-by-team pull request #715
Opened 2023-09-28 05:23 UTC by sh111-coder

# [BE] 피드 등록 이미지 업로드 추가
## 이슈번호
> closed #705 

## PR 내용

# 이미지 업로드 피드 등록 시 추가

* 이미지 업로드 관련 로직은 이전에 만들어 놨던 ImageUploadService 로직을 재사용
* 이때, 기존에 directoryPath에 있었던 이메일 해싱은 파일 길이만 길어지고 필요없다고 생각하여 제거
* `assetDirectory + imageDirectory + "/" + UUID.randomUUID()`로 생성 

## 요청 관련 Validation
* 이미지 개수 4개 이상 시 예외
* 이미지 크기 5MB 이상 예외
* 허용되지 않은 확장자 시 예외
* 내용, 이미지 모두 없을 시 예외

※ 프론트한테 물어봤을 때 내용이 없는 요청은 `""`로 요청보내는 게 편하다길래 ""와 content에 null과 "" 처리를 같이 함 
※ 이미지가 없이 내용만 요청 시에 Dto에 List<MultipartFile>에 null으로 들어오는데, 검증이 힘들어져서 EmptyList로 Dto에서 처리

## 참고자료

## 의논할 거리
* Validation 로직이 서비스 로직에서 조금 많아져서 Validator를 만들어서 책임 분리를 할까 고민했지만, 요청에 대한 검증이므로 그대로 서비스에서 하는게 맞다고 생각했고, 불필요한 클래스 생성을 줄였다!

* 현재 application-dev에 path 관련 property 설정이 잘 되어 있어서 건드리지 않았음
* appication-prod path property는 dev에서 이미지 업로드 테스트 후 추가할 예정

※ 그때 Application 실행 안되는 문제로 깃 클론 다시 받아서 진행했는데, 커밋 메시지가 초기화돼서 그냥 복붙했는데 커밋 메시지가 전부 올라갔네요... 죄송함다.. 다음에는 이전걸로 다시 사용해서 제대로 할게요 ㅠㅠ 커밋 메시지 양해 부탁드립니다,,

2023-09-28 09:14 UTC, pilyang requested changes
확인해야할 내용들 코멘트에 남겨두었습니다!

의논할 거리에 대한 의견은 이렇습니다

### Validation

좋아용

### application-dev(-prod).yml

일단 어떤 설정이 잘 되어있는거고 어떤설정이 안되어있는지 모르겠네요... 지금 둘다 잘 설정되어있는것 아닌가요...? prod에 변경되어야 할 내용이 있나요 지금..??

만약 있다면 전 해당 내용도 이 PR에 같이 올라와야 하는게 아닌가 싶습니다.
이전에도 한번 개발서버 관련 파일만 수정이 되어서 같이 머지되었었는데, 그때문에 한단계의 작업이 더 추가되어서 불편함이 있었습니다.... 예상치 못한 일로 운영서버가 죽을수도 있고요.

먼저 개발서버로 잘 작동되는지 확인하고나서 운영에 대한 설정을 건드리려고 하신것 같은데, 그렇게 되면 개발서버에서 잘 됨이 확인되어도 운영서버 설정에 대한 내용만 반영한 피알을 다시 생성해서 개발서버에 머지하고 그담음에 운영배포가 이루어져야 하게되네요...

둘이 한번에 같이된다면

`개발서버 테스트 -> 안됨 -> 수정 -> 잘됨 -> 운영배포`

위처럼 될 프로세스가 운영설정을 따로 한다고 하면

`개발서버 테스트 -> 안됨 -> 수정 -> 잘됨 -> 운영설정머지 -> 운영배포`

로 한단계의 프로세스가 추가되게 됩니다.

추가적으로 해당 기능을 수정하고 디벨롭 하는 중에 다른 작업완료된 기능들을 운영배포할 일도 생길 수 있을것같습니다. 그런데 이렇게 되면 운영서버용 프로퍼티는 배포된 코드와 불일치가 생길 수 있습니다. (개발서버에서 테스트가 완료가 안되었다고 업데이트를 안하고있다면) 그렇게 되면 운영배포시 어차피 진행하던 작업은 놔두고 배포할거니까 신경을 크게 못쓰고 배포를 하게 될 수 있고, 이러한 불일치때문에 운영서버에서 운영프로퍼티를 읽다 큰 불일치가 있다면 서버가 죽거나 하는등의 문제가 있을 것 같습니다.

그래서 앞으로 운영서버와 개발서버의 프로퍼티는 같이 업데이트하면서 관리가 되는게 좋을 것 같습니다.

---

큰기능 작업한다고 힘들었을껀데 성하 엔델 둘다 수고하셨습니다!!

2023-09-30 00:56 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +        return threadId;
이 부분 push 전에 한번 확인했었는데, 영속화 전의 feedThread의 id를 가져와도
영속화 이후라면 똑같이 id가 반환되더라구요?!
그래서 신기해서 냅뒀습니다!

영속성 컨텍스트에 객체가 저장되어서 영속화 이후에 해당 객체를 사용할 때 ID가 있는 채로 불러와지는 것 같아요!

그래도 명시적으로 헷갈릴 수 있을 것 같아서 `savedFeedThread`의 id를 반환하는 것으로 변경했습니다!

2023-09-30 01:01 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +            final String generatedImageUrl = fileCloudUploader.upload(image, assetDirectory + imageDirectory + "/" + UUID.randomUUID());
아 이 부분은 엔델 가고 난 뒤에 제가 혼자 작업했는데, 빠르게 PR 올리려고 하다보니 생각없이 놓친 것 같습니다 ㅠㅠ
이전 PR에서 자세히 설명해주셨는데 작업 당시에 좀 많이 지쳐있어서 빠르게 PR 올리려다가 실수한 것 같네요,,
정말 죄송합니다 😭

앞으로는 추상화에 관해서 더 신경써서 작업해보도록 하겠습니다!!
그럼에도 불구하고 자세하게 코멘트 남겨주셔서 감사합니다 ㅎㅎㅎ 저때문에 너무 많은 리소스 쓰신 것 같아서 죄송하네요..
다음에는 한번 더 생각하고 작업하겠습니다!

2023-09-30 01:04 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +            final String generatedImageUrl = fileCloudUploader.upload(image, assetDirectory + imageDirectory + "/" + UUID.randomUUID());
추가로, `appication-prod path property는 dev에서 이미지 업로드 테스트 후 추가할 예정`에 대한 부분도
작업 당시에는 application-prod 파일에 디렉토리 관련 프로퍼티 설정이 안 되어있다고 생각해서 PR에 저렇게 남겼었는데
다시보니 잘 되어 있네요 ㅠㅠ 이 부분도 그때 심신미약 상태여서 놓친 것 같습니다.. 죄송합니다!

그래도 dev 프로퍼티 테스트 후 prod를 바꾼다는 생각 자체가 잘못된 것 같아서
해당 부분 저도 필립이 설명해준 근거에 납득돼서
> 그래서 앞으로 운영서버와 개발서버의 프로퍼티는 같이 업데이트하면서 관리가 되는게 좋을 것 같습니다.

이 의견에 동의합니다!!

2023-09-30 01:07 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +        });
메소드 분리해서 리팩토링 진행했습니다!! 👍🏻👍🏻👍🏻

2023-10-03 03:24 UTC, SproutMJ approved these changes
docs 해결 감사합니다.

2023-10-04 01:32 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +        });
foreach내부에 들어가는 람다식을 메서드로 분리하는게 어떤가 하는 이야기였는데...ㅎㅎ  바뀐것도 좋네요!!!

2023-10-04 01:39 UTC, pilyang approved these changes
리뷰 반영 확인했습니다!!

고생했어요!

2023-10-04 01:39 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +        });
```java
images.foreEach(image -> saveToThread(image, savedFeedThread));
```

이런식을 이야기한거긴 한데..ㅎㅎ
이것도 `write`메서드 가독성이 충분히 좋아지네요!!

2023-10-04 02:08 UTC, the9kim approved these changes
확인이 늦었네요ㅠ

명절에도 고생한 성하, 엔델

우테코 최고의 커플로 임명합니다!

굿이에요 굿!

2023-10-04 05:32 UTC, merged