[FE]일정 제목이 길때 등록안되는 버그
woowacourse-teams/2023-team-by-team pull request #716
Opened 2023-09-28 05:57 UTC by hafnium1923

## 이슈번호
> close #352 #354 
## PR 내용
전
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/5721c1e8-6720-4ae4-9480-475cb8d719ed)

후
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/d88c737c-2226-40dc-a0be-43f3eab18a99)

![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/6cfa7048-1d76-454f-9304-2ac5681a61a5)

## 참고자료

## 의논할 거리

2023-09-28 16:34 UTC, wzrabbit requested changes
추석에 고생이 많습니다!

일정 등록 `<input />` 창에서 사용자가 250자가 넘는 일정 이름을 등록할 수 없도록 막는 로직이라면 HTML 상으로도 이를 막아주는 건 어떨까? `maxlength="250"` 을 이야기 한 거야

그 외에 오타 하나 있는 것 같아서 코멘트 적었는데, 내가 잘못 본 거라면 따로 코멘트에 남겨줘!

<img src="https://user-images.githubusercontent.com/87642422/233828081-bec1bb8b-7c29-4fac-8c67-0c84bb814ee2.png" width="35px" />

2023-09-28 16:34 UTC, wzrabbit commented on frontend/src/hooks/schedule/useScheduleAddModal.ts
> +            showToast('error', '일정 제목이 최대 글자(200자)를 초과했습니다.');
PR에 루루가 적어준 정보, 그리고 msw의 로직대로라면 `250` 글자여야 할 것 같은데, 맞을까?
```suggestion
            showToast('error', '일정 제목이 최대 글자(250자)를 초과했습니다.');
```

2023-10-04 01:07 UTC, hafnium1923 commented on frontend/src/hooks/schedule/useScheduleAddModal.ts
> +            showToast('error', '일정 제목이 최대 글자(200자)를 초과했습니다.');
수정할게여

2023-10-04 05:20 UTC, suyoungj approved these changes

2023-10-04 06:50 UTC, wzrabbit approved these changes
<img src="https://user-images.githubusercontent.com/87642422/233828081-bec1bb8b-7c29-4fac-8c67-0c84bb814ee2.png" width="35px" />

수고하셨읍니다

2023-10-04 06:51 UTC, merged