[BE] 피드에서 이미지 조회 기능 구현
woowacourse-teams/2023-team-by-team pull request #723
Opened 2023-10-05 03:25 UTC by SproutMJ

## 이슈번호
#717 

## PR 내용
1. 피드 조회 시 이미지를 추가로 조회합니다.
2. 90일 이후 만료되는지 테스트하기 위해 clock을 모킹했습니다.
3. mapToFeedImageResponse에서 각 피드의 이미지를 각각 데이터베이스에서 조회

## 참고자료

## 의논할 거리

2023-10-05 03:26 UTC, sh111-coder approved these changes
Pair로 작업해서 Approve 합니다!

2023-10-05 04:25 UTC, sh111-coder requested changes
CI 이슈로 일단 RC 해놓을게요

2023-10-05 08:15 UTC, pilyang requested changes
성하엔델 작업 고생하셨어요!!!

지금 테스트 터지는거 수정하면서 시간되면 코멘트 단 부분들도 확인 부탁드립니다.

일부 수정되면 좋을것같은 내용도 있고, 아무래도 큰 작업이였다보니 궁금한 내용들도 있어서 궁금한것들 코멘트로 남긴것들도 있어요.

추가적인 궁금한 사항이 있어서 아래 남깁니다!!!

---

아직 주기적으로 이미지확인해서 날리는 구현은 안한거죠???
기능도 이번 PR에 포함은 아니고 시간문제도 있고 해서 여기 포함이 안된거로 생각중인데 맞는지 확인 부탁드립니다!!

2023-10-05 08:15 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/feed/domain/image/FeedThreadImage.java
> +public class FeedThreadImage extends BaseEntity {
요건 궁금한 내용인건데

`FeadThreadImage` <-> `FeedThread`가 아니라
`FeedThreadImage` -> `FeedThread`로 한 이유가 있나요..?

양방향으로 하고 FeedThread가 FeedThreadImage리스트를 `EAGER`로 가지면 날리는 쿼리 수가 많이 줄어들것같은데,, 요래 하신 이유가 궁금합니다.
피드스레드를 조회하면서 피드스레드이미지를 조회하지 않을 경우는 없을것같아서요.

2023-10-05 08:15 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +
이친구 역할은 먼가요????

2023-10-05 08:15 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/global/domain/BaseEntity.java
> +    }
요렇게 바꾼 이유가 궁금합니다!!!

2023-10-06 04:32 UTC, the9kim approved these changes
재택으로 열심히 페어한다고 수고 많으셨어요!

필립이 질문 한 것 중에 저도 궁금한게 있었는데, 답글 달아주시면 확인해보겠습니다!

언능 오류 해결하고 S3에 이미지 올립시다!

2023-10-06 04:32 UTC, the9kim commented on backend/src/test/java/team/teamby/teambyteam/common/builder/TestFixtureBuilder.java
> +    public FeedThreadImage buildFeedThreadFeedThreadImage(final FeedThread feedThread, final FeedThreadImage feedThreadImage) {
'FeedThreadFeedThread'라는 Naming은 의도 하신거겠죠?..

2023-10-06 07:53 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/common/builder/TestFixtureBuilder.java
> +    public FeedThreadImage buildFeedThreadFeedThreadImage(final FeedThread feedThread, final FeedThreadImage feedThreadImage) {
FeedThread, FeedThreadImage라는 뜻입니다.

2023-10-06 07:54 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/global/domain/BaseEntity.java
> +    }
ci 테스트 통과를 위해서 했던 부분인데 결과적으로는 무의미해서 롤백했습니다.

2023-10-06 08:00 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +
일단 두괄식으로 결과만 먼저 말씀드리자면, 90일 후 이미지가 만료되는 부분을 테스트하기 위한 부분입니다.
알아보던 중 LocaldateTime.now() 등 static한 부분을 모킹하는 것이 좋지 않다는 것을 알게 되었고, clock.instant()를 모킹하는 것으로 방향을 선회하게 되었습니다.

이런 구조로 되는 경우 clock을 서비스에까지 주입을 시켜주어야겠지요? 그래서 ClockConfiguration으로 빈을 만들고 주입시키는 것입니다.

2023-10-06 08:01 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/domain/image/FeedThreadImage.java
> +public class FeedThreadImage extends BaseEntity {
등록에서 변경했습니다.

2023-10-06 08:07 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
> +
순서 변경 했습니다.

2023-10-06 08:08 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
> +        final String createdAt = feed.getCreatedAt().format(dateTimeFormatter);
사라진 부분입니다. 바뀐 부분은 어떤지 봐주시면 좋을 것 같네요.

2023-10-06 08:36 UTC, pilyang approved these changes
테스트 깨지는거 해결된것과 코멘트들 확인 했습니다.!!

테스트 깨지던 이유랑 해결 방법은 후에 공유 부탁드립니다ㅏ.

2023-10-10 01:27 UTC, sh111-coder approved these changes
good!

2023-10-10 01:51 UTC, merged