[BE] Icalendar 외부 배포 및 배포 url 조회 api 구현
woowacourse-teams/2023-team-by-team pull request #725
Opened 2023-10-05 04:28 UTC by pilyang

## 이슈번호
> close #724 

## PR 내용

- Icalendar (.ics) 파일 배포 기능 구현
- Icalendar 관련 패키지 생성
  - 의존성 : `icalendar` -> `schedule`, `teamplace`, `filesystem`

### Icalendar 파일 파싱

- [ical4j](https://github.com/ical4j/ical4j) 오픈소스 라이브러리 사용  
- 파싱하는 기능은 interface로 추상화 하고, ical4j를 사용하는 구현체 생성 (혹시나 사용못하는 상항이 생길 시 따로 구현체 구현하면 되도록 구현)  

### Icalendar 파일 배포

- FileCloudUploader를 통하여 s3배포
- byte[]를 인자로 받는 upload 메서드 추가

### ics파일 생성 및 배포 플로우

- 생성 & 배포 로직은 `IcalendarPublishService`를 통해 구현
- `IcalendarEventListener`에서 발행된 이벤트에 맞춰 PublishService 수행

#### 생성 플로우

생성되는 경우는 아래와 같음
1. 팀플레이스 생성시
  - TeamPlaceCreateEvent 발행 -> EventListener에서 CreateIcalendarEvent로 변환하여 재 발행
2. ical publish url조회하였는데, 아직 배포생성이 안되었을때
  - CreateIcalendarEvent 발행
3. 일정이 변동되어있는데, 아직 ics배포가 되지 않았을때

생성 및 배포 이벤트리스너는 비동기(`Async`)로 수행
   - 일정변동등의 이벤트처리가 기존에 있었고 (지금은 없지만) 이후 생성이 된다 해도 다른 우리서비스의 주요 비지니스로직들과 같은 스레드에서 실행이 되어 지연되는 상황이 없어야 한다고 생각. (여기서의 지연은 우리의 주요 비지니스 로직의 지연을 의미)

- Async테스트
  - `IcalendarEventListnerTest`에서는 SyncTaskExcutor를 Bean을 강제로 만들어줘서 동기로 처리하도록 변경
  - acceptance테스트에서는 실제 환경과 같아야한다고 생각해서 AsyncAspect AOP를 구현하여 생성이 된 이후 Async 어노테이션이 달린 메서드 종료 후 다음 테스트코드가 실행되도록 구현

## 참고자료

[ical4j 공식문서

## 의논할 거리

2023-10-05 04:37 UTC, pilyang commented
급하게 처리해야한다고 1500줄pr 죄송함다;;

문서화 테스트도 포함했습니다.

2023-10-05 08:08 UTC, sh111-coder requested changes
안녕하세요 필립, 로이!!
진짜 Icalendar 작업 너무 힘들었을텐데 잘 해주셔서 감사합니다!!
코드 보니까 진짜 작업량 대단하시네요.. 🙃 존경합니다...
다 처음 해보는거라 생소하고 레퍼런스 찾기도 힘들었을텐데 대단하십니다,, 👍🏻👍🏻

코드 보면서 수정 제안 코멘트랑 배경 지식이 없어서 궁금한 질문 몇 가지를 남겼어요!
답변 or 수정 해주시면 감사하겠습니다!!

다시 한번 정말 수고하셨어요! 멋있습니다.. 👍🏻👍🏻👍🏻

2023-10-05 08:08 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarPublishServiceTest.java
> +            verify(fileCloudUploader).upload(icalBytesCaptor.capture(), fileNameCaptor.capture());
이 부분 처음봐서 설명해주실 수 있을까요?!

2023-10-05 08:08 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarServiceTest.java
> +        assertThat(publishedIcalUrl).isEmpty();
검증 부에 이벤트 발행 검증도 추가되면 좋을 것 같아요!

2023-10-05 08:08 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/icalendar/domain/ical4j/ICal4jParserTest.java
> +class ICal4jParserTest {
오 해당 테스트 보니까 전체적인 파일 구조, 어떻게 파싱하는지 잘 이해되는 것 같아요! 👍🏻👍🏻👍🏻👍🏻

2023-10-05 08:57 UTC, pilyang reviewed
코멘트 주신부분 설명 / 반영 추가했습니다!

2023-10-05 08:57 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/icalendar/application/IcalendarPublishService.java
> +                                    .orElseThrow(() -> new IllegalArgumentException(TEAM_PLACE_NOT_CREATED_EXCEPTION_MESSAGE + teamPlaceId));
네 성하가 이해한대로 이미 생성이 되었어햐나는데, 조회가 안되는 상황이여서 이건 서버측 문제임으로 사용자에게 표현하기 위한 커스텀익셉션이 아닌 표준예외(IllegalArgumentException)을 던져서 저희 개발자들이 확인할 수 있도록 처리했습니다.
TeamplaceException.NotFoundException은 404를 응답하기 위한 예외로 사용되고 있습니다.
이부분은 GlobalExcpetionHandler에서 잡아서 사용자에게 알려주기 위한 예외는 아닙니다. 시스템 코드상 에러이고 이런부분은 커스텀보다 표준예외가 그 의미를 더 명확히 잘 전달해준다고 생각합니다.

아 추가적으로 해당 부분은 관련된 요청-응답이 없이 내부적으로 돌면서 처리가 되는데 GlobalExceptionHandler에서 잡힐지가 모르겠네요... 아마 안잡힐것같기도 하고 그럼 로깅은 안될것같은데 로깅할 수 있도록 로깅 추가하도록 하겠습니다.

2023-10-05 08:57 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/icalendar/domain/ical4j/VEventParser.java
> +        final VEvent vEvent = new VEvent(startTemporal, endTemporal, title);
네네 VEvent하나가 일정 (Schedule하나로 이해하면 됩니다.)

캘린더 정보를 의미하는 친구로는 이런식으로 하나의 컴포넌트가 아닌 캘린더 통합으로 있고, 저희가 추가로 사용한것중에는 타임존 관련 설정인
`VTIMEZONE`이 있습니다.

2023-10-05 08:57 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/icalendar/acceptance/IcalendarAcceptanceTest.java
> +    @TestConfiguration
블로깅 생각중입니다..ㅎㅎ

2023-10-05 08:57 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarEventListenerTest.java
> +    }
동기처리부분은 `Excutor`를 `SyncTestExcutor`로 강제로 보내주는식으로 해서 되는것이고,
reset부분은 이전 테스트의 mock에대한 정보가 다른스레드로 있어서 남아있어서 초기화 해주는 작업이라고 생각하면 될 것 같습니다.

2023-10-05 08:57 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarEventListenerTest.java
> +        TestTransaction.end();
네네 해당부분이 없으면 @TransactionalEventListener가 after_commit이기 때문에 이벤트 리스너가 실행이 안됩니다.

2023-10-05 08:57 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarPublishServiceTest.java
> +                        return "https://test.com/test.ice";
앗 ics인데 오타네요...ㅎㅎ 수정할께요!!

2023-10-05 08:57 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarPublishServiceTest.java
> +            verify(fileCloudUploader).upload(icalBytesCaptor.capture(), fileNameCaptor.capture());
목킹한 객체를 테스트할때 보통 verify로 메서드 호출 여부에 대해서 테스트가 가능한데, 이때 해당 메서드 호출에 인자로 전달된 값을 잡을 수 있는 기능입니다.
이런식으로 하면 인자로 전달된 값또한 검증에 이용해서 정상적인 데이터로 목킹한 객체에 메소드를 호출하였는지 검증이 가능합니다.

아래 보면 
```java
final String actualUploadedFileName = fileNameCaptor.getValue();

assertThat(actualUploadedFileName).endsWith(publishedIcalendar.getIcalendarFileNameValue());
```

로 인자를 가져와서 검증하는 부분이 있습니다.

2023-10-05 08:57 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarServiceTest.java
> +        assertThat(publishedIcalUrl).isEmpty();
추가했습니다!

2023-10-05 08:57 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/icalendar/domain/ical4j/ICal4jParserTest.java
> +class ICal4jParserTest {
로이형과 함께 머리 깨져가며 했습니다ㅠㅜㅜㅋㅋㅋㅋ

2023-10-05 10:30 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/icalendar/acceptance/IcalendarAcceptanceTest.java
> +    @TestConfiguration
좋은데요?

2023-10-05 10:32 UTC, sh111-coder commented on backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarEventListenerTest.java
> +        TestTransaction.end();
아하 그렇군요!! 한번 해보겠슴다!! 👍🏻

2023-10-05 11:06 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/icalendar/application/IcalendarEventListener.java
> +    }
역시 필립 근거가 있었군요!! 다 이해했습니다!
처음에는 SRP를 지켜야한다고 생각해서 해당 방향으로 제안드렸는데
확실히 확장될 때 계속 중복되는 오버로딩이 발생할 수도 있을 것 같네요,, 어렵네요 ㅠㅠ

해당 방법대로 하면 이벤트 리슨 로직의 오버로딩이 여러 번되는 것은 막지만,
결국 변환하는 이벤트 발행이 여러 번되긴 해서 둘 중에 정답이 있는 건 아닌 것 같아요 ㅠㅠ
(물론 둘 중에는 발행이 여러 번되는 게 좀 더 나은 느낌인 것 같습니다!)

그래도 SRP를 못 지키고 있는 느낌이라서 
다른 도메인의 Event를 리슨하고 CreateIcalendarEvent로 이벤트를 발행하는 역할을 가진 클래스를 만드는 것도
방법이 될 수 있을 것 같아요!

`IcalendarEventManager`? 이런 느낌으로..? 만들어서 이벤트 리슨 & 발행을 동시에 하는
 중간 클래스를 두는 것도 방법일 수 있을 것 같아요!

그러나 아직은 다른 도메인의 이벤트가 TeamPlaceCreate 한 개라서 조금 오버인 것 같긴 합니다!

그래서 제가 작업했으면 아직은 중복되는 코드가 별로 없고 SRP를 지키기 위해서 우선 오버로딩을 진행하고,
인지를 한 후에 이후에 이벤트가 추가 되면 중간 객체를 두는 식으로 진행할 것 같아요!!

필립이 작업한 부분도 충분히 근거가 있으니 이대로 두고 이후에 이벤트가 추가되었을 때
어떻게 할지? 방향만 인지하고 그대로 둬도 될 것 같습니다!!

2023-10-06 00:29 UTC, sh111-coder approved these changes
질문에 대한 답변도 잘 해주시고 
중요한 부분은 다 구현이 잘 됐다고 생각하여 Approve 합니다!!

수고많으셨어요 ㅎㅎㅎ

2023-10-06 02:51 UTC, the9kim approved these changes
어찌 이리 빠르게 구현하셨는지 놀라울 따름입니다!

가능할까 싶은 내용들이 실제로 구현된 걸 보니 가슴이 웅장해지네요!

고생많으셨습니다!!

2023-10-06 02:51 UTC, the9kim commented on backend/src/main/java/team/teamby/teambyteam/icalendar/application/IcalendarEventListener.java
> +    }
Event 리슨과 발행을 동시에 하는게 (SRP)측면에서  조금 어색해 보이기도 하네요.

성하가 말한대로 리슨 -> 발행 역할을 하는 별도 클래스를 만드는 것도 아주 좋은 방법인 듯 합니다!

다만 아직까지는 비교적 로직이 단순하기 때문에 이 방향으로 가고,

추후 이벤트가 추가되었을 때 클래스 분리를 하는 쪽이 괜찮을 듯합니다!

2023-10-06 04:54 UTC, merged