[FE] ICalendar 내보내기 기능 구현
woowacourse-teams/2023-team-by-team pull request #726
Opened 2023-10-05 08:39 UTC by suyoungj

# [FE] ICalendar 내보내기 기능 구현
## 이슈번호
> close #721 

## PR 내용
- ICalendar 내보내기 기능 구현
- 404 에러 건들면서 기존 에러 처리 로직 리팩터링 했습니다
- margin 대신 쓸 수 있는 Spacing 컴포넌트 추가했습니다 

## 참고자료
https://velog.io/@cnsrn1874/breaking-react-querys-api-on-purpose

## 의논할 거리
- 일단 내보내기 버튼 우측에 위치시켰습니다 논의 후 수정 예정
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/729e0a97-dfdb-4bcc-ba5a-b15ad947991e)
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/9f84f61d-a04b-4346-a3b2-2b8440c40cd5)
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/a5d533ac-1f61-4fad-8977-4ee1d8dbf78c)

2023-10-06 02:27 UTC, hafnium1923 requested changes
넘모좋아요

2023-10-06 02:27 UTC, hafnium1923 commented on frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.tsx
> +          내보낸 파일(.ics) 경로
내보낸 파일보단 일정파일(.ics) 경로 는 어때?

2023-10-06 02:27 UTC, hafnium1923 commented on frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.tsx
> +        <S.UserGuideLink
<img width="280" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/b4499bec-3807-464d-bb7b-32e30ff14a06">
의도한 건지 모르겠는데 깨져요!

2023-10-06 02:27 UTC, hafnium1923 commented on frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.styled.ts
> +  transform: translate(-50%, -50%);
다른 모달들처럼 모아보기에서는 캘린더 영역에 모달이 위치하면 좋을 것 같은데 어떻게 생각해?

2023-10-06 04:47 UTC, wzrabbit requested changes
신기한 기능을 다루는 PR이네~ 수고 많았습니다
코멘트 몇 개 적어봤어
<img src="https://user-images.githubusercontent.com/87642422/233928933-505b06b9-5460-4d73-bf1b-4addd84c9e9a.png" width="35px" />

2023-10-06 04:47 UTC, wzrabbit commented on frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.tsx
> +          >
우선 툴팁 사용한 거 너무 좋은 것 같아!
"일정 내보내기" 라는 메뉴만 봤을 때 사용자 입장에서는 어떻게 내보낸다는 거지...? 라고 의문을 가지기 쉬운 메뉴같은데
이렇게 툴팁을 사용하니까 사용자 입장에서 아하~ 하고 이해할 수 있을 것 같아

지금도 충분히 좋지만 여기에 조금 개선을 더하면 좋을 것 같아서 제안할 만한 거 적고갈게!
1. 툴팁 버튼에 `cursor: help` css 속성을 추가하기
2. 툴팁 텍스트에 `role="tooltip"` 속성 추가하기
3. 툴팁 Wrapper에 `tabindex={0}` 을 사용하여 포커싱이 가능하게 만들고, `onFocus` 와 `onBlur` 시에도 state 변경이 일어나도록 반들기

특히 3번은 적용하면 아래와 같이 스크린리더 사용자가 hover를 하지 않고 tab으로 툴팁을 선택해도 온전하게 정보를 알려줄 수 있어서 좋을 것 같아 (음성 있으니 소리 켜줘)

https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/10901842-dfbe-4442-aaf9-c62216a84f3b

2023-10-06 04:47 UTC, wzrabbit commented on frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.styled.ts
> +  height: 100%;
Line 6이랑 Line 7 사이에 빈 줄 하나 삽입해 주면 좋을듯!
우리가 정했던 컨벤션이니까

2023-10-06 04:53 UTC, suyoungj commented on frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.styled.ts
> +  transform: translate(-50%, -50%);
<img width="1054" alt="스크린샷 2023-10-06 오후 1 51 41" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/1ea54e80-b9da-40ce-b5b6-7f85306acf63">

2023-10-06 07:12 UTC, suyoungj commented on frontend/src/components/common/Spacing/Spacing.styled.ts
> +    }
적어주지 않아도 상관없지만, vertical | horizontal을 좀 더 명시적으로 구분하고 싶어서 이렇게 작성했어!

2023-10-06 07:13 UTC, suyoungj commented on frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.styled.ts
> +  width: 200px;
100%는 컨텐츠가 포함되지 않는 영역도 클릭이 가능해서 약간 늘리는 방식으로 수정했어 혹시 깨지면 알려줘~~

2023-10-06 07:13 UTC, suyoungj commented on frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.tsx
> +          >
몰랐던 부분이 많네 👍👍👍
접근성 측면은 생각 못해봤는데 앞으론 신경써볼게!

2023-10-06 07:41 UTC, wzrabbit requested changes

2023-10-06 07:41 UTC, wzrabbit commented on frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.styled.ts
> +  width: 200px;
그래서 길이를 딱 맞췄구나
약간 늘린 거 확인했는데, 이렇게 하면 깨지지는 않겠지만 여전히 사용자마다 꽤나 많은 빈 픽셀이 hover되는 등 안 맞는 부분이 생길 것 같다는 느낌이 들어

컨텐츠가 포함되지 않는 영역도 클릭이 되는 게 문제점이라면, 정확히 컨텐츠가 차지하는 만큼만 클릭이 가능하도록 수정해보면 되지 않을까?
이 `<a>` 는 Flex 내부에 있으니까...

```tsx
export const UserGuideLink = styled.a`
  align-self: flex-start;
`;
```

이러한 방법을 시도해 볼 수도 있어 보여!

2023-10-06 07:41 UTC, wzrabbit commented on frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.styled.ts
> +export const shortCutText = css`
```suggestion
export const shortcutText = css`
```

"shortcut" 은 한 단어니까, 이렇게 제안해봤어. 어때?

2023-10-06 09:13 UTC, hafnium1923 approved these changes
수고하셨슴당

2023-10-07 06:57 UTC, pilyang commented on frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.tsx
> +                  </Text>
아 참고로 구글의 캘린더, 애플의 캘린더가 맞는 표현일 것 같습니다!!
애플 켈린더의 명칭이 Icalendar가 아니라 calendar로 되어있네여, ical (icalendar)는 일정 정보 전달을 위한 표준 형식을 의미한다고 생각하면 될 것 같습니다.

2023-10-09 10:34 UTC, wzrabbit approved these changes
수고 많았습니다!

2023-10-10 01:23 UTC, merged