[FE] 이미지 포함한 스레드 등록 구현
woowacourse-teams/2023-team-by-team pull request #727
Opened 2023-10-05 10:35 UTC by hafnium1923

# [FE|BE|ALL] PR 타이틀 
## 이슈번호
> close #719 

## PR 내용
msw에서 multipart formdata로 접근하는 방식이 개 더럽습니다. 이게 제 최선이에요
마찬가지 이유로 multipart formdata로 이미지 접근이 어려워 이미지 필드가 있으면 몇개든 그냥 무조건 1개 올라가도록 구현해두었습니다. 이미지 여러개를 올렸을 때 몇개인지 구분하기 어렵게되어있더라구요 참고 부탁드립니당

## 참고자료

## 의논할 거리

2023-10-06 01:51 UTC, suyoungj requested changes
👍

2023-10-06 01:51 UTC, suyoungj commented on frontend/src/apis/http.ts
> +  postFormData: async (url: RequestInfo | URL, body: FormData) => {
기존 post 메서드 재활용할 수 있을 것 같아! 이런 식으로 리팩토링해도 좋을듯?

```ts
const createPostHeaders = (body: unknown) => ({
  headers: {
    'Content-Type':
      body instanceof FormData ? 'multipart/form-data' : 'application/json',
    Authorization: `Bearer ${localStorage.getItem(
      LOCAL_STORAGE_KEY.ACCESS_TOKEN,
    )}`,
  },
  body: body instanceof FormData ? body : JSON.stringify(body),
});

post: async (url: RequestInfo | URL, body: unknown) => {
    const response = await fetch(BASE_URL + url, {
      method: 'POST',
      ...createPostHeaders(body),
    });

    if (!response.ok) {
      throw new Error('네트워크 통신 중 에러가 발생했습니다.');
    }

    return response;
  },
```

2023-10-06 01:51 UTC, suyoungj commented on frontend/src/mocks/handlers/feed.ts
> +      for (let i = 0; i < parts.length; i++) {
고생했구만 🥲

2023-10-06 01:51 UTC, suyoungj commented on frontend/src/hooks/queries/useSendNoticeThread.ts
> +      const formData = new FormData();
아래에 공백 한 줄 추가되면 좋을듯?

2023-10-06 02:06 UTC, hafnium1923 commented on frontend/src/mocks/handlers/feed.ts
> +            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYZjvO1QuvfgCfQxBwwzmJcHIT5pTXIBGOLeyBDIbZknn6Dhkd40WrU0ZCdjt-IoXLzI0&usqp=CAU';
이 밑에 break 문 있어야 할듯

2023-10-06 02:42 UTC, hafnium1923 commented on frontend/src/apis/http.ts
> +  postFormData: async (url: RequestInfo | URL, body: FormData) => {
좋아요! 반영하겠습니당

2023-10-06 10:55 UTC, wzrabbit reviewed
루루! 고생한 흔적이 보이는 코드를 많이 짰더라
수고많았어
코멘트만 확인해 주면 Approve 누를게

<img src="https://user-images.githubusercontent.com/87642422/233828081-bec1bb8b-7c29-4fac-8c67-0c84bb814ee2.png" width="35px" />

2023-10-06 10:55 UTC, wzrabbit commented on frontend/src/mocks/handlers/feed.ts
> +      for (let i = 0; i < parts.length; i++) {
진짜 `------` 같은 거 보고 놀랐잖어...
고생 꽤나 했겠다

2023-10-06 10:55 UTC, wzrabbit commented on frontend/src/mocks/handlers/feed.ts
>        };
나도 바이너리 데이터 관련해서 검색해봤는데 바이너리 데이터를 msw에서 직접 해석하는 건 너무 힘들어보이는데다, 모킹 코드에 그렇게까지 신경쓸 필요까진 없어보이더라
코드가 있긴 한데 엄청 복잡하고 긴데 동작 결과를 보면 되는거니까 루루가 구현했던 대로 적절히 결과 이미지를 적절히 반환하는 걸로 충분한 것 같아

여기서 `Content-Disposition: form-data; name="images";` 의 개수가 곧 이미지 수라는 걸 알 수 있어 보여서, 이미지의 개수를 찾고 그만큼의 길이의 이미지 배열을 덮어씌우도록 아래와 같이 구현해 뒀는데, 그냥 참고만 해 줘!
`contentValue` 도 규칙 찾아서 파싱해 봤는데, 루루가 적절히 판단해서 msw 로직을 변경해 볼 것인지, 그대로 둘 것인지 결정해 주면 될 것 같아
확인했다는 표시로 코멘트 달아주면 Approve 누를게

```tsx
// formData를 추출
const formData = new TextDecoder('utf-8').decode(bufferData);

const imageCount = formData
  .split('\r\n')
  .filter((line) =>
    line.startsWith('Content-Disposition: form-data; name="images"'),
  ).length;

const contentValue = formData
  .split('Content-Disposition: form-data; name="content"\r\n\r\n')[1]
  .split('\r\n------WebKitFormBoundary')[0];

const newNoticeThread = {
  id: Date.now(),
  type: 'thread',
  authorId: 1,
  authorName: '유스',
  isMe: true,
  profileImageUrl: 'https://avatars.githubusercontent.com/u/49154600?v=4',
  createdAt: '2023-08-01 12:00' as YYYYMMDDHHMM,
  content: contentValue,
  images: Array.from({ length: imageCount }).map((_, index) => ({
    id: index,
    isExpired: false,
    name: '목데이터',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYZjvO1QuvfgCfQxBwwzmJcHIT5pTXIBGOLeyBDIbZknn6Dhkd40WrU0ZCdjt-IoXLzI0&usqp=CAU',
  })),
};
```

2023-10-09 13:00 UTC, hafnium1923 commented on frontend/src/mocks/handlers/feed.ts
>        };
확실히 너가 한게 더 이쁘긴하다 역시 요토... 처음부터 맡길걸 😭😭😭

2023-10-10 04:26 UTC, wzrabbit approved these changes
수 고 하 셨 습 니 다

2023-10-10 04:26 UTC, merged