[FE] 스레드에서 이미지를 조회할 수 있는 기능 추가
woowacourse-teams/2023-team-by-team pull request #733
Opened 2023-10-06 02:17 UTC by wzrabbit

# [FE] 스레드에서 이미지를 조회할 수 있는 기능 추가
## 이슈번호
> 해당되는 모든 번호를 태그해주세요

## PR 내용

## 참고자료

## 의논할 거리

2023-10-06 04:01 UTC, suyoungj requested changes
이미지 확인 모달도 잘 나오네 👍

<img width="1476" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/625664b1-e439-4a72-b759-7b5be016255d">

직접 써보니까 파일 이름, 닫기 버튼, 하단 페이지 번호가 너무 크고 굵은 느낌인데 어때?
Dimmed 영역도 너무 짙어서 아예 다른 앱을 쓰는 느낌이 들어

2023-10-06 04:02 UTC, hafnium1923 requested changes
> 그래서 스크롤이 생겨도 썸네일 리스트가 가려지지 않도록 padding-bottom: 20px 를 적용해 주었는데, 이 경우에는 스크롤이 생겼을 경우 어색하지 않지만(그림 2) 반대로 스크롤이 없는 경우 하단에 다소 어색할 수 있는 여백이 생기는 것 같아(그림 3). 어떻게 하면 좋을까?

나는 사용자가 보았을 때 이미지가 있기 때문에 다른 말풍선과 여백이 다르다고 생각할 것 같아서 괜찮은 것 같은데

> 이렇게 하면 펼쳐보기 버튼을 누르지 않고도 이미지가 있다는 사실을 사용자에게 알릴 수 있고 사용자에게 이미지를 보여주기도 편해보여서. 괜찮은 해결 방법 같을까?

지금처럼 보여주는 것에 대해서는 나는 좋은 것 같아.   다만 좀 어색해 보이는 부분은 코멘트로 달아두었어! 깨지는 것 아니면 지금 당장 엄청 필요한 부분은 아니니 반영하지 않고 이슈만 파두어도 좋아. 어쨌든 빠르게 구현해서 최소한의 기능이 돌아가는지 확인하는게 먼저니까! 
또한 유스의 의견처럼 생각보다 이미지모달에 대해서 좀 수정해야할 부분이 보이긴해. 다만 이건 이 PR에서 한번에 고치기엔 PR의 목적과 다르기도 해서 새로 이슈를 파서 진행하는게 좋을 것 같아.

2023-10-06 04:02 UTC, hafnium1923 commented on frontend/src/components/feed/NoticeThread/NoticeThread.tsx
> +              <ThumbnailList
<img width="338" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/0f64ce98-dec7-48cd-ab6b-c29c3c99719f">

개인적으로  공지용 썸네일은 크기가 더 작아도 될 것 같다는 느낌이 들어!
적어도 모아보기에서 보는 공지는 이미지 4개를 올리더라도 스크롤이 안생기면 더 자연스러울 것 같거든.

이번 PR에서 반영하기 애매해보이면 이슈만 새로 파도 될 것 같아!

2023-10-10 04:19 UTC, wzrabbit reviewed
코멘트의 일부분에 한해 반영 완료!
나머지는 지금 당장 구현하기 힘든 기능도 있었고, 의견을 묻고자 하는 코멘트도 있으니 봐주고 답변 달아주면 다시 반영해볼게

<img src="https://user-images.githubusercontent.com/87642422/233928933-505b06b9-5460-4d73-bf1b-4addd84c9e9a.png" width="35px" />

2023-10-11 07:26 UTC, hafnium1923 requested changes

2023-10-11 07:26 UTC, hafnium1923 commented on frontend/src/components/common/ExpandButton/ExpandButton.tsx
> +  theme: 'white' | 'blurple';
일리있는 이야기야! 원래는 공지에서도 expandButton을 사용했기 때문에 포괄적인 이름을 사용했었는데 내 생각에도 앞으로피드 한정으로 될 것 같아. 그래서 요술토끼가 제안해준 대로  common 폴더에서 이 컴포넌트를 제외하고, 이름도 ThreadExpandButton 과 같이 좀 더 세부적인 역할을 설명하는 한정적인 이름으로 변경하는거 찬성합니다~!!

2023-10-11 07:26 UTC, hafnium1923 commented on frontend/src/components/feed/NoticeThread/NoticeThread.tsx
> +              <ThumbnailList
> 가능하면 일반 스레드의 썸네일 리스트와 디자인이 통일되었으면 좋겠어

나는 공지의 썸네일 크기가 지금보다 줄어든다고 일반스레드와 디자인이 어색하게 보일 것 같진 않아. 
애초부터 공지와 일반 스레드가 다르게 생겼기 때문이야! 또한 썸네일 컴포넌트가 아예 다른 모양으로 보여주는 것이 아닌 정말 사진 크기만 줄이는 것이니 생소하다고 느끼지 않을 것 같아. 
바꾸기 전 UI 처럼 공지가 배경을 제외하고 보여주는 것이 거의 비슷하다면 요토의 의견에 동의했을 것 같지만 지금처럼 완전 다른 형식이라고 보여주고 있을 땐 문제 없을 것이라고 생각해

2023-10-11 07:26 UTC, hafnium1923 commented on frontend/src/components/feed/NoticeThread/NoticeThread.tsx
> +              <ThumbnailList
스크롤은 아쉽긴 하네,, 뭐 나중에 우리가 써보면서 불편함이 생긴다면 그때가서 다른배치를 고민해보자!

2023-10-11 07:26 UTC, hafnium1923 commented on frontend/src/components/feed/Thread/Thread.tsx
> +          <S.ContentWrapper>
나는 바뀐 디자인도 이뻐보이네! zindex를 사용하는 다른 컴포넌트를 보았을 때 문제도 없어보이고! 일단은 이렇게 하고 나중에 시간나면 다시 생각해보자 ㅋㅋ

2023-10-11 07:31 UTC, hafnium1923 commented on frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.styled.ts
> +  padding: 20px;
> X 버튼을 이미지 썸네일 안으로 가져와서 overflow를 피하는 방법은 안 될까?

어떤 말인지 조금만 더 자세히 설명해줄래?! `DeletableThumbnail`을 버리고 이미지 등록시에는 X컴포넌트를 따로 보여주겠다는 이야기일까?
그런데 개발서버에서는 해당 문제가 보이지 않는데 괜찮다면 원래대로 롤백하는 것도 하나의 해결 방법이 될 수 있을 것 같아!

<img width="404" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/3edab1ea-b424-4711-9cd4-51fe3d55a9f0">

2023-10-12 05:29 UTC, wzrabbit commented on frontend/src/components/feed/NoticeThread/NoticeThread.tsx
> +              <ThumbnailList
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/38941d29-2ef8-43b7-af6a-09cb80a9f543)

2023-10-12 07:37 UTC, suyoungj reviewed
<img width="543" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/5b293fbe-7a6c-423c-9008-18594de9de2e">

모서리가 각져있는데 사진 없는 스레드처럼 둥글게 만드는건 어때?

2023-10-12 07:37 UTC, suyoungj commented on frontend/src/components/feed/Thread/Thread.tsx
> +              <Text size="xl" css={S.contentField(threadSize, isMe)}>
size랑 css가 겹치지 않을까??

2023-10-13 04:42 UTC, hafnium1923 approved these changes
오랜기간 수고많았어!

2023-10-13 04:42 UTC, hafnium1923 commented on frontend/src/components/feed/NoticeThread/NoticeThread.tsx
> +              <ThumbnailList
맘에든다 이쁘다 고생했어~!~!

2023-10-13 05:46 UTC, wzrabbit commented
이미지 모달 디자인 관련한 부분은 따로 이슈 파는 것으로 합의 완료!

2023-10-13 05:48 UTC, suyoungj approved these changes

2023-10-13 05:48 UTC, merged