[BE] 공지 등록 api 리팩토링
woowacourse-teams/2023-team-by-team pull request #740
Opened 2023-10-06 10:38 UTC by sh111-coder

## 이슈번호
> closed #728 

## PR 내용

* 기본적인 로직은 피드 등록 로직과 거의 동일해서 거의 복붙함.

## 참고자료

## 의논할 거리

* 거의 복붙하다보니 이게 맞나? 싶긴했지만,  애초에 '피드(스레드)'와 '공지'를 다른 도메인으로 설계했고,
* 이후에 공지와 피드(스레드)의 정책이 바뀔 수 있기 때문에 나누는 것이 좋아보였음!
* ex : 만약 공지의 이미지 개수가 1개로 제한되고, 용량도 적게 제한되도록 정책이 변경된다면 피드까지 변경되어야 함.

2023-10-07 15:37 UTC, pilyang requested changes
고생하셨습니다 성하!!!

의견(의논할 거리)남겨주신 부분에서는 일단 도메인적으로 저희가 분리하여 생각하기로 했기에 중복이 발생하여도 달라질 수 있음을 감안하여 동의하는 바입니다.

그런데, 일부 부분에서는 파일 시스템이나, 유틸적인 측면은 혹시 따로 분리할 수  있지 않을까 하는 생각이 들긴해서 코멘트를 남겼는데, 해당 부분 동의하시면 수정하여 주시거나, 반대면 성하 의견 코멘트로 남겨주시면 확인해보겠습니다!!!

2023-10-07 15:37 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +        }
이정도는 FileUtile정도로 생각해서 파일관리 유틸 클래스를 만들어 static 메서드로 만든 후 피드등에서도 같이 재사용 해도 되지 않을까 하는 생각입니다.

2023-10-07 15:37 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/notice/domain/AllowedImageExtension.java
> +}
이친구는 파일시스템상 허용할 이미지 확장자 형식을 의미하기 때문에, 피드스레드와 공통으로 생각해서 FileSystem에 만드는건 어떤가 하는 생각입니다.

2023-10-08 03:30 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
> +        }
오!! 맞네요!!
이 부분은 유틸로 빼서 공통으로 처리할 수 있을 것 같아요! 반영하겠습니다!!

2023-10-08 03:37 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/notice/domain/AllowedImageExtension.java
> +}
이 부분도 공통되었지만 분리한 이유가
정책이 달라지면 둘이 달라질 수도 있을 것 같아서였어요!

예를 들어서 공지에는 사진만 올라갈 수 있도록 하면 사진 확장자만 ENUM에 필드로 존재할 것이고,
나머지 스레드에 영상까지 올릴 수 있다고 하면 영상 확장자도 추가될 것이기 때문에 다르게 분리해야 한다고 생각했었습니다!

그러나 현재 상황에서 피드 등록 UI가 공지 & 스레드 둘 다 같은 UI에서 파일을 등록하기 때문에
공통으로 묶어도 괜찮을 것 같아요! 그래서 FileSystem에 리팩토링 하도록 하겠습니다! 👍🏻👍🏻👍🏻

2023-10-08 04:36 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/notice/domain/AllowedImageExtension.java
> +}
제가 해당 부분이 공통이라고 생각한 이유는 클래스명이 `AllowedNoticeFileExtension`이 아닌 `AllowedImageExtension`이였기 때문입니다.

성하가 말한것처럼 공지와 피드의 허용 파일 정책이 변경된다면 (하나는 이미지만, 하나는 이미지 + 영상 또는 파일) `AllowedVideoExtension`과 같이 허용되는 형식별 확장자가 공통으로 추가되고, 각각의 기능 서비스에서 허용할 형식들을 이용해서 검증하는 것을 생각했습니다.

2023-10-08 04:37 UTC, pilyang approved these changes
확인했습니다!!
파일 확장자 관련 코멘트는 제가 생각했던 내용이 다 안들어가있었던것 같아서 추가 내용 남겼습니다!!!

2023-10-08 04:38 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/notice/domain/AllowedImageExtension.java
> +}
만약에 이름이 `AllowedNoticeFileExtension` 과 같았으면 그대로 놔두는걸 선호했을지도..?

2023-10-09 01:58 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/notice/domain/AllowedImageExtension.java
> +}
아하 추가 코멘트 감사합니다 ㅎㅎㅎㅎ
클래스명을 좀 더 고민해서 짓긴 했어야 할 것 같네요 ㅎㅎㅎ,, 🤣
일단 지금은 리팩토링한 상태로 FileSystem에서 관리하게 하면 될 것 같아요!

2023-10-09 13:25 UTC, SproutMJ requested changes
구현하느라 고생하셨습니다......

2023-10-09 13:25 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/filesystem/util/FileUtil.java
> +    public static String getFileExtension(MultipartFile file) {
final 부탁합니다!

2023-10-09 13:25 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/filesystem/util/FileUtil.java
> +        if (originalFilename != null) {
Objects.isNull()은 어떠신가요?

2023-10-09 13:25 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeRegisterRequest.java
> +        return images;
return 위에 한줄 들어가나요?

2023-10-09 13:25 UTC, SproutMJ commented on backend/src/test/java/team/teamby/teambyteam/common/fixtures/FileFIxtures.java
> +
한줄 발견

2023-10-10 00:13 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/filesystem/util/FileUtil.java
> +        if (originalFilename != null) {
`Objects.nonNull()`로 변경했습니다!

2023-10-10 00:30 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeRegisterRequest.java
> +        return images;
return 전 개행 추가했습니다!

2023-10-10 01:06 UTC, SproutMJ approved these changes
g.o.o.d

2023-10-10 01:10 UTC, the9kim approved these changes
성하 엔델 환상의 페어 고생많으셨습니다!

2023-10-10 01:26 UTC, merged