[FE] 고객 문의 모달 구현
woowacourse-teams/2023-team-by-team pull request #755
Opened 2023-10-13 10:22 UTC by hafnium1923

## 이슈번호
> clsoe #748 

## PR 내용
언젠가 쓰일 것을 기대하며 공용 Accordion 컴포넌트 구현
자주하는 질문쪽에 회원탈퇴 숨겨둠

<img width="404" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/aca3d2e6-afbd-4acc-98a3-f15a61da75f7">

2023-10-14 13:59 UTC, hafnium1923 commented
요토가 제안해준 것 처럼 문의메일에 mailto넣었고 밑줄, 강조 했어.
하는김에 문의 메일 포맷도 만들었는데 이메일 누르면 아래 그림처럼 기본 작성돼!

<img width="397" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/7b038561-fd93-4cb4-afb0-86c81bdba843">

2023-10-16 04:47 UTC, suyoungj requested changes
👍

2023-10-16 04:47 UTC, suyoungj commented on frontend/src/components/common/Accordion/AccordionContext.tsx
> +  const [openedAccordion, setOpenAccordion] = useState<number>();
```tsx
const [..., setOpedAccordion]
> const [..., setOpenedAccordion]
```

2023-10-16 04:47 UTC, suyoungj commented on frontend/src/components/user/ServiceCenterModal/ServiceCenterModal.tsx
> +            원하시는 내용 없다면 아래 메일로 문의주세요
`원하시는 내용이 없다면 아래 메일로 문의주세요.`

가 나을듯?

2023-10-16 04:47 UTC, suyoungj commented on frontend/src/components/user/ServiceCenterModal/ServiceCenterModal.tsx
> +                <Text weight="semiBold">자주 묻는 질문</Text>
자주 묻는 질문들은 아닌거같아서 Q&A 정도로 충분할 거 같아

2023-10-16 04:47 UTC, suyoungj commented on frontend/src/components/user/ServiceCenterModal/ServiceCenterModal.tsx
> +                      Q. 외부 캘린더에서도 팀 일정을 보고 싶어요
`Q. 외부 캘린더에서도 팀 일정을 보고 싶어요`

`Q. 외부 캘린더(구글 캘린더, iOS 캘린더 앱)에서도 팀 일정을 보고 싶어요.`로 통일하는게 좋아보여

2023-10-16 04:47 UTC, suyoungj commented on frontend/src/components/common/Accordion/AccordionContext.tsx
> +  const handleOpenAccordionChange = (id: number) => {
얘도 `handleOpenedAccordionChange`가 좋아보여

2023-10-16 06:17 UTC, wzrabbit requested changes
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/257237fb-bf2c-43ef-b2c7-9c6f437af21b)


루루 문의 모달과 아코디언 만드느라 수고 많았어~
모달 크기가 작아서 어떻게 구현했을까 궁금했는데 모달이 부드럽게 늘어나네? 잘 만든 것 같아
코멘트 확인해줘!

2023-10-16 06:17 UTC, wzrabbit commented on frontend/src/components/common/Accordion/AccordionItem/AccordionItem.tsx
> +  return <S.Container>{children} </S.Container>;
여기도 마찬가지로 - 여기 있는 공백은 꼭 필요한 공백이야? 공백이 있어서 혹시나 해서 적어봤어

2023-10-16 06:17 UTC, wzrabbit commented on frontend/src/components/common/Header/Header.tsx
>  // import NotificationListModal from '~/components/feed/NotificationListModal/NotificationListModal';
나중에 사용할 일이 있어서 주석으로 남겨둔걸까? 아니라면 지우면 좋을 것 같아!

2023-10-16 06:17 UTC, wzrabbit commented on frontend/src/components/user/ServiceCenterModal/ServiceCenterModal.tsx
> +              <Accordion.Item></Accordion.Item>
이 아코디언 아이템 컴포넌트는 아무 내용을 담고 있지 않은데, 이 컴포넌트가 하는 역할을 혹시 설명해 줄 수 있을까?

2023-10-16 06:17 UTC, wzrabbit commented on frontend/src/components/user/ServiceCenterModal/ServiceCenterModal.tsx
> +            <a href="mailto:teambyteam.official@gmail.com?subject=팀바팀 문의합니다.&body=이메일(팀바팀 계정):%0D%0A문의분류(계정, 서비스, 버그, 기능추가, 기타):%0D%0A문의내용:%0D%0A">
아주 멋집니다
이런 식으로 하면 사용자가 메일 문의할 때 조금이나마 더 편하게 문의할 수 있을 것 같아
문의율도 당연히 높아질테고

2023-10-16 06:17 UTC, wzrabbit commented on frontend/src/components/common/Accordion/AccordionHeader/AccordionHeader.styled.tsx
> +  overflow-anchor: none;
오 `overflow-anchor: none` 은 처음 보는 속성이네
그래서 검색해 봤어, 스크롤이 있는 내용에서 중도에 컨텐츠가 더 많아지더라도 본래의 스크롤 위치를 유지하는 속성이구나

그런데, 루루가 구현한 모달 및 아코디언은 내용이 넘칠 경우 아코디언/모달 크기 자체가 늘어나면서 대응하는 방식인 것 같아서, 이 속성이 필요한지가 느껴지지 않았는데, 이 속성이 루루의 컴포넌트에서 사용되는 케이스를 혹시 설명해 줄 수 있을까? 내가 뭔가 놓친 것 같아서

2023-10-16 07:25 UTC, hafnium1923 commented on frontend/src/components/user/ServiceCenterModal/ServiceCenterModal.tsx
> +            원하시는 내용 없다면 아래 메일로 문의주세요
너무 극극 공손인데? `~부탁합니다` 는 서비스가 사용자한테 할 만한 말은 아닌 것 같아. 왜냐면 우리는 을이 아니잖아. 서비스를 제공하고 서비스를 사용하는 동등한 관계라고 생각해. 또한 내가 해당 문구를 작성할 때 여러 서비스의 고객문의 페이지를 참고했는데 보통 '~요' 로 끝나더라구!

2023-10-16 07:26 UTC, hafnium1923 commented on frontend/src/components/common/Accordion/AccordionHeader/AccordionHeader.styled.tsx
> +        outline: 3px ridge rgba(0, 46, 210, 0.381);
왜 투명도를 낮추면 보라색에 가까워 지는건지..🤪

2023-10-16 07:27 UTC, hafnium1923 commented on frontend/src/components/common/Accordion/Accordion.tsx
> +Accordion.Body = AccordionBody;
우리가 기존에 가지고있던 Menu컴포넌트와 구성이 동일해! 이렇게 한다면 사용처에서 import할 때 총 4개의 컴포넌트를 각각 import할 필요 없이 아코디언 컴포넌트 단 하나만을 불러와서 나머지 컴포넌트를 사용할 수 있어.

2023-10-16 07:28 UTC, hafnium1923 commented on frontend/src/components/common/Accordion/AccordionHeader/AccordionHeader.tsx
> +          {children} <ArrowExpandMoreIcon />
오 예리한데?! 수정할게!!

2023-10-16 07:31 UTC, hafnium1923 commented on frontend/src/components/user/ServiceCenterModal/ServiceCenterModal.tsx
> +              <Accordion.Item></Accordion.Item>
이건 뭐야 처음봤어 ㅋㅋㅋ 하다가 실수한 것 같네! 지우도록할게

2023-10-16 07:33 UTC, hafnium1923 commented on frontend/src/components/common/Accordion/AccordionHeader/AccordionHeader.styled.tsx
> +  overflow-anchor: none;
요토가 이해한대로 현재는 있으나 마나한 속성이 맞아. 하지만 만약 나중에 요구사항이 변경되어서 모달의 크기가 한정적이게 되거나, Q&A가 길어져서 스크롤이 생기게 될 경우도 추가적인 설정 없이 대응 할 수 있도록 하기위해서 추가해두었어. 아코디언은 재사용할 생각을 염두해두고 만든 컴포넌트니 최대한 다양한 상황에서 수정없이 사용되면 좋겠다는 생각이었거든

2023-10-16 07:33 UTC, hafnium1923 commented on frontend/src/components/common/Header/Header.tsx
>  // import NotificationListModal from '~/components/feed/NotificationListModal/NotificationListModal';
저건 그 알림컴포넌트 주석처리한 PR에서 있던 수정사항인데 아직 알림에 대해 정확하게 정한 것이 없어서 일단 주석했던 것으로 기억해! 근데 여전히 알림에 대해서 정해진 것이 없는데 지워도 될까? 잘 모르겠어

2023-10-17 09:20 UTC, suyoungj approved these changes

2023-10-17 09:28 UTC, wzrabbit commented on frontend/src/components/common/Header/Header.tsx
>  // import NotificationListModal from '~/components/feed/NotificationListModal/NotificationListModal';
오 그러면 일단은 냅두자
이해했어

2023-10-17 09:43 UTC, wzrabbit commented on frontend/src/components/common/Accordion/AccordionHeader/AccordionHeader.styled.tsx
> +  overflow-anchor: none;
그래, 공용 컴포넌트인 걸 생각하면 여기서는 안 쓰인다고 해도 다른 곳에서 사용할 때 해당 속성이 영향을 줄 수 있겠네
이해했어!

2023-10-17 09:44 UTC, merged