[BE] feat: 멤버 인증 인터셉터 구현
woowacourse-teams/2023-team-by-team pull request #78
Opened 2023-07-16 08:14 UTC by SproutMJ

## 이슈번호
#29 

## PR 내용
인터셉터 사용 경로: 모든 경로
보통 TokenProvider를 빈으로 만들어 토큰 생성(여기서는 상관 없음), 토큰 검증(이때 임의의 키가 들어감), PayLoad에서 필요한 부분 추출(이때도 임의의 키를 이용해 검증을 넣을 수 있음)을 담당하게 하는 것으로 보인다.
하지만 유효성 검증을 하지 않고 인터셉터를 구현하는 것을 목적으로 했기 때문에 내부 private 메서드로 필요 기능을 구현하였다.
1. 헤더에서 “Bearer “ 문자열 제거
2. 1에서 추출된 토큰에서 PayLoad를 분리하고 거기서 email 추출
3. email을 통해 Member를 조회하고 성공하면 정상, 실패하면 예외를 던지도록 구현

## 참고자료

## 의논할 거리
1. 요청할 때마다 MemberRepository를 조회하는 점
2. 커스텀 예외(현재 NotFoundException, IllegalTokenException을 만들어 적당한 때에 throw 중)

2023-07-16 10:59 UTC, sh111-coder requested changes
작업 수고하셨슴다 엔델!! 코드 리뷰 몇 부분 남겼슴다

2023-07-16 10:59 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +@Component
`MemberInteceptor`를 @Component로 빈으로 등록한 이유가 있을까요??

2023-07-16 10:59 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +    private static final String EMAIL_KEY = "email";
상수와 인스턴스 변수 사이에 개행하는 게 좋을 것 같슴다~!

2023-07-16 10:59 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +package team.teamby.teambyteam.member.configuration;
`MemberInterceptor` 패키지를
global.configuration에 둬야할지, 이대로 둬야할지 조금 고민이 드네요,,

이런 패키지적인 부분은 도메인이 아니면 크리티컬한 문제는 아니라고 생각하는데요!
개발자들 간에 직관? 어디가 자연스러울지 팀 내에서 정하면 될 것 같습니다!!

저는 MemberArgumentResolver랑 MemberInterceptor가 같이 있으면 좋을 것 같아서 지금 패키지 구조도
괜찮다고 생각하는데
다른 분들은 어떤지 궁금하네유

2023-07-16 10:59 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
인증 Prefix가 Bearer가 아닌 경우는 따로 예외 처리를 해주는 게 좋을 것 같아요!
'인증 Prefix 형식이 다릅니다.' 이런 식으로?

인증 Prefix가 없는 건 잘못된 토큰은 아니라서 다른 예외라고 생각합니다!

2023-07-16 10:59 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +        }
이 부분은 Optional의 `orElseThrow`를 사용하면 더 깔끔하게 처리될 것 같긴 한데

단순히 멤버가 존재하는지 확인하는 거면 select 쿼리가 아닌 count 쿼리로
JPA exist 메소드를 사용하는 게 좋을 것 같습니다!

2023-07-16 10:59 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/domain/MemberRepository.java
> +    Optional<Member> findByEmail(@Param("email")Email email);
이 부분 보니까 생각났는데 우리 VO에 Equals & HashCode도 재정의 해줘야 할 것 같습니다..?

2023-07-16 11:04 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +    private final MemberRepository memberRepository;
> 의논할 거리
* 요청할 때마다 MemberRepository를 조회하는 점'

이 부분은 난 Inteceptor는 Presentation 레이어라고 생각해서 Repository가 아닌 Service를 참조해야 한다고 생각함

2023-07-16 11:32 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +@Component
안그래도 그점이 있었는데 WebMvcConfiguration에서 MemberInterceptor추가할 때 MemberRepository 넣어야되는데 이방법이 최선인거같아서요

2023-07-16 11:55 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +@Component
아하!!! 제가 놓쳤네요!
이해됐습니다!

2023-07-16 12:38 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +@Component
아 이거 방법이 아예없나요? 내일 일단 한번더 여쭈어보겠습니다.

2023-07-16 12:54 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +            return bearerToken.substring(7);
이 부분 매직 넘버인 것 같습니다!

2023-07-17 03:33 UTC, pilyang requested changes
리뷰 남겼어요 ^^

2023-07-17 03:33 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +package team.teamby.teambyteam.member.configuration;
저도 `ArgumentResolver`와 같은 위치에 있는게 좋다고 생각합니다.

글로벌로 이동을 하려면 마땅한 이유가 있거나 알규먼트 리졸버와 같이 움직여야 할 것 같습니다.

추가적인 이유로는 회원도메인으로 등록된 회원인지를 인증하는것(이러한 표현이 맞나는 모르겠지만)이기 때문에 해당 도메인 내부에  있는거가 좋다고 생각합니다.
그래야 멤버도메인에 변동이 생기거나 했을때 해당 패키지 내에 있는 인터셉터만 수정할 수 있도록요

2023-07-17 03:33 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
> +    }
전체에 모두 걸어주셨는데, 일단은 공통부분은 `/api`하위로 오는 것들에 대해서 검증을 하는게 어떨까 합니다.

너무 루트부터 하면 후에 어떤 url이 생길 지 몰라서.. 일단 공통으로 들어가는 `/api`부분부터로 잡는게 좋다고 생각하는데, (호오옥시 나중에 admin같은게 추가되면 그때가서 해당 부분도 같은 인터셉터를 사용할지 아님 관리자를 위한 추가적인 게 필요할지 등 상의할 게 있을 것 같네요)

다른분들의 생각은 어떠신가요???

2023-07-17 03:33 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +        }
저도 성하 의견에 동의합니다!!

findByEmail(~~~)
.orElseThrow()

또는 exist

2023-07-17 03:33 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
저는 해당부분에 대한 예외처리에 대해서는 다시 같이 이야기해보아도 좋을 것 같아요.

물론 이게 크리티컬한 경우는 아니지만 인증관련 예외나 그 종류나 내용에 대해서는 최대한 메시지등은 숨기는게 좋다고 생각합니다.

만약 로깅을 해서 저희가 확인하는 용도면 괜찮다고 생각합니다.

지금 예외로 던져주는 "잘못된 토큰"이라는 메시지도 충분하다고 생각이 들기는 합니다.(사용자들한테 가기에는 - 로깅용이 아닌)

2023-07-17 03:33 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +            return bearerToken.substring(7);
이부분은 `Bearer `를 스트링으로 축출하고
7 대신에 해당 string.lenght()를 이용해도 좋을 것 같네요..!!

```java
private final String BEARER_PREFIX = "Bearer ";

...

BEARER_PREFIX.length();        // 요런 느낌쓰..?
```

2023-07-17 03:33 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +        }
`extractToken`에서 null을 반환하는것보다 Optional을 반환하도록 해서 orElstThrow같은걸 처리하거나,

String으로 반환한다면 extractToken에서 validation까지 하여 throw를 하고 무조건 null이 아닌 스트링을 반환하도록 하는건 어떠신가요?

2023-07-17 06:05 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Bearer 토큰이 아닌 경우 UnSupportAuthenticationException를 던지도록 변경했습니다.

2023-07-17 06:14 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +        }
exsist 사용하도록 변경했습니다.

2023-07-17 06:17 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +            return bearerToken.substring(7);
필립의견처럼 했습니다.

2023-07-17 06:18 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
> +    }
일단은 보안을 전체 다 걸고 필요한 부분에 해제하는 식으로 가져가려고 일단 다 걸었습니다. 당연히 랜딩페이지나 로그인페이지에 걸면 안될 것입니다.

2023-07-17 06:19 UTC, SproutMJ commented on backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
> +        }
extractToken 함수에서 Bearer 토큰이 아닌 것을 감지하면 throw하도록 변경했습니다.

2023-07-17 07:31 UTC, pilyang requested changes
`final` 놓친부분만 잡아주면 될 것 같습니다!!

2023-07-17 07:33 UTC, sh111-coder approved these changes
good!

2023-07-17 07:35 UTC, pilyang approved these changes
good

2023-07-17 07:36 UTC, merged