[FE] 검색 결과에 대한 정보 제공을 위한 meta tag 추가
woowacourse-teams/2023-team-by-team pull request #828
Opened 2023-10-24 08:10 UTC by suyoungj

# [FE] 검색 결과에 대한 정보 제공을 위한 meta tag 추가
## 이슈번호
> close #827 

## PR 내용
- 검색 결과에 대한 정보 제공을 위한 meta tag 추가

2023-10-24 08:54 UTC, hafnium1923 requested changes

2023-10-24 08:54 UTC, hafnium1923 commented on frontend/public/index.html
> +    <meta name="og:description" content="쉽고 간단한 팀플 플랫폼, 팀바팀" />
og:image도 설정하는게 좋지 않을까?

2023-10-25 02:42 UTC, wzrabbit approved these changes
👍🏻

2023-10-25 02:45 UTC, wzrabbit commented on frontend/public/index.html
> +    <meta name="og:description" content="쉽고 간단한 팀플 플랫폼, 팀바팀" />
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/6cc6c90c-a000-4cc1-a71c-8e4d80ff7578)

뭐 이런 이미지라도 쓰쉴?

2023-10-25 02:46 UTC, hafnium1923 commented on frontend/public/index.html
> +    <meta name="og:description" content="쉽고 간단한 팀플 플랫폼, 팀바팀" />
좋은데요?

2023-10-25 05:49 UTC, hafnium1923 commented
근데 이미지 업로드 안했는데  적용되는거야?

2023-10-25 05:52 UTC, suyoungj commented
s3에 올려놨는데 html이 아직 안바껴서 프로덕션 배포해봐야 알듯?

2023-10-25 05:53 UTC, hafnium1923 commented
ㅇㅎ 거기에 올라간거구만 좋아요

2023-10-25 05:53 UTC, hafnium1923 requested changes
열일하시는군뇨
수고하셨슴다

2023-10-26 05:01 UTC, hafnium1923 approved these changes

2023-10-26 05:01 UTC, merged