[FE] 테스트, 빌드 속도 개선
woowacourse-teams/2023-team-by-team pull request #830
Opened 2023-10-26 04:53 UTC by suyoungj

# [FE] 테스트, 빌드 속도 개선
## 이슈번호
> close #829 

## PR 내용
- 테스트, 빌드 속도 개선
- 차이가 좀 나는군요

## 참고자료
### 테스트
Before
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/535fdf2b-baa2-4d44-8284-6ff9050e4c04)

After
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/1a4c9923-4d0b-4df5-a5d0-ab424b56c4c5)

### 빌드
Before
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/3f602937-1736-4829-91f1-9a11e6624133)

After
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/d9f506d3-109a-4aa8-82a7-fdafea54b778)

2023-10-26 04:54 UTC, hafnium1923 commented
혹시 빌드도구를 바꾸게 된 계기가 있다면 관련 자료도 같이 올려줄 수 있나요?

2023-10-26 04:59 UTC, suyoungj commented
## 참고자료
https://fe-developers.kakaoent.com/2022/220707-webpack-esbuild-loader/

2023-10-26 05:02 UTC, hafnium1923 commented
아 테스트꺼도..🫠👍

2023-10-26 05:03 UTC, suyoungj commented
테스트는 기억 속 어딘가에서 끄집어와서 공식문서와 swc 동작방식을 참고하는게 좋을 듯 합니다

https://swc.rs/docs/usage/jest

2023-10-26 08:52 UTC, hafnium1923 requested changes
jest의 빌드 도구를 변경한건 이해가 되는데
ts-loader을 esbuild-loader으로 마이그레이션 하는 이유는 속도 차이 때문에 그런가?
찾아보니까 ts-loader은 컴파일 과정에서 타입체크를 진행하는데 esbuild loader는 타입체크를 하지 않는다 하더라고! 지금 속도도 나는 사실 그렇게 느리다고 생각되진 않아서 꼭 바꿔야하나 싶긴해

2023-10-26 08:52 UTC, hafnium1923 commented on frontend/webpack.config.js
> +          target: 'es2015',
esnext로 하면 안되나?

2023-10-26 10:29 UTC, suyoungj commented
앞으로도 계속 빌드 + 배포할거니까 타입 체크보다 빌드 시간을 50% 절약하는게 더 이득이라고 생각했어!
개별적으로는 체감이 크지 않지만 쌓이면 쌓일수록 절약 효과가 크니까 안 쓸 이유는 없다는 느낌?

2023-10-27 02:42 UTC, hafnium1923 commented
그치만 나는 타입스크립트를 사용하는 건 더 안전한 개발환경을 구축하기 위해서라고 생각하는데 컴파일 시점에 타입체크가 되지 않는다면 허점이 생길 수 있는거 아닐까 생각해.
우리 처음 목표도 타스를 최대한 다 쓰면서 구현하자! 였으니까..

2023-10-27 05:13 UTC, suyoungj commented
1) vscode에서 충분히 타입체크를 꼼꼼히 해준다고 생각해서, 컴파일 시점 타입체크는 굳이 중요하지 않다고 생각했어.
2) esbuild-loader는 esnext로 빌드하는게 기본값이라 options를 제거했어.

2023-10-27 05:17 UTC, hafnium1923 approved these changes
충분한 설명 감사합니다

2023-10-27 05:48 UTC, merged