[FE] React Query staleTime을 적용하여 네트워크 요청 횟수를 줄인다.
woowacourse-teams/2023-team-by-team pull request #832
Opened 2023-10-26 08:23 UTC by suyoungj

# [FE] React Query staleTime을 적용하여 네트워크 요청 횟수를 줄인다.
## 이슈번호
> close #831 

## PR 내용
- staleTime을 적용하여 네트워크 요청 횟수 최적화
- 팀 캘린더의 경우 30초마다 동기화하도록 설정
- 팀 링크, 멤버 목록의 경우 1분마다 동기화하도록 설정
- 팀 초대 코드의 경우는 변하는 경우가 없으므로 Infinity를 줬습니다.

## 참고자료
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/735b9f7c-2a86-44d7-9c8b-9cb6dd0d4ca0)

2023-10-26 08:57 UTC, hafnium1923 requested changes

2023-10-26 08:57 UTC, hafnium1923 commented on frontend/package.json
> +    "@tanstack/react-query-devtools": "^4.36.1",
얜 먼가여

2023-10-26 08:57 UTC, hafnium1923 commented on frontend/src/constants/query.ts
> +  TEAM_PLACE_INVITE_CODE: Infinity,
이왕이면 ics도 무한이면 좋을 것 같으데

2023-10-26 08:57 UTC, hafnium1923 commented on frontend/src/constants/query.ts
> +  SCHEDULES: 1000 * 30,
통합캘린더와 통합 하루 일정도 동일한 시간 걸어두자

2023-10-26 08:57 UTC, hafnium1923 commented on frontend/src/constants/query.ts
> +  TEAM_PLACE_MEMBERS: 1000 * 60,
그 갑자기 생각난건데 나의 정보도 캐시타임 주면 좋지 않나

2023-10-27 05:14 UTC, suyoungj commented on frontend/package.json
> +    "@tanstack/react-query-devtools": "^4.36.1",
리액트 쿼리 개발자 도구입니다 너무 늦게 깔았네요..

2023-10-27 05:15 UTC, suyoungj commented on frontend/src/constants/query.ts
> +  TEAM_PLACE_MEMBERS: 1000 * 60,
접속하자마자 Header 렌더링할 때 불러오는 데이터라 굳이 안줘도 될 것 같다고 생각했어!

2023-10-27 05:17 UTC, hafnium1923 commented on frontend/src/constants/query.ts
> +  TEAM_PLACE_MEMBERS: 1000 * 60,
근데 방금 확인해보니까 탭 전환할때 계속 me도 불러오고 있어서 여기도 타임 주는게 좋을듯! 더군다나 이친구는 이름 수정해서 변경 일어나는거 아니면 계속 동일하니까

2023-10-27 05:25 UTC, suyoungj commented on frontend/src/constants/query.ts
> +  TEAM_PLACE_MEMBERS: 1000 * 60,
일단 5분 줘봤읍니다

2023-10-27 05:29 UTC, hafnium1923 approved these changes
굿입니다요

2023-10-27 05:51 UTC, merged