[FE] 팀 정보 아이콘 접근 시 prefetching 적용
woowacourse-teams/2023-team-by-team pull request #833
Opened 2023-10-27 06:04 UTC by suyoungj

# [FE] 팀 정보 아이콘 접근 시 prefetching 적용
## 이슈번호
> close #826 

## PR 내용
- 팀 정보 아이콘 onFocus, onMouseEnter시 prefetching 적용
- onFocus / onMouseEnter가 일어나면 사용자가 클릭할 것이라 가정하고 데이터를 미리 불러와서 로딩 상태를 보지 않도록 구현했습니다
- 아이디어는 저번에 요토랑 잡담하다 갑자기 생각났습니다

2023-10-27 06:36 UTC, hafnium1923 requested changes
좋은 아이디어인데 사실 필요할까 싶긴합니다! 팀 아이콘이 내 정보 옆에 있으니까 약간 의도하지 않은 이벤트가  자주 일어날 것 같아서.

2023-10-27 06:36 UTC, hafnium1923 commented on frontend/src/components/common/Header/Header.tsx
> +  const queryClient = useQueryClient();
헤더에 queryClient가 있는게 어색해보여. 저번 캘린더 프리패치처럼 훅을 분리하는건 어때?

2023-11-01 04:53 UTC, suyoungj commented on frontend/src/components/common/Header/Header.tsx
> +  const queryClient = useQueryClient();
여기서 prefetch는 조건부(이벤트 발생 시)로 호출돼서, 훅으로 분리해서 쓰지는 못해
`const navigate = useNavigate();`
랑 비슷해서, 나는 딱히 어색하게는 안 느껴지는거 같아

2023-11-01 04:53 UTC, suyoungj commented on frontend/src/components/common/Header/Header.tsx
> +  const queryClient = useQueryClient();
의도하지 않은 이벤트가 발생할 수 있긴 한데, 스크롤에 비하면 빈도가 훨씬 적고 fetch 요청도 잦지 않아서 괜찮다고 생각했어!

2023-11-01 04:54 UTC, hafnium1923 approved these changes
좋아요 캘린더도 호버이벤트로 프리패치 달까

2023-11-01 04:59 UTC, suyoungj commented
일정은 들어오자마자 보여야 하니깐 캘린더는 지금 방식대로 프리페치하는게 좋아보여
만약 추가한다면 내 일정(MySchedule)도 메인 캘린더랑 동일하게 이전 달 + 저번 달 불러오게 하면 좋을듯?

2023-11-02 07:45 UTC, merged