[FE] 이미지 모달의 이미지 전환을 키보드 조작으로 할 수 있도록 개선
woowacourse-teams/2023-team-by-team pull request #835
Opened 2023-10-27 14:32 UTC by wzrabbit

# [FE] 이미지 모달의 이미지 전환을 키보드 조작으로 할 수 있도록 개선
## 이슈번호
> close #834 

## PR 내용
본 PR에서는 팀 채팅 메뉴에서 쓰이는 이미지 모달의 이미지를 키보드 조작으로도 가능하게 만들어 사용자가 보다 편리하게 기능을 사용할 수 있도록 개선하였다.

### 주요 기능
- `←`, `→` 키를 누르면 이미지를 양옆으로 전환할 수 있다.
- `1` ~ `9` 키를 누르면 누른 숫자 키에 해당하는 번호의 이미지를 보여 준다. 단, 전체 이미지 개수보다 누른 키의 번호가 클 경우에는 아무 일도 일어나지 않는다.

### 보조 기능
- 모달의 이미지가 하나뿐인 경우, 양옆의 이미지 전환 버튼을 비활성화시키고 시각적으로도 전환이 불가능함을 표현하였다.

## 참고자료
- 이미지가 하나뿐이었을 때 버튼이 비활성화되어 시각적으로도 흐리게 표시되며, 마우스 포인터도 `not-allowed` 로 표시된다.

![캡처_2023_10_27_22_50_57_869](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/517b3426-8a30-43d8-a310-875e0424a7a2)

## 의논할 거리
구현 중 `keyDown` 이벤트의 `keyCode` 를 사용했는데, 이 프로퍼티는 사실 deprecated된 프로퍼티로, 사용이 권장되지 않는 상태야. 그럼에도 사용했는데, 이유는 [이 이슈](https://github.com/wzrabbit/boj-totamjung/issues/11)에서 트러블슈팅을 했을 때, 일부 Mac OS 유저에 한해, `key` 프로퍼티에 찍히는 값이 이상한 경우가 간혹 있었더라고.

그래서, 기본적으로 사용이 권장되는 `key` 프로퍼티를 통해 눌린 키가 방향키/숫자키인지 검사하되, 아닐 경우에 `keyCode` 를 사용하여 보조적으로 추가 검증을 하는 방향으로 구현해 보았어.

내가 명확하게 권장되지 않는 걸 쓴 것은 맞으니, 이에 대해서 의논해 보면 좋을 것 같아!

2023-10-31 06:10 UTC, hafnium1923 requested changes

2023-10-31 06:10 UTC, hafnium1923 commented on frontend/src/hooks/thread/useCarouselPageNo.ts
> +      console.log('key press', key);
콘솔 삭제 plz

2023-10-31 06:10 UTC, hafnium1923 commented on frontend/src/constants/feed.ts
> +export const KEY_CODE = {
얜 머야

2023-10-31 06:10 UTC, hafnium1923 commented on frontend/src/hooks/thread/useCarouselPageNo.ts
> +        keyCode >= KEY_CODE.DIGIT1 &&
위에 key값 로직이랑 이거랑 똑같은거 아니야..?

+ keycode말고 그냥 key값으로는 못하나??

2023-10-31 06:42 UTC, wzrabbit commented on frontend/src/hooks/thread/useCarouselPageNo.ts
> +      console.log('key press', key);
오, 깜박하고 지우지 않았네. 삭제할게!

2023-10-31 06:42 UTC, wzrabbit commented on frontend/src/constants/feed.ts
> +export const KEY_CODE = {
`keyCode` property를 사용하게 되면 키 입력이 일어났을 때 고유의 코드 값을 부여받게 돼, 아래는 몇 가지 예시야.
- `Enter` key: 13
- `1` key: 49
- `9` key: 57

이 코드 값을 이용해 어떤 키가 눌렸는지를 검사하는 로직이 이번 PR에서 구현된 건데, `13`, `49`, `57` 과 같은 `keyCode` 값은 매직넘버에 해당되어 알아보기 힘들 수 있으므로 별도로 `KEY_CODE` 라는 변수를 선언하고 그 내부에 값들을 저장해 상수화시킨거야!

2023-10-31 06:42 UTC, wzrabbit commented on frontend/src/hooks/thread/useCarouselPageNo.ts
> +        keyCode >= KEY_CODE.DIGIT1 &&
루루가 말한대로 거의 동일한 것은 맞아.
"의논할 거리" 에 관련 사항을 적어둔 적이 있으니 확인해 줘, 확인 이후 다시 코멘트 주면 좋겠어!

2023-10-31 06:46 UTC, hafnium1923 commented on frontend/src/hooks/thread/useCarouselPageNo.ts
> +        keyCode >= KEY_CODE.DIGIT1 &&
저런.. 리뷰만 하고 읽는걸 깜빡해버렸네 쏘리
방금 해당 로직 지우고 실행해봤는데 나한테는 문제가 없는 것 같아! 일단 없애도 될듯??

2023-11-01 04:02 UTC, hafnium1923 approved these changes
댓글 단거만 확인해줘 수고했슴!

2023-11-01 04:51 UTC, suyoungj reviewed
👍

2023-11-01 04:51 UTC, suyoungj commented on frontend/src/components/feed/Carousel/Carousel.tsx
> +          css={S.arrowButton(images.length === 1)}
`images.length === 1`이 반복되니까 따로 변수로 빼면 어떨까??

2023-11-01 04:51 UTC, suyoungj commented on frontend/src/hooks/thread/useCarouselPageNo.ts
> +        keyCode >= KEY_CODE.DIGIT1 &&
내 생각에도 key로 충분할거 같아!
로컬에서 돌려봤는데 문제되는 점은 없어보여

2023-11-06 06:22 UTC, wzrabbit commented on frontend/src/hooks/thread/useCarouselPageNo.ts
> +        keyCode >= KEY_CODE.DIGIT1 &&
Mac OS도 브라우저, 운영체제 등에 따라 작동 방식이 다른 것 같아 - 그래서 몇몇 기기에서는 이와 관련된 문제가 생기는 것 같아 보여

하지만 다시 생각해 보니까 내가 제시한 케이스는 `Command` 키를 같이 눌렀을 때의 케이스고, 인터넷에 검색했을 때도 뚜렷하게 이 버전에서는 이러한 문제가 생길 수 있다는 자료도 없는지라 내 주장도 그닥 신빙성이 없어보이네

`keyCode` 를 사용하는 로직은 본래도 추천되지 않았고 나도 가능한 한 넣고 싶지 않았으니까 요녀석은 다시 지우고 `key`만으로 검증하도록 바꿔놓을게, 문제가 생기는 케이스가 있다면 그 때 다시 커버해보는 걸로!

2023-11-06 07:09 UTC, wzrabbit commented on frontend/src/components/feed/Carousel/Carousel.tsx
> +          css={S.arrowButton(images.length === 1)}
굿 아이디어~ `hasSingleImage` 는 어때?

2023-11-06 07:18 UTC, wzrabbit commented
모든 코멘트 반영 완료!

2023-11-06 07:19 UTC, wzrabbit commented on frontend/src/constants/feed.ts
> +export const KEY_CODE = {
`keyCode` 를 제거하기로 결정함에 따라, 이 객체는 다시 지웠어

2023-11-14 04:47 UTC, merged