[FE] 팀바팀 모바일 버전 구현
woowacourse-teams/2023-team-by-team pull request #845
Opened 2023-10-31 15:33 UTC by hafnium1923

# [FE] 팀바팀 모바일 버전 구현
## 이슈번호
> close #842 

## PR 내용
- 모바일에서 모아보기페이지 접근금지 처리
- 모바일 pageTemplete 구현
- 모바일 환경에서 짤리는 디자인 수정

## 의논할 거리
- 최대한 만든거 활용하려고 노력함
- 디자인 개구린거 아는데 일단 모바일에서 사용가능하게 만들어두고 고도화 하는 방향으로 수정하는건 어떻게 생각함
- 모달도 다 수정해야하는데 한번에 하면 충돌나거나 너무 시간 오래 걸릴 것 같아서  진짜 걍 사용만 가능하게 함

2023-11-02 01:39 UTC, suyoungj requested changes
UI 수정사항 제안해봅니다

<img width="394" alt="스크린샷 2023-11-02 오전 10 33 51" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/53bd4d47-21fc-4dcd-a0f5-7a1896c4d253">
- 모바일에서는 배경 이미지 없어도 될 것 같아

![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/048fda9c-30c4-4e66-a395-4da59644cc48)
- 팀 Select랑 캘린더 정중앙 배치 부탁드려요

![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/2063c161-cecc-40a7-9aa3-589f2c61ae95)
- 잘 보면 미세한 틈이 있네요

2023-11-02 01:39 UTC, suyoungj commented on frontend/src/hooks/useCheckMobileWeb.ts
> +export const useCheckMobileWeb = () => {
얘는 다른 훅을 쓰지 않는 그냥 유틸 함수니까 이름이랑 위치 옮겨야 될 것 같아
`getIsMobile / getIsMobileWeb` 정도?

2023-11-02 01:41 UTC, hafnium1923 commented on frontend/src/hooks/useCheckMobileWeb.ts
> +export const useCheckMobileWeb = () => {
꺅

2023-11-02 01:41 UTC, suyoungj requested changes

2023-11-02 01:41 UTC, suyoungj commented on frontend/src/hooks/useCheckMobileWeb.ts
> +  return false;
공백 한 줄 추가 부탁드려요

2023-11-02 01:49 UTC, kpeel5839 commented
오 장난아닌데요

2023-11-02 01:50 UTC, kpeel5839 commented on frontend/src/hooks/useCheckMobileWeb.ts
> +  return false;
공백이 꼭 필요할 것 같긴하네요

2023-11-02 04:38 UTC, hafnium1923 commented
해결완료요

2023-11-02 07:36 UTC, suyoungj approved these changes
👍
아래 깨지는것만 수정해주세요
<img width="485" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/792bc329-2c45-4090-a8b7-bf3a135c815b">

2023-11-02 08:43 UTC, wzrabbit commented on frontend/src/styles/theme.ts
> +  WHITE_BLUR: 'rgba(255, 255, 255, 0.68)',
요거만 일관성에 맞게 HEX 값으로 바꿔주면 좋을듯!
```suggestion
  WHITE_BLUR: '#ffffffad',
```

2023-11-02 08:45 UTC, wzrabbit reviewed
이걸 어떻게 하루만에 구현한거임!???

2023-11-06 06:14 UTC, wzrabbit requested changes
되게 늦게 봐서 미안하긴 하지만...
리뷰 이후에 새로운 문제를 찾은 것 같아서, 이것만 확인해 줄 수 있을까?

PC 버전인 상태에서, **모아보기 페이지** 로 이동할 때, 또는 **캘린더 페이지** 로 이동할 때, UI가 위로 밀려 올라가는 문제가 있는 것 같아

이 두 문제는 해결이 필요해 보여
혹시 해결이 안 된다면 더 자세히 찾아볼게

https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/881c73f7-9c84-462c-b0fb-d311ee033de4




https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/add9babf-7010-4844-9a5f-b7363d7ead5e

2023-11-07 02:58 UTC, wzrabbit approved these changes
트러블슈팅 해 보니까 이 PR의 문제가 아니라 다른 곳에서의 원인인 것으로 보이네
슬랙에서 충분히 이야기한 것 같으니 이 PR은 Approve 할게!
당황했을 것 같기도 한데 열심히 트러블슈팅 해줘서 고마워

2023-11-07 03:05 UTC, merged