[FE] 프로필 닉네임 수정 낙관적 업데이트 적용
woowacourse-teams/2023-team-by-team pull request #849
Opened 2023-11-01 07:24 UTC by suyoungj

# [FE] 프로필 닉네임 수정 낙관적 업데이트 적용
## 이슈번호
> close #848 

## PR 내용
- 프로필 닉네임 수정 낙관적 업데이트 적용

## 참고자료
- MSW delay 1초 줘서 결과 비교

- 낙관적 업데이트 X
![화면 기록 2023-11-01 오후 4 18 33](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/ff6207f7-db0d-4b62-8378-0467f3949065)

- 낙관적 업데이트 O
![화면 기록 2023-11-01 오후 4 19 56](https://github.com/woowacourse-teams/2023-team-by-team/assets/19235163/9945e840-4dda-4f52-99d3-d2c8662074b9)

2023-11-02 07:29 UTC, hafnium1923 commented
슨생님 제가 낙관적 업데이트 공부를 하고 pr을 확인하고 싶어서 그런데 리뷰 좀 기다려주실수..?있을까요

2023-11-06 10:17 UTC, hafnium1923 requested changes
낙관적업데이트 순서가 query 보낼동안 onMutate가 실행되어 마치 바로 성공한 것 처럼 보여주고 제대로 통신이 되었는데 에러가 발생하지 않으면 onMutate로 설정한 값이 진짜 값이라 생각해서 그대로 두는거로 이해했는데 맞을까?!

2023-11-06 10:17 UTC, hafnium1923 commented on frontend/src/hooks/queries/useModifyUserInfo.ts
> +              return { ...old, ...body };
이전값을 왜 쪼개서 넣는지 이해를 못했어. 이부분이 낙관적업데이트를 하는 부분이라고 생각되는데 updater함수에서 반환하는 값이 낙관적 값이 되는거니 {..body} 로 충분한거 아니야?

2023-11-08 12:17 UTC, suyoungj commented on frontend/src/hooks/queries/useModifyUserInfo.ts
> +              return { ...old, ...body };
`UserInfo`를 업데이트해야 하고, body에는 바꿀 `name`만 들어가 있으니까 `{...old, ...body}`로 다른 필드는 그대로 유지하고 `name`만 바꾼 새로운 `UserInfo`를 반환한다고 이해하면 될 것 같아!

2023-11-10 10:49 UTC, hafnium1923 commented on frontend/src/hooks/queries/useModifyUserInfo.ts
> +              return { ...old, ...body };
와 저렇게 되도 새로운 값만 바뀌는거구나 댑ㄱ악

2023-11-10 10:49 UTC, hafnium1923 approved these changes
감사합니다!

2023-11-10 10:50 UTC, merged