[FE] useSSE를 ProtectRoute에서 호출하도록 수정
woowacourse-teams/2023-team-by-team pull request #853
Opened 2023-11-02 04:51 UTC by suyoungj

# [FE] useSSE를 ProtectRoute에서 호출하도록 수정
## 이슈번호
> close #852 

## PR 내용
- useSSE를 ProtectRoute에서 호출하도록 수정
- 개발 서버 배포 후 확인 필요

2023-11-02 05:01 UTC, hafnium1923 requested changes

2023-11-02 05:01 UTC, hafnium1923 commented on frontend/src/index.tsx
> +              <TeamPlaceProvider>
아 이럼 에러 생길텐디

2023-11-02 05:25 UTC, suyoungj commented on frontend/src/index.tsx
> +              <TeamPlaceProvider>
이유 설명좀 해줄래? 잘 모르겠어

2023-11-02 05:52 UTC, suyoungj commented on frontend/src/index.tsx
> +              <TeamPlaceProvider>
PageTemplate에서 호출하게 바꿔봤어

2023-11-02 07:23 UTC, hafnium1923 commented on frontend/src/index.tsx
> +              <TeamPlaceProvider>
내 기억상 provider하위에 있는 페이지에 접속하면 무조건 팀을 get하려 하는데
APP을 감싸면 모든 페이지에서 팀을 가져오려해서 에러 생겼던 걸로 기억!

2023-11-02 07:24 UTC, hafnium1923 commented on frontend/src/index.tsx
> +              <TeamPlaceProvider>
코드상에서 안바꼈는데 push안한듯?

2023-11-06 04:14 UTC, hafnium1923 approved these changes

2023-11-06 04:20 UTC, merged