[FE] 스케줄 바를 드래그하여 수정할 수 있는 기능 구현
woowacourse-teams/2023-team-by-team pull request #857
Opened 2023-11-13 07:11 UTC by wzrabbit

# [FE] 스케줄 바를 드래그하여 수정할 수 있는 기능 구현
## 이슈번호
> close #846

## PR 내용
현재 리팩토링 및 버그 체크 중. 아마 화요일에 Pull Request를 작성할 것으로 예상.

2023-11-30 07:17 UTC, hafnium1923 requested changes
오우 진짜 퀄리티 높은 코드네 보면서 감탄했어!
작성하느라 진짜진짜 고생 많았음!!! 리뷰 기다려줘서 고마워ㅎㅎ 아까 자세하게 설명해준게 도움이 컸어
리뷰는 간단한거 몇개만 작성했는데 한번 확인해주면 좋을 것 같아~!~!~ 
수고많았어 토끼야

2023-11-30 07:17 UTC, hafnium1923 commented on frontend/src/components/team_calendar/CalendarDragScreen/CalendarDragScreen.tsx
> +interface CalendarDragScreenProps {
...dragStaus로 보내고 있으면 dragStatus 객체로 받는게 더 깔끔하지 않나?

2023-12-07 18:03 UTC, wzrabbit reviewed
리뷰 고맙고~
엄청 길고 못생긴 코드라 대충 넘어갈 수도 있었는데 관심 가지고 이 코드가 어떻게 작동하는건지 궁금한 점을 여과없이 물어봐 줘서 좋았어~

여러 제안을 해 주었는데 대체로 좋은 제안이라 생각되서 대부분 수용했고, 단언에 대해서는 단언을 사용하는 대신 다른 해결 방법을 찾아보았어
`CalendarGrid` 이름은 좋은 이름 좀 추천해주라 나도 모르겠다...

그럼 코멘트 확인해 줘! 고마워~

2023-12-11 04:16 UTC, hafnium1923 commented on frontend/src/hooks/schedule/useScheduleBarDragStatus.ts
> +  const [dragStatus, setDragStatus] = useState<DragStatus>({
아주좋아

2023-12-11 04:18 UTC, hafnium1923 commented on frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.styled.ts
> +export const CalendarGrid = styled.div`
그러니까 말야 그냥 일단일케 둘까? 하도 캘린더가 구조가 복잡한데 단일형태라그런지 마땅하지 않네

2023-12-11 04:19 UTC, hafnium1923 approved these changes
길고도 커다란 업데이트가 드디어 적용되네 고생많았어 요토! 실제로 사용하는게 기대된다ㅎㅎ

2023-12-11 04:19 UTC, merged