[FE] 일정 등록 모달 UI 구현
woowacourse-teams/2023-team-by-team pull request #89
Opened 2023-07-17 07:34 UTC by wzrabbit

## 이슈번호
> #61 

## PR 내용
본 PR에서는 팀 플레이스 캘린더에서의 일정 등록을 위한 모달의 UI를 구현하였다.
모달 밖을 클릭하거나 닫기 버튼을 누르면 모달이 닫히는 등의 기본적인 상호작용이 포함되어 있다.

## 참고자료
- 스토리북
<img src="https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/ce0bb3b6-1ea5-401b-90c3-b845b4bcb686" width="500px" />

## 의논할 거리
`YYYY-MM-DD` 형식으로 필드를 작성할 수 있도록 하기 위해 `<input type="date" />` 를 사용하여 구현했는데, `<input type="datetime-local" />` 을 사용하면 `YYYY-MM-DD HH:MM` 까지 설정할 수 있는 것 같아.
둘을 서로 비교해봐도 좋을 듯?

- `datetime-local`
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/9d88d34c-c76d-4ee4-90a8-bd4c8b83879b)

코드가 많이 어지러운 편인데, 부디 바로잡아 줬으면 좋겠다. 많이 개선하면서 배울게...

2023-07-17 08:13 UTC, hafnium1923 reviewed
수고하셨슴둥~

2023-07-17 08:13 UTC, hafnium1923 commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +          <S.Input width="80px" marginright="40px" />
Input도 후에 공용컴포넌트를 만들게되면 대체하는게 좋을 것 같아!

2023-07-17 08:13 UTC, hafnium1923 commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +          <S.Input type="date" width="100px" />
요토가 말한 것 처럼
` <input type="datetime-local" />`
 이렇게 하는게 좋을듯!

2023-07-17 08:13 UTC, hafnium1923 commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +          <S.CloseButton variant="plain" type="button" onClick={closeModal}>
나는 Button 공용 컴포넌트를 사용하는게 좋을 것 같아.
1. Text 공용 컴포넌트의 스타일링 방법과 통일
2. Button이 공용 컴포넌트인 것을 명확하게 보여줌 -> 후에 스타일 충돌 날 때 어디를 봐야 할 지 바로 알아채기 쉬움
3. 버튼은 버튼인데 그 역할까지 명확하게 나타내야만 하는 이유가 있을까..?

2023-07-17 08:13 UTC, hafnium1923 commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +          <Text as="p" size="xxl" weight="bold">
Text 공용컴포넌트의 기본 태그는 p입니당

2023-07-17 08:13 UTC, hafnium1923 commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +        <S.ButtonMenu>
S.ButtonMenu는 굳이 있어야하나 싶어! 원래 요토가 했던 것처럼 하려면 styled(Button)이렇게 해서 한번에 하는 방법도 있고 Button을 그대로 사용하려면 cssprops 로 내리는 방법도 있을 거야

2023-07-17 08:13 UTC, hafnium1923 commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +          <S.Input width="80px" marginright="40px" />
그리고 나는 이렇게 스타일 컴포넌트에 prop로 내릴거면 차라리 지금 공용 인풋 컴포넌트를 만들어서 빼는건 어떨까? style 파일에 inputprops가 있는것도 좀 어색해보여!

2023-07-17 08:13 UTC, hafnium1923 commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.styled.ts
> +interface InputProps {
이렇게 할거면 공용컴포넌트로 빼는게 어떨까?

2023-07-18 01:33 UTC, wzrabbit commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +  teamPlaceLabel: string;
새로 이름을 바꾼다면 `teamPlaceName` 으로 바꾸면 좋을 것 같다는 생각이 드는구만!

> 혹은 나중에 teamPlaceId를 통해 teamPlace의 이름에 접근할텐데(전역 상태이든 뭐든간에) 
이 부분은
- 컴포넌트가 직접 전역 상태에 접근할 수도 있고
- 다른 상위 컴포넌트에서 전역 상태에 접근해서 받아온 값을 props를 통해 이 컴포넌트에 넘겨주는 방법  

이 될 수 있을 것 같다 생각했어.

어떻게 할 지 정해지지 않았기에 후자일 것이라 생각하고 UI만 구현하는 현 시점에서는 props 값을 자유롭게 바꿀 수 있도록 구현한 거였어! 이후 어떻게 값을 받아올지가 확실하게 결정되면 그 때 바꾸는 것을 고려하고 있는데, 루루는 어떻게 생각해?

2023-07-18 01:36 UTC, wzrabbit commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +          <S.Input type="date" width="100px" />
`datetime-local` 로 바꾸기 위해, 일단 input의 개수는 하나로 줄일게! 이후 다시 되돌리는 게 좋아보인다면 그 때 다시 의논해 보자고

2023-07-18 01:38 UTC, wzrabbit commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +          <S.Input width="80px" marginright="40px" />
그래... 이 부분은 `Input` 에 해당하는 공용 컴포넌트가 아직 없어서, 임시방편으로 구현한 거야.
이후 해당 공용 컴포넌트가 새로 생긴다면, 이 부분의 코드는 수정할게.

2023-07-18 01:38 UTC, hafnium1923 commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +  teamPlaceLabel: string;
오 맞는 말이야! 그럼 변수명만 수정해줘도 좋아

2023-07-18 01:42 UTC, hafnium1923 commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +          <S.Input width="80px" marginright="40px" />
그러면 간단하게라도 Input 컴포넌트를 빼서 지금 작성해두는것이 좋을 것 같애

2023-07-18 02:06 UTC, wzrabbit commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +        <S.ButtonMenu>
이거는 서로의 취향 차이로 보면 좋을 것 같다! 지금으로써는 확실히 Wrapper 을 두는 것은 필수적이지 않고, 버튼에 스타일을 주는 방법으로도 해결이 되니 코멘트를 반영했지만, 여기에 내 생각 정도는 두고 갈게.

루루 입장에서 지금 이 상황에서 Wrapper을 굳이 사용하지 않아도 되는데 왜 사용하는지 충분히 의문이 들 만하다고 생각해. 불필요한 상황에서는 굳이 이러한 코드를 쓸 필요성은 없을 것이고, 이후에 Wrapper가 필요해지면 그 때 넣으면 될 테니까.

이번에는 내부의 컴포넌트가 몇 개이든 상관없이 행별로 역할들을 먼저 나누고(`-Menu` 접미사) 구현했는데, 이렇게 하면

1. 각 메뉴(행)가 무슨 역할을 하는지 내부의 컴포넌트를 보지 않고 메뉴의 이름만 보는 것으로 판단하고 빠르게 작업해야 하는 부분을 찾을 수 있다고 생각함. 특히 내부의 컴포넌트가 무슨 역할을 하는지 명확하지 못할 때가 있는데 이런 상황에서 더 빛을 발할 수 있는 방법이라고 생각했음. 지금은 `<S.CloseButton>` 이기에 버튼의 역할이 명확하게 드러나지만 `<Button>` 으로 바꾸고 CSS Props를 내려주는 방향으로 바꾸면 이 버튼이 무슨 역할을 하는지 알아내기 어려울 수 있다고 생각해. 내부에 명확한 역할을 가진 컴포넌트가 있더라도 결국에는 그 내부의 컴포넌트를 보아야 알 수 있는 것 같아보이고.
2. 일관성 면에서도 행/열 단위로 먼저 레이아웃을 나누고 역할별로 내부에 컴포넌트를 넣는 방법은 유효한 것 같다고 생각하고 있어. Flex 레이아웃 내부에 들어가는 스타일 컴포넌트들을 모두 `<-Menu>`, `<-Menu>`, ... 형태로 통일시킬 수 있어. 다른 태그/네이밍의 컴포넌트가 중간중간 들어가지 않게 할 수 있지. 실제로도, `-Row`, `-Col` 을 사용해서 스타일 컴포넌트들의 네이밍을 정하고 격자 형태로 요소들을 배치하는 컨벤션도 있어.

2023-07-18 03:50 UTC, wzrabbit commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +          <S.Input width="80px" marginright="40px" />
아까 의논한대로, 대충이라도 공용 컴포넌트 구현해 놓고 다시 커밋할게 🆗

2023-07-18 03:55 UTC, wzrabbit commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +          <S.CloseButton variant="plain" type="button" onClick={closeModal}>
- 1번을 고려하면 공용 컴포넌트를 사용하는 거 나도 좋다고 생각해. 일관성은 당연히 중요하고, 이전의 코드가 해당하는 방법을 썼다면, 나도 그 방법을 따르는 것이 좋겠지.
- 3번은 포기하기 어려울 정도로 중요하다고 생각해. 어느 컴포넌트든 역할을 드러낼 수 있는 기회가 있다면 가능한 한 역할을 명확하게 보여주도록 심혈을 기울이는 것은 중요하다고 생각해. 역할이 잘 드러나는 코드는 곧 가독성이 좋고 유지보수에 좋은 코드일테니까. 그리고 이 역할을 드러내기 가장 좋은 방법은 - 컴포넌트의 이름을 명확하게 정하는 거지. 내부 컴포넌트들이나 속성들을 봐야 이해할 수 있는 것보다 훨씬 확실한 방법이라 생각해. 그런데 2번도 고려하자니, 고민되는 부분이네.

고민과 별개로 일관성을 따르는 건 중요하니 이 부분은 코멘트 반영할게!

2023-07-18 04:18 UTC, hafnium1923 commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +        <S.ButtonMenu>
오호 그런의미라면  `-Row`, `-Col` 를 붙이는게 더 명확할 것 같다는 생각!

2023-07-18 04:36 UTC, suyoungj requested changes

2023-07-18 04:45 UTC, wzrabbit commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +            <CloseIcon aria-label="닫기" />
`aria-label` 을 사용하는 위치에 대해서 잘 모르고 있었다...
버튼에 사용하는 게 확실히 더 타당해 보여. 반영할게!

2023-07-18 04:45 UTC, wzrabbit commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +          <S.Input width="80px" marginright="40px" />
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/daa98920-42e7-4837-8eb2-5b342a7154d3)

2023-07-18 06:22 UTC, wzrabbit commented
피드백 반영 완료!

CSS Props로 변경하기는 했다만, 이걸 또 인라인으로 사용할지 VS 변수로 선언해놓고 사용할지에 대해 의논이 필요해 보이네!
같은 css 속성을 여러 곳에서 사용한다면 믹스인 형태로 사용하면 좋겠지만, 그렇지 않은 경우라면 인라인이 편할 수도 있어 보이니!

`-Wrapper`, `-Container` 형태의 접미사를 사용하면서 네이밍들도 바꿨어. 그러니 CSS Props가 올바르게 사용되었는지, 새롭게 바뀐 네이밍은 적절한지 다시 검토해 줘야 할 것 같아.
고마워!

2023-07-18 06:27 UTC, suyoungj commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +            css={S.titleStyles}
styles 접미사가 꼭 필요할까? 소문자로 시작하는 네이밍은 괜찮은 것 같아

2023-07-18 06:27 UTC, suyoungj commented on frontend/src/components/common/Input/Input.tsx
> +const Input = (props: InputProps) => {
input은 여유로울 때 고도화하면 좋을듯?

2023-07-18 06:38 UTC, wzrabbit commented on frontend/src/components/common/Input/Input.tsx
> +const Input = (props: InputProps) => {
OK

2023-07-18 06:39 UTC, wzrabbit commented on frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
> +            css={S.titleStyles}
마침 의논도 끝났으니까 결정된 대로 다시 작업해서 커밋할게!

2023-07-18 06:45 UTC, suyoungj approved these changes
LGTM

2023-07-18 06:45 UTC, hafnium1923 commented on frontend/src/components/common/Input/Input.tsx
> +const Input = (props: InputProps) => {
인정합니다 일단 이렇게 두죠

2023-07-18 06:46 UTC, hafnium1923 approved these changes
아아아아주 수고하셨슴둥~

2023-07-18 06:46 UTC, merged