Refactor/fe/일정 요청 방식 변경
woowacourse-teams/2023-team-by-team pull request #897
Opened 2023-12-19 04:50 UTC by wzrabbit

# [FE] 변경된 일정 조회 명세가 작동하도록 팀 캘린더와 통합 캘린더 리팩터링
## 이슈번호
> close #895 #881

## PR 내용
본 PR에서는 회의 끝에 새롭게 변경한 아래의 두 명세에 대해 서비스가 올바르게 작동하도록 리팩터링 작업을 진행하였다.
1. 팀 캘린더 기간 조회 일정 명세
2. 통합 캘린더 기간 조회 일정 명세

## 참고자료
명세는 아래와 같이 변경되었다. 아래의 예시는 팀 캘린더의 명세로, 실제로는 통합 캘린더의 명세도 같은 형식으로 변경되었음에 유의한다.

Before:
/api/team-place/{teamPlaceId}/calendar/schedules/?year={year}&month={month}

After:
/api/team-place/{teamPlaceId}/calendar/schedules?startdate=yyyymmdd&enddate=yyyymmdd

## 의논할 거리
API 서버와 `YYYYMMDD` 형식으로 소통하려면 먼저 `Date` 객체를 `YYYYMMDD` 형식으로 변환하는 과정이 필요해 보여
그래서
1. **컴포넌트 → tanstack-query 로직이 담기는 커스텀 훅** 으로 호출하는 쪽에서는 `Date` 객체 형태로 호출하고
2. **tanstack-query 로직이 담기는 커스텀 훅이 담기는 커스텀 훅** 에서 `YYYYMMDD` 형식으로 변환하는 과정을 거친 뒤
3. **tanstack-query 커스텀 훅 → 직접 API를 호출하는 비동기 로직** 으로 호출하는 쪽에서는 `YYYYMMDD` 형식으로 호출하는 방법

을 사용 중이야
각 함수의 역할 배분은 괜찮아 보일까? 왜냐하면, 처음부터 `Date` 객체로 호출하지 않고 컴포넌트에서 호출할 때 처음부터 `YYYYMMDD` 형식으로 호출하는 방법도 있거든, 방법이 하나가 아닌지라

고민해 보고 코멘트 남겨줘!

2023-12-19 10:17 UTC, hafnium1923 requested changes
오~ 의논할 거리에 대해 나의 생각을 적어보자면 굳이 generateYYYYMMDD를 따로호출해야할 필요가 있을까싶어 무슨 뜻이냐면
지금 변경된 명세로 인해 useFetch~ 를 호출하기 전에 모두 getFirstLast~ 유틸함수를 호출하고 있는데 애초에 이친구의 반환값으로 generateYYYYMMDD를 돌린 값이 나오면 한단계는 줄일 수 있을 것 같다는 뜻이야.
왜 이게 좋을 것 같나면 반환값이 yyyymmdd로 통일한다면 이 기능이 확장되었을 때 다시한번 변환해야하는 단계를 신경쓰지 않고 개발할 수 있을 것 같아서.( 개발자의 편의성을 위해ㅋㅋ) 
어떻게 생각해?

2023-12-19 10:17 UTC, hafnium1923 commented on frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
> +  const firstDateOfPreviousMonthCalendar = new Date(
이전달과 다음달도 위의 친구처럼 할 수 있을 것같은데 따로 계산을 해야하는 이유가 뭐야?

```suggestion
 const { firstDateOfPreviousMonthCalendar, lastDateOfPreviousMonthCalendar } =
    getFirstLastDateOfCalendar(year, month -1);
```

2023-12-19 10:17 UTC, hafnium1923 commented on frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
> +  const firstDateOfPreviousMonthCalendar = new Date(
위 변수명의 형식대로 변수를 짓자 너무 길어지는 것 같아서..
```suggestion
  const firstDateOfPreviousCalendar 
```
이거 아니면
```suggestion
  const firstDateOfPrevCalendar
```
어때?

2023-12-19 10:17 UTC, hafnium1923 commented on frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
팀캘린더에 대한 변경 제안사항은 통합캘린더와 동일하니 따로 적어두지 않을게~!

2023-12-19 14:22 UTC, wzrabbit commented
## 반영 전 코멘트

> 지금 변경된 명세로 인해 useFetch~ 를 호출하기 전에 모두 getFirstLast~ 유틸함수를 호출하고 있는데 애초에 이친구의 반환값으로 generateYYYYMMDD를 돌린 값이 나오면 한단계는 줄일 수 있을 것 같다는 뜻이야.

앗 `generateYYYYMMDD` 를 굳이 따로 만든 이유는, `getFirstLastDateOfCalendar` 는 `generateScheduleBars`(스케줄 바를 생성하는 그 유틸함수에서 본래 연산을 위해 사용되던 함수이기에, `getFirstLastDateOfCalendar` 함수 자체의 반환값을 바꾸도록 구현할 생각은 하지는 못했어

그렇지만, `yyyymmdd` 데이터를 얻기 위한 과정이 번거롭게 느껴진 점은 충분히 이해되는 것 같아
- 현재 과정: `year`, `month` → 달력의 시작 날짜의 `Date()`, 달력의 끝 날짜의 `Date()` → `yyyymmdd`

중간 과정이 무조건 필요한 것이 아니기에 **한 단계를 줄여보자는** 조언을 해 준 것 같아, 그렇다면 아래의 방법대로 한다면 어떨 것 같아?

- 아래의 함수를 새롭게 만든다.
```tsx
const generateYYYYMMDDRange = (year, month) => {
  // year와 month를 이용해 YYYYMMDD 형식으로 시작 일자, 끝 일자를 만든다
  
  return { startDateFormat, endDateFormat };
};
```

- 과정을 `generateYYYYMMDDRange` 함수를 사용하여 진행한다면 아래와 같이 수정이 가능하다.
`year`, `month` → `yyyymmdd`

이렇게 하면 전체 플로우는 아래와 같이 바뀔 것으로 보여, 사용하는 측에서 `Date` 객체를 사용하는 대신 바로 `YYYYMMDD` 타입을 이용해 요청을 하게 될 듯?

- 팀 플레이스 번호와 같이 이번 PR과 관련없는 변수들은 생략
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/03fa7d6e-5c3f-4ed6-954e-55be4799933b)

2023-12-20 07:07 UTC, hafnium1923 commented
그러니까 기존에 있는 함수를 사용하는 것이 아닌 새로운 유틸함수를 만들자 이건가? 
새로운 유틸함수에서  getFirstLastDateOfCalendar와 동일한 일을 하지만 반환값이 YYYYMMDD 인거야?

2023-12-21 15:08 UTC, wzrabbit commented
응 맞아~ 어제 내가 이야기했으니까
혹시 더 깔끔해 보이는 구조가 생각난다면 부디 코멘트로 남겨줘~

그게 아니라면 새롭게 생각한 구조대로 다시 짜볼게!

2023-12-24 19:08 UTC, wzrabbit reviewed
반영 완료!
변경 사항 중에 여전히 개선되어야 할 부분이 있으면 알려주되,
내가 사정상 코드를 못 만지게 된다면, 그 때는 직접 변경해도 괜찮아!

2023-12-24 19:18 UTC, wzrabbit commented on frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
> +  const firstDateOfPreviousMonthCalendar = new Date(
이 요구사항을 반영하기 전에는 이전 달 / 다음 달의 일정을 삼항연산자로 그 자리에서 계산해서 요청했는데, 루루는 보통 따로 변수를 만들어서 대입하는 것을 좋아하는 것으로 알고 있어~ 리턴할 때에도 보통 리턴할 값을 변수로 정리한다음 리턴하는 걸 선호하는 것도 기억하고

일단 내가 봤을 때는 이렇게 내버려둬도 괜찮은 것 같고 따로 이전 달에 해당하는 변수 등을 `prevCalendarMonth` 과 같은 변수로 선언한 뒤
```tsx
const prevCalendarYear =  month === 0 ? year - 1 : year;
const prevCalendarMonth = month === 0 ? 11 : month - 1;

usePrefetchMySchedules(
  generateCalendarRangeByYearMonth(
    prevCalendarYear,
    prevCalendarMonth,
  ),
);
```
형태로 사용하는 것도 괜찮아 보이고~
어떤 방식을 좋아해?

2023-12-25 04:32 UTC, wzrabbit commented on frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
> +    ),
오 ㅋㅋ 바꾸고 나니까 순서가 바뀌었다는 걸 깨달았네
그치만 `{다음 달, 이전 달}` 의 정보를 prefetch하던 거를 `{이전 달, 다음 달}` 의 순서로만 바꾼 거니까 지장은 없을 거야
그치만 순서 바꾸고 싶으면 이야기하구

2023-12-26 03:04 UTC, hafnium1923 commented on frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
> +  const firstDateOfPreviousMonthCalendar = new Date(
나는 아래꺼가 더 좋아보이네! 패치 안에 함수 안에 삼항연산자가 있으니까 가독성이 너무 떨어지는 것 같거든!

2023-12-26 03:06 UTC, hafnium1923 reviewed
삼항연산자 대입하던거 변수에 할당하다가 대입하는거로만 바꾸면 될 것 같애! 수고했어~!

2023-12-26 15:40 UTC, wzrabbit commented
b1479c68394552277d384d39ea6e464438925410

반영 완료!

2023-12-27 05:32 UTC, hafnium1923 approved these changes

2023-12-27 05:32 UTC, merged