[FE] 팀바팀 전반적인 모달 사이즈 조정
woowacourse-teams/2023-team-by-team pull request #937
Opened 2024-02-18 13:19 UTC by hafnium1923

# [FE|BE|ALL] PR 타이틀 
## 이슈번호
> close #936 

## PR 내용
전 후 사이즈 비교 
(왼쪽- 후 / 오른쪽 - 전)
<img width="1349" alt="스크린샷 2024-02-18 오후 10 16 41" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/2b28680b-1a96-428d-9018-1ba2dd745df9">
<img width="1288" alt="스크린샷 2024-02-18 오후 10 16 52" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/087d1e98-4099-4508-8663-2305f5fdcc69">
<img width="992" alt="스크린샷 2024-02-18 오후 10 17 13" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/37bfe304-c399-4ddd-8874-a011003b05e0">
<img width="1153" alt="스크린샷 2024-02-18 오후 10 17 39" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/75f0b607-429b-4c04-9eea-8fec6471765a">
<img width="1357" alt="스크린샷 2024-02-18 오후 10 17 50" src="https://github.com/wo
<img width="1428" alt="스크린샷 2024-02-18 오후 10 18 20" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/01459ad7-8b38-452f-bd5d-4934a8da571f">
owacourse-teams/2023-team-by-team/assets/79538610/9cf74a93-639f-4f8d-8b33-ec54ba35194e">
<img width="1396" alt="스크린샷 2024-02-18 오후 10 18 06" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/7953
<img width="1211" alt="스크린샷 2024-02-18 오후 10 18 14" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/4dce3bc5-1332-4753-bd7c-9777544799de">
8610/a87be0d5-db30-4a49-af49-6ebadf9eb055">

2024-02-25 14:37 UTC, wzrabbit requested changes
@hafnium1923 👋🏻 

미안해 루루, 리뷰가 늦었지?
모달 크기가 너무 불필요하게 큼지막한 경우가 있어서 이 PR을 작성했을텐데, 변경사항 확인해 보니까 대체로 좋은 것 같아

특히 눈에 잘 안 띄는 부분을 개선한 것도 몇 가지 보이더라

별도의 스타일/디자인에 대한 피드백은 없고, 오로지 기능만 보면서 예상과 다르게 작동할만한 부분만 피드백해 뒀어
수고 많았어!

2024-02-25 14:37 UTC, wzrabbit commented on frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.styled.ts
>      `;
1. `DailyScheduleModal` 과 동일하게, 이 모달도 클릭되는 스케줄 바의 위치에 따라 위치가 다르고, 공식이 하드코딩 되어 있으므로 수정이 필요할 거야! -- 공식은 내가 봤는데도 복잡해 보여서 그냥 내가 만져보면서 맞춘 변경사항만 여기 올려볼게

    - 위치: `ScheduleModal.styled.ts`, Line 141 ~ Line 152
```ts
 return css`
  position: absolute;
  top: ${(row < 3 ? 92 : -128) + (row + 1) * 110 + level * 18}px;
  left: ${(column > 3
    ? calendarWidth / 7 - 446
    : column === 3
    ? calendarWidth / 14 - 223
    : 0) +
  calendarLeft +
  (calendarWidth * column) / 7}px;
`;
```

2. 일정 모달의 경우 변경 이후 모달의 크기가 굉장히 작아졌더라고, 우선 이 PR을 적은 이유가 모달들의 크기가 너무 커서 사용하기 힘들기에 줄이고자 한 것이니 취지는 공감이 돼. 다만 크기를 많이 줄이는 과정에서, 날짜가 나타나는 텍스트 (ex: `2024년 1월 1일`) 칸의 여유가 너무 없어져서, 일부 상황에 한해 날짜가 다음 줄로 넘어가는 문제가 생기고 있는 것 같아

    - 우선, Pretendard는 고정폭 글꼴이 아니야, 그렇지? `1`은 폰트에서 가로 크기를 적게 먹어서, 이렇게 `1`이 들어간 일정은 정상적으로 한 줄에 나타나는 편이야


    ![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/3177d1fe-53d7-4465-8826-b0feaddc37e3)


    - 그런데, 이렇게 일정에 `1`이 하나도 없는 경우, 텍스트의 너비가 너무 길어져서 다음 줄로 넘어가는 경우가 있는 것 같아, 이거는 루루의 컴퓨터에서도 한 번 테스트해 볼 수 있을까? 일정에 `1`이 하나도 없는 케이스로 말이야.

    ![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/87642422/4f1aebc7-b851-4c29-bb64-803e48e19369)

    - 이 경우를 생각하지 않더라도, 낮은 확률로 사이트를 로딩할 때 폰트를 받아오지 못해 기본 폰트(이마저도 환경에 따라 엄청 다양)가 사용되는 경우도 있을 거고, 유저가 별도의 폰트를 설정해 둔 경우도 있을 거야, 이 때는 텍스트의 길이가 소폭 변할 수도 있어. 그래서, 루루의 변경사항은 좋은 것 같지만, 날짜가 들어가는 텍스트 박스의 크기만큼은 만일의 상황을 대비해 **조금의 여유를 두는 것**을 제안하고 싶어, 이전 모달만큼 엄청 여유롭지 않아도 괜찮아

2024-03-10 04:54 UTC, hafnium1923 commented on frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.styled.ts
>      `;
오 내 컴퓨터에서 동일한 문제가 나오더라구! 넓이에 여백을 주는거 동의해 하지만 지금 모달크기도 작다고 생각되진 않아서,,, 차라리 날짜의 글씨크기를 lg에서 md로 변경했어 그러면 요토가 말해준 문제도 발생하지 않고 오히려 글씨가 적절하게 작아진 것 같더라구

![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/6879b31f-e43f-4039-a9ed-c9ffbe0f9fe6)

2024-03-10 04:54 UTC, hafnium1923 commented on frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.styled.ts
> +  width: 250px;
친절하신 요술토끼님....

2024-03-10 04:58 UTC, hafnium1923 reviewed
안녕 요토~!~!~ 너무 오랜만에 반영했지,,ㅎㅎ 미아내,,,,,,
일단 요토가 내가 생각하지 못한 부분까지 짚어줘서 수정이 편했어. 정말 고마워! 나중에 현업에서 일하더라도 요토와 같은 팀원이랑 일하고 싶다는 생각이 들어.(진짜 진심이야!!!)
그래서 요토가 알려준 부분은 다 수정했고 말해줬던 일정모달에 대해서는 글자크기를 줄이는 방식으로 해결했어. 코멘트에 사진을 달아두었는데 글자크기를 줄이는 게 줄이기 전보다 더 자연스럽더라구(내눈에는) 한번 확인해보고 이상하면 알려줘 글자크기는 되돌리고 넓이를 늘려볼게

언제나 고마워!

2024-03-11 12:44 UTC, merged