[BE] 기간 지정 팀플레이스 일정 조회 기능 구현
woowacourse-teams/2023-team-by-team pull request #95
Opened 2023-07-18 01:50 UTC by pilyang

## 이슈번호
> #19

## PR 내용

- 기간을 지정해서 기간 내 팀플래이스 일정 조회 기능 구현
- 테스트요 더미데이터 추가
- 요청 쿼리 누락 또는 정수가 아닌 입력시 400에러 발생

## 참고자료

## 의논할 거리

- TODO comment 남겨둔거 있는데 확인 부탁드립니다!

2023-07-18 01:52 UTC, pilyang commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
> +        checkTeamPlaceExist(teamPlaceId);
이부분 의견 남겨주시면 감사하겠습니다!!!

2023-07-18 08:00 UTC, hafnium1923 commented
정렬해서 보내주시면 감사....

2023-07-19 04:29 UTC, sh111-coder requested changes
일정 조회 코드보니까 제가 했으면 더 오래걸렸을 거 같은데 짱짱이네요,, ✌🏻

오타 부분만 수정해주시면 Approve 하겠습니다!

2023-07-19 04:29 UTC, sh111-coder commented on backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
> +        final LocalDate endDAte = startDate.with(TemporalAdjusters.lastDayOfMonth());
이 부분 변수명 endDAte -> endDate로 수정되어야 할 것 같습니다!

2023-07-19 05:39 UTC, pilyang commented on backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
> +        @DisplayName("요청에 패스쿼리가 누락되면 조회에 실패한다.")
날짜정보라도 표현 수정했습니다!!

2023-07-20 01:25 UTC, sh111-coder approved these changes
수고하셨습니다!!!

2023-07-20 01:26 UTC, SproutMJ approved these changes
good

2023-07-20 01:26 UTC, merged